### ISSUE TITLE
Please create import fucntion for Putty hosts

### ISSUE THREAD

**Issue by chinupf** [kingToolbox/WindTerm#1]
Please include a function to import saved sessions from putty (if possible), to be found in the following registry key:

Computer\HKEY_CURRENT_USER\Software\SimonTatham\PuTTY\Sessions

Thank you!

**Comment by kingToolbox** [comment]
Thanks, I will provide this function in next release.

**Comment by kingToolbox** [comment]
This has been done in version 0.92.
