### ISSUE TITLE
Share session config by MySQL/SQLite

### ISSUE THREAD

**Issue by LinWanCen** [kingToolbox/WindTerm#100]
I compared many similar software. This software has the best performance and the most beautiful.
Everyone in our test environment has to configure especially troublesome,
Hope to save the test environment without setting the master password,
**Configuration can share configuration with database like mRemoteNG**
(The mRemoteNG does not support sz/rz and there is no file viewing and dragging function which is why I did not choose).

**Comment by kingToolbox** [comment]
Sorry for the late reply. These two days have been busy with the testing and release of the new [WindTerm_prerelease_3](https://github.com/kingToolbox/WindTerm/releases/tag/2.1). 

MySQL and SQLite are not convenient as the json configuration files and too heavy. In WindTerm, you can just copy the "profiles" folder from the current computer to the other computers and all the sessions and configuration will be restored.

It does not matter whether you set a master password or not, as long as you can enter the correct master password, you can migrate and use it at will. You can try it. :smile:

**Comment by LinWanCen** [comment]
I looked at the files in the profile folder, it was very convenient.😄

However, it is not divided into different folders according to the group tree. It is not convenient to use Git to share by group.

I don't know if there are other good ideas for real-time sharing.🤔

I tried an empty password, but it still automatically locks the screen, can I set it not to lock the screen automatically?

**Comment by xzhuiz** [comment]
open the global\wind.config file,
set like   "application.lockScreenTimeout": -1,

**Comment by kingToolbox** [comment]
Thank you xzhuiz for your help. You can set `application.lockScreenTimeout` to 0 or a negative number to disable the lock screen.

In addition, for real-time sharing, you can write a shell script to automatically parse the session configuration and divide it into different folders according to the group tree when you commit it to git. This can be done easily using git hooks, you can read [Customizing Git - Git Hooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) to learn more.

**Comment by kingToolbox** [comment]
Hello, it looks like this issue has been resolved and can be closed. Welcome to continue submitting new issues and feature requests, thank you.
