### ISSUE TITLE
v2.1.0_prerelease_3 close and start  error

### ISSUE THREAD

**Issue by gooker** [kingToolbox/WindTerm#103]
just down, open cmd and close start

delete reopen.history  restart ok.
<img width="1163" alt="20210528085411" src="https://user-images.githubusercontent.com/5688076/119914208-4ba27300-bf92-11eb-91ba-0de4a7299f97.png">

**Comment by kingToolbox** [comment]
Thank you. I noticed this and just fixed this bug, please redownload the new [WindTerm_prerelease_3](https://github.com/kingToolbox/WindTerm/releases/tag/2.1) and it should be OK now.

**Comment by gooker** [comment]
Test ok

**Comment by kingToolbox** [comment]
Thank you! :smile:
