### ISSUE TITLE
连接报错：Unknown error

### ISSUE THREAD

**Issue by DuanXiangXiang** [kingToolbox/WindTerm#1036]
![image](https://user-images.githubusercontent.com/75104073/184519948-35ff164e-7cc6-4891-8a61-2b253f632659.png)

**Comment by DuanXiangXiang** [comment]
有些可以正常登录

**Comment by DuanXiangXiang** [comment]
![image](https://user-images.githubusercontent.com/75104073/184520283-cbf2bd96-7825-456a-b7d3-0e9bd921661b.png)

**Comment by ayuayue** [comment]
> ![image](https://user-images.githubusercontent.com/75104073/184520283-cbf2bd96-7825-456a-b7d3-0e9bd921661b.png)

把密码显示出来，看是否复制的有问题或ssh能否正常，是否使用代理等

**Comment by DuanXiangXiang** [comment]
> > ![image](https://user-images.githubusercontent.com/75104073/184520283-cbf2bd96-7825-456a-b7d3-0e9bd921661b.png)
> 
> 把密码显示出来，看是否复制的有问题或ssh能否正常，是否使用代理等

![image](https://user-images.githubusercontent.com/75104073/186703458-93541dcc-f8b7-4616-9ea0-3d8cd03d2eaa.png)
我把验证的这里的取消就可以了

**Comment by laosuantang** [comment]
> > > ![image](https://user-images.githubusercontent.com/75104073/184520283-cbf2bd96-7825-456a-b7d3-0e9bd921661b.png)
> > 
> > 
> > 把密码显示出来，看是否复制的有问题或ssh能否正常，是否使用代理等
> 
> ![image](https://user-images.githubusercontent.com/75104073/186703458-93541dcc-f8b7-4616-9ea0-3d8cd03d2eaa.png) 我把验证的这里的取消就可以了

我也曾经面临同样的问题，按你的设置解决了

**Comment by distantlullaby** [comment]
2023年10月19日  按照上图的验证设置，可以登录了
