### ISSUE TITLE
Suspend processing issues for a period of time

### ISSUE THREAD

**Issue by kingToolbox** [kingToolbox/WindTerm#104]
Hello, everyone. I will take the summer vacation and suspend the handling of the issues for a period of time, because I won’t have internet during that time. But I will continue to complete some features and bugs so that I can release the WindTerm v2.1.0 and [WindEdit](https://github.com/kingToolbox/Digedit) v1.0.0 soon after I come back. 

If you have any feature request or issue, please feel free to submit it. I will deal with it when I come back, thank you. 

Let's meet again in June.

**Comment by hongnod** [comment]
The new 2.10 pre3 has some strange issues when copy old profile to its folder.

**Comment by kingToolbox** [comment]
Thank you very much. I have fixed and re-uploaded the WindTerm_2.1.0_Prerelease_3 version that day. Now the new [WindTerm_2.1.0_Prerelease_4](https://github.com/kingToolbox/WindTerm/releases/tag/2.1-prerelease) is also released, you can download and use it. And because I have come back, I think this post is no longer needed and will be deleted soon. :smile:
