### ISSUE TITLE
Can I not set the master password?

### ISSUE THREAD

**Issue by ranbest** [kingToolbox/WindTerm#106]
Can I not set the master password ,  or can I configure it?

**Comment by kingToolbox** [comment]
Sorry for the late reply, I just returned from vacation. You can reset the master password to empty to disable it. Please read [Enhanced Protection / Change Master Password](https://kingtoolbox.github.io/2021/04/23/change-master-password/) to learn more, thank you.

**Comment by 107295472** [comment]
Forgot your password? What should I do

**Comment by ranbest** [comment]
> Forgot your password? What should I do

thank you.  I have reset the password to empty。

I mean, when I did not set the master password. I can log in directly without entering the master password。








> Sorry for the late reply, I just returned from vacation. You can reset the master password to empty to disable it. Please read [Enhanced Protection / Change Master Password](https://kingtoolbox.github.io/2021/04/23/change-master-password/) to learn more, thank you.

thank you.  I have reset the password to empty。

**Comment by ranbest** [comment]
I have reset the password to empty as an alternative

**Comment by kingToolbox** [comment]
Ok. Welcome to continue submitting new issues and feature requests, thank you. :smile:
