### ISSUE TITLE
Drag and drop transfer files from intellij's directory tree is fine, but vscode is not

### ISSUE THREAD

**Issue by xzhuiz** [kingToolbox/WindTerm#107]
The drag-and-drop to transfer files is very, very convenient and very cool.

**Comment by kingToolbox** [comment]
I tested VS Code, and unfortunately, VS Code only passes the file path as the plain text, not as the mime `text/uri-list`, which means the dragged data are actually references to files or objects, so unless VS code changes this, WindTerm can’t transfer files by dragging and dropping them from VS Code.

**Comment by kingToolbox** [comment]
Hello, I suggest submitting this issue to VSCode, as long as it supports the new `text/uri-list` copy format, WindTerm can support it well.
