### ISSUE TITLE
What is the default password to unlock the screen?

### ISSUE THREAD

**Issue by Water26** [kingToolbox/WindTerm#1089]
<img width="500" alt="image" src="https://user-images.githubusercontent.com/26089659/185871674-db8ff0c9-dedc-486f-a609-c6b6cb4eb89c.png">

**Comment by paulzlb** [comment]
安装目录的global下，有个wind.config文件，搜索"lock",把timeout的时间改成0或者-1非正数就行

**Comment by paulzlb** [comment]
安装目录的global下，有个wind.config文件，搜索"lock",把timeout的时间改成0或者-1非正数就行

**Comment by paulzlb** [comment]
重启后就没锁了

**Comment by x1ntt** [comment]
没有设置密码 就直接按下回车就行了

**Comment by kingToolbox** [comment]
The default `master password` is empty, just press `Enter` to unlock. If you don't want to automatically lock the screen, you can set `Menu - Session - Preferences - Settings - Security - Lock screen timeout` to `off` to turn it off.

**Comment by Water26** [comment]
> 安装目录的global下，有个wind.config文件，搜索"lock",把timeout的时间改成0或者-1非正数就行

按你这个设置后就可以了，谢谢

**Comment by hhf1949** [comment]
> 安装目录的global下，有个wind.config文件，搜索"lock",把timeout的时间改成0或者-1非正数就行

有效
