### ISSUE TITLE
default font capitalization

### ISSUE THREAD

**Issue by li-dianzheng** [kingToolbox/WindTerm#1092]
My computer uses a touchpad, and sometimes I always zoom in and out accidentally. I wish I could add a shortcut key to restore default font capitalization, like: ctrl + 0

**Comment by kingToolbox** [comment]
There is currently no setting interface for shortcut keys. Please open `WindTerm_install_path/global/wind.keymaps` and add:
```
  { "keys": "<Ctrl+0>",
    "modes": "normal, command, local, remote",
    "action": "Text.ResetZoom"
  }
```
In addition, you can also directly use the existing shortcut keys `Ctrl+=` and `Ctrl+-` to zoom in and out.

**Comment by li-dianzheng** [comment]
It.s working. Thanks

**Comment by kingToolbox** [comment]
Thank you for your feedback. This issue has been solved and will be closed. Welcome to continue submitting new feature requests and bugs.
