### ISSUE TITLE
In docker container cli,Press arror key

### ISSUE THREAD

**Issue by sonce** [kingToolbox/WindTerm#1102]
For example:
``` shell
k3s kubectl exec -it jump -n dev /bin/sh
```
Enter jump container cli.
I want to run pre command,press arrow key of UP。
it show ^[[A。
![image](https://user-images.githubusercontent.com/887972/186298705-311c3d03-5af5-4460-af5c-107dc89150c8.png)

**Comment by xywf221** [comment]
This is the default SH in the container. You can try bash

**Comment by sonce** [comment]
Thank you ,I try /bin/bash ,it is right.
