### ISSUE TITLE
Feature:bookmark folder

### ISSUE THREAD

**Issue by sonce** [kingToolbox/WindTerm#1103]
Hi,
I try Auto Sync Terminal Folder, it is has a good experience.
I often visit a folder,I want to a bookmark list or history,to select the folder,and auto cd in it.
thanks.

**Comment by kingToolbox** [comment]
I suggest you add a button to the [QuickBar](https://kingtoolbox.github.io/2020/08/22/quickbar/) with the text `cd /your/favourite/folder/path`, so that you can get what you want.

**Comment by sonce** [comment]
Thank you ,it is great.
