### ISSUE TITLE
v2.5.0 can not create session dir, that make session management very difficult

### ISSUE THREAD

**Issue by libaoan** [kingToolbox/WindTerm#1113]
![image](https://user-images.githubusercontent.com/39528143/186552920-f4bd0559-34b8-455b-bcf6-fd9f9aa69ea2.png)

**Comment by kingToolbox** [comment]
Please fill in the folder name you want in the `Session Settings Dialog - SSH -Session - Group` input box. Also, use the `>` character (eg `a > b > c`) to get nested folders.

![image](https://user-images.githubusercontent.com/51009775/186621359-6495cbd6-cd89-4fc7-9463-cd8a141ccee8.png)

**Comment by libaoan** [comment]
i see, tks!
