### ISSUE TITLE
Commands executed after authentication are not automatically executed

### ISSUE THREAD

**Issue by buleseli** [kingToolbox/WindTerm#1118]
在SSH会话中设定了'认证后执行命令',WindTerm确实发送了命令,但此命令未自动回车执行,希望发送完用户设定的命令后能够自动回车执行!

**Comment by kingToolbox** [comment]
That's how it was designed. Not every command entered needs to be executed automatically. For example, you may sometimes need to append some text to the end.

If you need the command to be executed automatically, just add `\n` to the end of the command.

**Comment by buleseli** [comment]
i know it ,tks!

**Comment by lovelycheep** [comment]
请问如何输入多条命令；比如我登录堡垒机需要先输入2\n，
