### ISSUE TITLE
Is there any feature like multi-windows input?

### ISSUE THREAD

**Issue by RandalTeng** [kingToolbox/WindTerm#1128]
hello there, i'm wonder that is WindTerm has any feature like multi-windows input, just like MobaXTerm?

MobaXTerm's screenshot:

![image](https://user-images.githubusercontent.com/13815562/186719709-a2774367-a9c3-4915-ab2d-d06590d09557.png)

![image](https://user-images.githubusercontent.com/13815562/186720429-c84a6062-7031-42dc-9947-a39f70368709.png)

**Comment by kingToolbox** [comment]
This feature has already been developed. Please read [Sync Input](https://kingtoolbox.github.io/2021/05/27/sync-input/) to learn more, thank you.

**Comment by RandalTeng** [comment]
> This feature has already been developed. Please read [Sync Input](https://kingtoolbox.github.io/2021/05/27/sync-input/) to learn more, thank you.
Got it, thank you very much, i had search with multi input, but not "sync input", so, thanks again.
