### ISSUE TITLE
SSH can't login QNAP NAS。

### ISSUE THREAD

**Issue by dustxdustx** [kingToolbox/WindTerm#1136]
SSH server   QNAP 453Bmini   fireware Ver 5.0.0 1986 build 20220324
SSH client   WIndterm 2.50 for MAC
1.When try to  ssh the NAS，input username（admin），and click “continue”
2.prompt “authentication be refused，try agin plaease！” and can't login
But Electerm is OK 。
Fix this problem，please。

**Comment by dustxdustx** [comment]
@tino926   Thanks you very much，It work！

**Comment by RenBuShengTian** [comment]
I experienced the same matter, and the solution in the previous post was extremely helpful.
After a few more attempts, I discovered that the "Attempt keyboard-interactive authentication" option seemed to be the source of the conflict.
In my environment, simply unchecking this box solves the issue.

楼上的方法很管用。我又试了一下，发现只需要取消勾选”尝试键盘交互验证“就可以解决这个问题。
