### ISSUE TITLE
how to turn off that CurrentDir?

### ISSUE THREAD

**Issue by sleepingforest2** [kingToolbox/WindTerm#1160]
just like this 
![image](https://user-images.githubusercontent.com/40165891/187818427-f3abcca1-e8f0-47e8-a3b5-959c5ec427a6.png)
i want to hide that message

**Comment by slankka** [comment]
Same problem!!! 

It is a protocol:
```
export PS1="$PS1\[\e]1337;CurrentDir="'$(pwd)\a\]'
```
https://github.com/Eugeny/tabby/wiki/Shell-working-directory-reporting

WindTerm does not support it.
I found that VScode support it. https://github.com/microsoft/vscode/issues/157567

**Comment by oicu** [comment]
There is a method to solve the problem.

WindTerm Session Settings:
Term: `xterm`

---

`.bash_profile`
```
if [ "${TERM}x" == "xterm-256colorx" ]; then
    export PS1="$PS1\[\e]1337;CurrentDir="'$(pwd)\a\]'
fi
```
