### ISSUE TITLE
Whether you can add a custom setting is up to the user to decide whether to support the functions of double-click copy and right-click paste

### ISSUE THREAD

**Issue by guntm124** [kingToolbox/WindTerm#117]
Whether you can add a custom setting is up to the user to decide whether to support the functions of double-click copy and right-click paste

**Comment by kingToolbox** [comment]
WindTerm supports **Select-to-copy** and **middle-click-to-paste**, but **double-click copy** and **right-click paste** are not yet supported.

WindTerm also supports drag and drop the selection to input it, which is faster than any `copy and paste` method, especially without the side effects of overwriting the clipboard.

You can read [this comment](https://github.com/kingToolbox/WindTerm/issues/19#issuecomment-719334753) to learn more about **Select-to-copy** and **middle-click-to-paste**, and you can watch the video [Tips / Input By Dragging And Dropping Text](https://kingtoolbox.github.io/2020/06/20/tips-input-by-dragging-and-dropping-text/) to learn about `drag-and-drop selection to copy-and-paste`. I'm sure you will like it.

I think **double-click copy** is too limited. Even if WindTerm can select text intelligently, double-clicking can usually only select a few types of text such as words or URLs. **Select-to-copy** actually not only includes the function of **double-click copy**, it is also more flexible. 

Similarly, **right-click** is more suitable for popping up a right-click menu, which is a waste of just pasting. The reason for the existence of **right-click paste** is that the dumb terminal did not have the function of the right-click menu a long time ago, so it was designed in this way. It should be said that it is not very timely. 

What do you think?

**Comment by Liuhongdan** [comment]
I also wanted this **right-click paste** long time ago. But now **Select-to-copy** and **Shift-Ins** are OK for me.

**Comment by kingToolbox** [comment]
The new version [WindTerm_2.1.0_Prerelease_6_Windows_Portable](https://github.com/kingToolbox/WindTerm/releases/tag/2.1-prerelease) has just been released. In this version, the `right-click-to-paste` feature has been well supported. Please download and use it.

The default action of right click is still showing the right-click menu. After downloading it, you need set **terminal.rightClickAction** in `WindTerm_install_path/profiles/default.v10/user.config` or `WindTerm_install_path/global/wind.config` to **PasteText** to enable it. I recommend setting **text.autoCopySelection** to **true** at the same time to make it more convenient. Thank you.

I still think the right-click menu is more useful than `right-click-to-paste`. But I am only a tool maker and I need to meet your needs. And I have to say that the power of habit is really amazing. :smile:

**Comment by kingToolbox** [comment]
It looks like the problem in this post has been solved. This issue will be closed and welcome to continue submitting new issues and feature requests. Thank you!
