### ISSUE TITLE
Sender loss

### ISSUE THREAD

**Issue by karagi4** [kingToolbox/WindTerm#118]
Hello!
Sometimes I need to hide the sender in the bottom panel for convenience, but then the panel is very difficult to get back. Is it possible to make a convenient button?
![2021-07-07_15-09-17](https://user-images.githubusercontent.com/41114204/124757470-4abc1400-df36-11eb-9c34-2f4cf5f60c5a.png)

**Comment by kingToolbox** [comment]
From the screenshot I guess you are using WindTerm_2.1.0_Prerelease_4. The WindTerm_2.1.0_Prerelease_5 has added `Focus Mode` and `Layout` features, which are exactly what you want. And today [WindTerm_2.1.0_Prerelease_6](https://github.com/kingToolbox/WindTerm/releases/tag/2.1-prerelease) just happened to be released. So please download the latest version and use.

If you frequently open and close `sender` pane repeatedly, I suggest you use `Focus Mode` to quickly switch between the two layouts. If not, I suggest you use the layout button on the menubar, it can also easily close and open the `sender` pane. You can read [Focus Mode](https://kingtoolbox.github.io/2021/06/28/ui_focus_mode/) and [Layout Button](https://kingtoolbox.github.io/2021/06/28/ui_layout/) to learn more.

**Comment by karagi4** [comment]
It's cool! Thanx! 👍

**Comment by kingToolbox** [comment]
The crash problem has finally been fixed and the stable version 2.1.0 will be released soon, please keep follow and thank you.
