### ISSUE TITLE
Pressing "alt gr" jumps one character back

### ISSUE THREAD

**Issue by morgonjor** [kingToolbox/WindTerm#121]
When I push the Alt Gr key on a Spanish keyboard, the cursor moves one place to the left. The behavior i expect is when i press Alt Gr key, dont happens anything because it is waiting for another key press ( for example: ALT GR + 2 --> i get "at" simbol: @)
WindTerm is a great "connection manager" and i love it. Thanks in advance.

setxkbmap -query
rules:      evdev
model:      pc101
layout:     es

**Comment by kingToolbox** [comment]
Thank you. I will check and fix this problem. If there is any progress, I will update it here.

**Comment by kingToolbox** [comment]
Hello, this issue has been fixed and will be released in the 2.1.0 linux version soon, please  keep follow and thank you.

**Comment by kingToolbox** [comment]
I am happy to tell you that the [WindTerm_2.1.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.1) has been released. You can download and check it now, thank you.

**Comment by kingToolbox** [comment]
The issue has been fixed in [WindTerm_2.1.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.1) and self-test passed. Please reopen this issue if it is still valid. Thank you.
