### ISSUE TITLE
How to cancel the suggestion when I exit windterm.

### ISSUE THREAD

**Issue by yisuixinq** [kingToolbox/WindTerm#122]
How can I cancel the option?

![image](https://user-images.githubusercontent.com/40953718/125167813-fe423400-e1d4-11eb-895d-75917cbac9d2.png)

I edit the config file as below, but it's no use.
<img width="510" alt="Snipaste_2021-07-10_23-24-34" src="https://user-images.githubusercontent.com/40953718/125168098-49107b80-e1d6-11eb-8330-1b47a5009b17.png">
<img width="477" alt="Snipaste_2021-07-10_23-25-20" src="https://user-images.githubusercontent.com/40953718/125168099-4ada3f00-e1d6-11eb-9e1a-b5507f6701b1.png">

**Comment by kingToolbox** [comment]
This feature is added in [WindTerm_2.1.0_Prerelease_6](https://github.com/kingToolbox/WindTerm/releases/tag/2.1-prerelease), so please updat to the latest version, thank you.

**Comment by kingToolbox** [comment]
Hello, this issue will be closed because it should have been resolved. Please reopen this issue if it is still valid. Thank you.
