### ISSUE TITLE
I can't use ctrl+backspace to remove a word

### ISSUE THREAD

**Issue by donnol** [kingToolbox/WindTerm#1222]
I have:

```sh
$ sudo apt upgrade[Cursor is here now]
```

I want to use ctrl+backspace to remove the `upgrade` word, but I can't.

BTW, Windterm is 2.5.0.

**Comment by donnol** [comment]
I use `ctrl`+`w`, it works, so closed.

**Comment by DogeFlow** [comment]
same issue
