### ISSUE TITLE
Can not send Ctrl-@

### ISSUE THREAD

**Issue by wingerted** [kingToolbox/WindTerm#123]
Hi, thank you for such a good job !

I use emacs on linux, and it need "Ctrl-@" to mark string. When I press "Ctrl-@", I only get "2".

I have already delete all keymap in wind.keymaps, but not effect.

Please help

**Comment by kingToolbox** [comment]
Welcome. I will check and fix this issue in the next prerelease, thank you.

**Comment by kingToolbox** [comment]
Hello, [WindTerm_2.1.0_Prerelease_7](https://github.com/kingToolbox/WindTerm/releases/tag/2.1-prerelease) has finally been released and this issue have been fixed. You can download and check it now. Thank you.

**Comment by wingerted** [comment]
Thanks ! That's fixed.

**Comment by kingToolbox** [comment]
Hello, [WindTerm_2.1.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.1) has been released and this issue has been fixed, please download and check it, thank you.
