### ISSUE TITLE
wrong master password

### ISSUE THREAD

**Issue by huai168an** [kingToolbox/WindTerm#127]
After the configuration file is completely moved, the master password is wrong in most cases, and the password is correct occasionally

Prerelease 7

Just now I tested it again. It seems that it didn't appear again. It's strange...
However, just after the configuration file was moved, a large number of master password errors occurred

**Comment by kingToolbox** [comment]
Thank you. I think the new WindTerm_2.1.0 may be good, you can try it. If the master password error still occurs, it is recommended to [change the master password](https://kingtoolbox.github.io/2021/04/23/change-master-password/) once, which should work.

**Comment by huai168an** [comment]
nice

**Comment by kingToolbox** [comment]
Ok, it looks like this issue has been resolved and can be closed. Welcome to continue submitting new issues and feature requests, thank you.
