### ISSUE TITLE
The sound of "Dong Dong"怎么关闭“咚咚”声？

### ISSUE THREAD

**Issue by zhanglindoudou** [kingToolbox/WindTerm#1277]
How to turn off the "Dong Dong" sound？
怎么关闭“咚咚”声？

**Comment by littlecong** [comment]
![图片](https://user-images.githubusercontent.com/1177264/195283729-ba1f7961-cbea-497d-9fa1-23dde1a7aa98.png)

**Comment by zhanglindoudou** [comment]
> ![图片](https://user-images.githubusercontent.com/1177264/195283729-ba1f7961-cbea-497d-9fa1-23dde1a7aa98.png)

Thank you
