### ISSUE TITLE
Cannot change default master password

### ISSUE THREAD

**Issue by DmHertz** [kingToolbox/WindTerm#130]
What is the default master password? 
I cannot change it because there is no info about the default one. 
Is it possible to reset it?

**Comment by kingToolbox** [comment]
Yes, the default master password is **empty**. You can follow the video ["change-master-password"](https://kingtoolbox.github.io/2021/04/23/change-master-password/) to change your master password. Thank you.

**Comment by DmHertz** [comment]
Thank you!

**Comment by kingToolbox** [comment]
Welcome to continue submitting new issues and feature requests. :smile:
