### ISSUE TITLE
cannot use backspace and arrow keys in spark shell

### ISSUE THREAD

**Issue by pjgao** [kingToolbox/WindTerm#131]
![image](https://user-images.githubusercontent.com/22350313/127084423-37386273-c039-4ce5-8066-809e7e0fa71c.png)
backspace and arrow keys in my WSL works ok, but in a remote vitural machine have strange behaviors. 
The variable 'TERM' value in vetural machine is 'xterm'.
WindTerm config as 
![image](https://user-images.githubusercontent.com/22350313/127084661-b06521f9-11da-4ea5-a18a-ff13994b5a39.png)

**Comment by kingToolbox** [comment]
You can try setting the `backspace` key value to see if it can solve the problem. You can refer to [Backspace And Delete Key](https://kingtoolbox.github.io/2020/08/22/keyboard-backspace-delete/) for details. Please remember to reopen the session to take effect after setting. 

As for the arrow keys not working properly, I haven't figured out why. Can you set `Term` to `vt100` or `vt220` and see if it is normal? In addition, if other clients like PuTTY can work normally, please execute the `showkey -a` command in the **Linux shell** in other clients and press the up, down, left, and right keys, and paste the printed results, thank you.
