### ISSUE TITLE
Can open and edit text files directly in the software like VScode?

### ISSUE THREAD

**Issue by Mijiu190** [kingToolbox/WindTerm#1318]
Can open and edit text files directly in the software like VScode? Now I need to select the corresponding open program to open the file. Can some text files be opened and edited directly in the software?

**Comment by xq2248** [comment]
请用英语描述

**Comment by funkpopo** [comment]
WindTerm支持引用本地具备文本编辑的工具直接处理终端内文件，**但是存在编码问题，慎用**。
**配置默认编辑器的方法如下**：
在WindTerm窗口的右上角“_关闭_”按钮下有一个最靠右侧的、位于“_专注模式_”的窗格配置项，将左侧栏设置为开启模式，您即可在默认配置下的左侧栏中看到您连接的终端“_文件管理器_”。
在_“文件管理器_”的“_刷新_”按钮的右侧有一个更多配置项，点击后在快捷键映射默认为“_（S）_”的“_默认编辑器_”设置中，选定您的默认编辑器exe文件路径。
依照您的问题，将该exe文件路径选定为VScode的可执行程序路径即可。**不可使用相对路径**。

**Comment by SheldonKubor** [comment]
It doesn't work on macos
