### ISSUE TITLE
个别ssh连接会出现 ]1337;CurrentDir=/root

### ISSUE THREAD

**Issue by caoye126** [kingToolbox/WindTerm#1328]
个别ssh连接会出现 ]1337;CurrentDir=/some_dir .
请问如何破
![image](https://user-images.githubusercontent.com/26160361/199173794-bd6afc47-25fd-45d3-aeaa-610d7d204d61.png)

**Comment by caoye126** [comment]
今天找到问题原因了,我同事为了vscode使用sftp方便,在~/.bash_profile 重新定义了 PS1 变量. 此变量winterm可能识别不了.
cat ~/.bash_profile
....
export PS1="$PS1\[\e]1337;CurrentDir="'$(pwd)\a\]'
Linux默认的PS1变量为 [\u@\h \W]\$ .
你可以将此配置删除或者重新定义.
我在windterm 每次重置了此变量.
![image](https://user-images.githubusercontent.com/26160361/202069806-920ccaf0-73fe-4887-a83d-af34c2b3210c.png)

**Comment by yk8023** [comment]
在虚拟机上执行   vi ~/.bash_profile
然后注释两行代码
#export PATH
#export PS1="$PS1\[\e]1337;CurrentDir="'$(pwd)\a\]'
这个路径的这个文件是隐藏文件,我是这样解决的
![image](https://user-images.githubusercontent.com/44730744/209366958-3e4d5eed-20fc-465d-897c-2526db1a691c.png)
