### ISSUE TITLE
能否在”历史命令“里支持配置”常用命令“？

### ISSUE THREAD

**Issue by finlaywang** [kingToolbox/WindTerm#1357]
比如我经常输入的命令或者密码，可以预先配置好，要输入的时候双击输入到窗口
Is it possible to save frequently-used commands, with which I could send directly?

**Comment by tinyhare** [comment]
你想要一个“命令管理器”的功能吧，比如SecureCRT这种：
Do you want a ”command manager" , such as SecureCRT?：
![image](https://user-images.githubusercontent.com/6851513/202832135-c457c8a1-442e-4749-a7f1-fddad3721740.png)

现在的“发送”能发送内容，但是不能保存，我也希望给它加个保存功能，一些复杂的命令可以一键输入。
The current "Sender” can send content, but it cannot be saved. I also hope to add a save function to it. Some complex commands can be entered with one click.
![image](https://user-images.githubusercontent.com/6851513/202832243-f143407f-c4b7-46c9-82eb-2eca20fb5d54.png)

**Comment by scopeccsky** [comment]
![image](https://user-images.githubusercontent.com/13957927/202891727-6a02cb8e-420e-4a2b-954a-a37f95063601.png)
可以调出来
![image](https://user-images.githubusercontent.com/13957927/202891759-001a43fc-c9b9-4347-829f-34957d6f544b.png)
快捷栏

**Comment by loda13** [comment]
快速命令可以做这个事情

**Comment by finlaywang** [comment]
> ![image](https://user-images.githubusercontent.com/13957927/202891727-6a02cb8e-420e-4a2b-954a-a37f95063601.png) 可以调出来 ![image](https://user-images.githubusercontent.com/13957927/202891759-001a43fc-c9b9-4347-829f-34957d6f544b.png) 快捷栏

谢谢，可用。Thanks, it works!
