### ISSUE TITLE
支持多开cmd窗口吗？

### ISSUE THREAD

**Issue by chunzhi716** [kingToolbox/WindTerm#1370]
我并没有找到多开选项，请告诉我如何多开cmd窗口，谢谢！

**Comment by li-dianzheng** [comment]
在你的窗口右上角有个加号，选中powershell或者cmd即可多开

**Comment by chunzhi716** [comment]
> 在你的窗口右上角有个加号，选中powershell或者cmd即可多开

看到了，谢谢
