### ISSUE TITLE
ssh连接termux报错连不上

### ISSUE THREAD

**Issue by caidonglin** [kingToolbox/WindTerm#1390]
![20221205015544](https://user-images.githubusercontent.com/52196001/205507244-cc8ba368-73bd-4e87-b418-2ccb45898bd9.png)
ssh连接Android里termux报错，密码/密钥方式都连不上，报以上错误，使用xshell/putty等shell终端没有这样情况。

**Comment by Mnoisec** [comment]
> 

默认会话设置->SSH->验证，将尝试键盘交互认证关掉，其他的开起来就可以了

**Comment by caidonglin** [comment]
谢谢，将尝试键盘交互认证关掉，已解决。
