### ISSUE TITLE
希望加入文件管理器目录可以随命令行切换功能

### ISSUE THREAD

**Issue by hexiegege** [kingToolbox/WindTerm#1399]
比如命令行输入cd /opt/app 文件管理器能自动切换到对应目录，此功能为可选项用户自己勾选是否跟随命令行切换

**Comment by clownfive** [comment]
2.6 windows 版本就有

**Comment by realysy** [comment]
我用的2.6，windows本地能跟随终端变化，但ssh连的远程终端无法跟随
