### ISSUE TITLE
COM session reset setting

### ISSUE THREAD

**Issue by bpan2020** [kingToolbox/WindTerm#14]
1. There are 2 com in my pc, com3 and com4.
I create a serial session with setting to open com4, and save the session. But it will be set to com 3, if i only change some other settings in the session property dialog and save it. I need to set it to com4 by manual even if i only want to change some other settings.
Looks like you dectet the 2 com in the session property dialog, and set com3 as the default one. I think it is ok when creating a new session. But it is better to restore the saving settings when openning the session property.

2. An simular issue is the data format will be set to binary in the session property dialog if I save it after changing some other settings.

**Comment by kingToolbox** [comment]
Sorry for the late reply. This issue has been confirmed and fixed in the new version 1.5, which will be released in a days or two. Thanks for reporting the issue.
