### ISSUE TITLE
How to turn it off  screen locked?

### ISSUE THREAD

**Issue by melin** [kingToolbox/WindTerm#140]
Usually habitually leave the computer lock screen, do not want the windTerm to lock the screen again

**Comment by kingToolbox** [comment]
Please open the config file `WindTerm_install_path/profiles/default.v10/user.config`. Then add `"application.lockScreenTimeout": 0` to it  to disable the lock screen.

The setting dialog is under development and will be released as part of the WindTerm_2.2.0 release. I believe it will be much easier to modify the parameters at that time.

**Comment by YiTester** [comment]
> Please open the config file `WindTerm_install_path/profiles/default.v10/user.config`. Then add `"application.lockScreenTimeout": 0` to it to disable the lock screen.
> 
> The setting dialog is under development and will be released as part of the WindTerm_2.2.0 release. I believe it will be much easier to modify the parameters at that time.

I went to set it as you said, but found it did not take effect. Is there any other setting method?

**Comment by kingToolbox** [comment]
@YiTester 
Sorry for the late reply. I just finished a long trip, and because there is no Internet, I can't deal with the issue in time. 

You may modify `global/wind.config` and set `application.lockScreenTimeout` to 0 or a negative number then restart WindTerm. I think this should also disable the lock screen.

**Comment by kingToolbox** [comment]
Hi, please download and check the new prerelease version [WindTerm_2.2.0_Prerelease_2](https://github.com/kingToolbox/WindTerm/releases/tag/2.2-prerelease), The new prerelease version provides a setting dialog, you can simply configure `Menubar - Session - Preperences - Settings - Security - Lock screen timeout` to turn off this feature. Thank you.
