### ISSUE TITLE
Bug MacOS

### ISSUE THREAD

**Issue by xjink** [kingToolbox/WindTerm#1409]
Hello, I'm faced with problem when I'm typing smth full screen and half screen mode Windterm go mad adn give me black screen. Pls check video to fully understand what happened.

hw:
MacAir M2
MacOS - Ventura 13.0.1 (22A400)

Here a problem:
https://drive.google.com/file/d/1V91nJ98SHs6EOrNzSNwV6s4p-CSUL12m/view?usp=share_link

**Comment by bahirul** [comment]
@xjink you can try disable autocompletion feature, this solve the problem on me.

**Comment by xjink** [comment]
@bahirul I disabled autocompletion and it works, thank you!

**Comment by xjink** [comment]
@bahirul  I disabled autocompletion and it works, thank you!
