### ISSUE TITLE
这个项目估计是停了

### ISSUE THREAD

**Issue by joesdu** [kingToolbox/WindTerm#1414]
这个项目估计是停了,都快半年没更新了.

**Comment by jan-bar** [comment]
要是能完全开源，大家一起维护就好了。这个项目真的很棒。

**Comment by joesdu** [comment]
> 

对,可惜不是全开源.

**Comment by 107295472** [comment]
这个是qt做的吧，维护有难度

**Comment by Kendarou** [comment]
哎，每天都来看...

**Comment by joesdu** [comment]
> 

只要完全开源了.就算是神仙语言做的,GitHub也有大佬能维护[手动滑稽]

**Comment by chenyidong** [comment]
看来又要用回finalshell了？

**Comment by peniridis** [comment]
不太想用finalshell，希望能继续维护，加油！

**Comment by joesdu** [comment]
> 看来又要用回finalshell了？

finalshell是真不行,Java程序启动慢,还经常启动不起来,而且没有隧道功能.不太适合我.若是这个软件长时间无法更新估计得用回XShell(个人版)了.

**Comment by freekkk** [comment]
老外也删库跑路了。可惜了。这么好用的工具

**Comment by TcDhlPro** [comment]
> > 看来又要用回finalshell了？
> 
> finalshell是真不行,Java程序启动慢,还经常启动不起来,而且没有隧道功能.不太适合我.若是这个软件长时间无法更新估计得用回XShell(个人版)了.

我唯一用FinalShell的理由是, 它有个自定义快捷命令

**Comment by mzky** [comment]
作者还在上学吧  2.6很好用啊 [WindTerm 2.6.0 Prerelease 1](https://github.com/kingToolbox/WindTerm/releases/tag/2.6-prerelease)

**Comment by mzky** [comment]
> > > 看来又要用回finalshell了？
> > 
> > 
> > finalshell是真不行,Java程序启动慢,还经常启动不起来,而且没有隧道功能.不太适合我.若是这个软件长时间无法更新估计得用回XShell(个人版)了.
> 
> 我唯一用FinalShell的理由是, 它有个自定义快捷命令 我还提了一下 #1411

有哦~
![image](https://user-images.githubusercontent.com/13345233/209891110-4b52170d-9b51-48e6-937c-6b42cc868ea8.png)

**Comment by wxplovecc** [comment]
用tabby吧还是，带同步，快捷命令等插件，更新及时

**Comment by TcDhlPro** [comment]
> > > > 看来又要用回finalshell了？
> > > 
> > > 
> > > finalshell是真不行,Java程序启动慢,还经常启动不起来,而且没有隧道功能.不太适合我.若是这个软件长时间无法更新估计得用回XShell(个人版)了.
> > 
> > 
> > 我唯一用FinalShell的理由是, 它有个自定义快捷命令 我还提了一下 #1411
> 
> 有哦~ ![image](https://user-images.githubusercontent.com/13345233/209891110-4b52170d-9b51-48e6-937c-6b42cc868ea8.png)

如果上百个快捷命令呢?  目前是没办法整合归类的吧

**Comment by xiaowoonly** [comment]
> 用tabby吧还是，带同步，快捷命令等插件，更新及时

Tabby也不行额，没有快捷命令设置，而且搜狗输入法还输入不了

**Comment by exitNA** [comment]
> 

Tabby性能不行，比较慢。

**Comment by ourcubk** [comment]
> > > > 看来又要用回finalshell了？
> > > 
> > > 
> > > finalshell是真不行,Java程序启动慢,还经常启动不起来,而且没有隧道功能.不太适合我.若是这个软件长时间无法更新估计得用回XShell(个人版)了.
> > 
> > 
> > 我唯一用FinalShell的理由是, 它有个自定义快捷命令 我还提了一下 #1411
> 
> 有哦~ ![image](https://user-images.githubusercontent.com/13345233/209891110-4b52170d-9b51-48e6-937c-6b42cc868ea8.png)

不能调用本地第三方程序，比如直接唤起winscp或者python

**Comment by Nyar233** [comment]
[WindTerm 2.6.0 Prerelease 2](https://github.com/kingToolbox/WindTerm/releases/tag/2.6-prerelease)
Changes in Version 2.6.0 Prerelease 2 (2023-6-7):

**Comment by joesdu** [comment]
> [WindTerm 2.6.0 Prerelease 2](https://github.com/kingToolbox/WindTerm/releases/tag/2.6-prerelease)
> Changes in Version 2.6.0 Prerelease 2 (2023-6-7):

是的，所以我关掉了这个issue
