### ISSUE TITLE
ssh连接后会出现 ]1337;CurrentDir=/root的解决办法

### ISSUE THREAD

**Issue by yk8023** [kingToolbox/WindTerm#1416]
在虚拟机中注释两行代码即可
vi ~/.bash_profile
注释下面两行代码即可
#export PATH
#export PS1="$PS1\[\e]1337;CurrentDir="'$(pwd)\a\]'
![image](https://user-images.githubusercontent.com/44730744/209367245-5614e04d-df49-4450-a306-761add54e080.png)

**Comment by fhyxz001** [comment]
感谢分享，这个方法有效

**Comment by msugry** [comment]
我的~/.bash_profile文件没有这个这个PS1参数，害得我一顿好找。
<img width="973" alt="Snipaste_2024-01-23_16-46-47" src="https://github.com/kingToolbox/WindTerm/assets/44873305/ada9b108-f489-45f2-aae5-8abe7013c09a">
根据代码的执行查找对应的位置，发现/root/.orca_term/orca-bash.sh下面的设置
![image](https://github.com/kingToolbox/WindTerm/assets/44873305/954020eb-97a6-4aa6-8944-886334c10e02)
注释这两行就可以解决对应的问题
注：
preexec() 函数：在每次执行命令之前（preexec）调用。通过 printf 函数发送 ESC（Escape）控制序列和一些信息到终端。
precmd() 函数：在每次命令执行完毕并即将显示提示符之前（precmd）调用。通过 printf 函数发送 ESC 控制序列和一些信息到终端。

**Comment by msugry** [comment]
![image](https://github.com/kingToolbox/WindTerm/assets/44873305/cfd42dc6-6d94-490e-86a9-e14126020b13)
这里是可以根据逻辑来回溯打印的位置的，不同的设置可能出问题的位置不同。
