### ISSUE TITLE
"application.lockScreenTimeout": 0 did not take effect

### ISSUE THREAD

**Issue by YiTester** [kingToolbox/WindTerm#142]
I went to set it as you said, but found it did not take effect. Is there any other setting method?

And I found that using the RZ upload tool over the serial port protocol  will Initialize this setting file

**Comment by YiTester** [comment]
![setting file](https://user-images.githubusercontent.com/66789059/128277040-abe559c9-9e85-4cfd-8058-6c483ea7ca06.png)

**Comment by kingToolbox** [comment]
I think it is because you missed a comma after `"terminal.askBeforeCloseTab": false`, which caused the entire configuration file to become invalid. Please try adding the comma to it to solve the problem. 

``` c++
{
  "modem.lastUploadFolder": "E:/xxx",
  "terminal.askBeforeCloseTab" : false,  //Please note that you need to add a comma at the end of this line
  "application.lockScreenTimeout": 0 
}
```

**Comment by YiTester** [comment]
Thrank you
