### ISSUE TITLE
Is it possible to adjust line-height of terminal?

### ISSUE THREAD

**Issue by chaneyzorn** [kingToolbox/WindTerm#146]
I found that the arrow symbol (powerline) of nerdfonts is relatively small,
and the vertical line of nvim-tree is not continuous.

![image](https://user-images.githubusercontent.com/8176642/128344559-b35cef80-e5b0-44ef-bdd1-d7b3ece46d67.png)

**Comment by chaneyzorn** [comment]
After I change font to Fira, it has been improved, but there are still some gaps.

**Comment by kingToolbox** [comment]
Please open the config file `WindTerm_install_path/profiles/default.v10/user.config`. Then add `"text.lineSpaceFactor": 0.0` to it to adjust the line height. If you are not satisfied, you can try any floating point number between 0.0 and 5.0. The actual line height is equal to the text height multiplied by `1+text.lineSpaceFactor`, So when `text.lineSpaceFactor` is 1.0, the line height is double the text height. The default value is `0.1` to make the text look good. This is why the arrow symbol is relatively small. 

In addition, `"text.charSpaceFactor"` controls the spacing of characters. After each modification, remember to restart to take effect. 

The setting dialog is under development and will be released as part of the WindTerm_2.2.0 release. Please stay tuned, thank you.

**Comment by chaneyzorn** [comment]
Thank you ~
It works, Looks great.

**Comment by kingToolbox** [comment]
Hello, as I mentioned before, the `Settings` dialog will be completed in version 2.2.0. Now the new version [WindTerm_2.2.0_Prerelease_2](https://github.com/kingToolbox/WindTerm/releases/tag/2.2-prerelease) has been completed and released. Please download and check it.

In this version, the extra 10% of the line height has been removed, so you can get the normal text display without gap directly. If you need to adjust the line spacing, you can easily adjust it in the `Menubar - Session - Preperences - Settings - Text - Spacing - Line spacing`. In addition, the fonts can also be specified using `Settings - Default Font`. I hope you can use WindTerm more easily. Thank you.

**Comment by bhaktadas** [comment]
> After I change font to Fira, it has been improved, but there are still some gaps.

With JetBrains font no gaps.
