### ISSUE TITLE
提点建议

### ISSUE THREAD

**Issue by ty913585486** [kingToolbox/WindTerm#1478]
希望开发者可以新增一个复制会话的功能，方便对单一会话进行不同的操作。

**Comment by jackfahdin** [comment]
![2023-02-14_09-43-47](https://user-images.githubusercontent.com/50285470/218616769-199b5c75-86d3-48fd-baac-36d7abc5dd60.png)
你想要的是这个吗？

**Comment by sopcce** [comment]
哈哈，这真是一个尴尬的事情
