### ISSUE TITLE
Not able to connect VPS through private key without password setting. 

### ISSUE THREAD

**Issue by dellca** [kingToolbox/WindTerm#1484]
The VPS connection uses only a private key for authentication, with no need for credentials.
I had tried a couple of the versions including WindTerm_2.6.0 , 2.5.0, etc. all the same. Not able to connect the VPS while Putty works fine. is it something I set it wrong or a bug? 
![Screenshot 2023-02-15 121936](https://user-images.githubusercontent.com/125506698/219147340-1f991c87-fcaa-473d-871a-be063362b3a2.jpg)

**Comment by gonboy** [comment]
key convert to openssh pem format

**Comment by dellca** [comment]
> convert key .ppk to openssh format .pem

It works, thank you!
