### ISSUE TITLE
ssh隧道动态转发问题

### ISSUE THREAD

**Issue by irhuahua** [kingToolbox/WindTerm#1494]
ssh隧道，动态转发，打开后本机telnet 127.0.0.1 7890端口通，然后通过浏览器访问报错
错误信息：Channel opening failure: channel 43 error (1) open failed

**Comment by irhuahua** [comment]
![image](https://user-images.githubusercontent.com/57852602/220223764-bca98792-ef11-4727-a552-e5bb45a9125b.png)

![image](https://user-images.githubusercontent.com/57852602/220223670-3f05db43-708d-4c01-a1d4-63501008255c.png)

**Comment by Stanford2299** [comment]
我也有同样的问题，楼主已经解决了么

**Comment by irhuahua** [comment]
临时在本地电脑,手动开启动态转发
动态转发  本地端口 远端用户名主机
ssh -ND  [$port] [$host]
