### ISSUE TITLE
MacOS zsh issue

### ISSUE THREAD

**Issue by Kvieta1990** [kingToolbox/WindTerm#1499]
Anytime I am launching WindTerm and run my local zsh or anytime I execute a command, I am seeing something like below printed out to the terminal,

```
ESC]697;OSCUnlock=...
```
and a whole bunch of other `ESC]697` escape sequences. Any ideas?

**Comment by Kvieta1990** [comment]
I figured out this is something to do with the installation of the `fig` app for my Mac. Uninstalling `fig` solved the issue.

**Comment by lijiajun325** [comment]
> I figured out this is something to do with the installation of the `fig` app for my Mac. Uninstalling `fig` solved the issue.

please,fig app is Figma?
