### ISSUE TITLE
Log's directory can't be changed

### ISSUE THREAD

**Issue by bpan2020** [kingToolbox/WindTerm#15]
Can we change the root directory of the session log to a directory ouside the installation directory？

**Comment by kingToolbox** [comment]
Thank you, this feature has aslo been done in the upcoming new version 1.5.

**Comment by Elvisass** [comment]
Would it be better if user specify the log path when he wants to start logging? (like Xshell)
Currently log switch is bound with the session, session opens and logging begins. It's too trouble when I need just a part of log (e.g. outputs of current running testing program after some operation with no need to care)

**Comment by kingToolbox** [comment]
Yes, that would be more convenient. I will implement it in v1.7 or v1.8.
Now you can achieve this in two ways.

- Select the output text you wanted and execute the menu "Session/Save Selection As..." to save the selected text to a file.
- Select the commands you wanted in outline pane, then execute the shortcut menu "Copy Output" to copy the corresponding  output text and paste to any application as you like. Multiple items can be selected by pressing Shift key or Ctrl key.

A little bit complicated, but works.

**Comment by kingToolbox** [comment]
@Elvisass 
Manual logging has been released, please download the new prelease version 1.7 and check, thank you.

**Comment by kingToolbox** [comment]
Self-test passed, and this issue will be closed if no further activity occurs during the next week. If the issue is still valid just add a comment to keep it alive. Thank you.
