### ISSUE TITLE
会话标签用户体验优化建议

### ISSUE THREAD

**Issue by zczhendev** [kingToolbox/WindTerm#1542]
会话标签目前是hover状态就会自动切换，建议改为单击切换或者增加设置项
![image](https://user-images.githubusercontent.com/33118060/223311898-8be3b0b6-c55c-4d28-8dc4-f358b492c6b9.png)

**Comment by sishau** [comment]
会话-> 首选项 -> 设置 -> 标签 -> 悬停后激活标签页 选择"绝不"
