### ISSUE TITLE
Wrong tab when paste to vim

### ISSUE THREAD

**Issue by pjgao** [kingToolbox/WindTerm#155]
When pasting many lines to vim, wrong new line tab will occurs as follow, any configurations may I missed?
![image](https://user-images.githubusercontent.com/22350313/129292792-4bc457ad-0379-493f-a06b-1f7248df6411.png)

![image](https://user-images.githubusercontent.com/22350313/129292782-fcd86f32-bf9b-44f0-bd37-7fe4cfd2aa42.png)

**Comment by kingToolbox** [comment]
This is a bit strange, WindTerm will not modify the pasted content, especially will not add or delete characters. I tested the same text and did not have this problem. You can try to check the checkbox `Convert tab to spaces` in the `paste` dialog and then paste it to see if the format is correct.

Another strange thing is that, according to the design, if WindTerm detects that it is in `Vi`, the `paste` dialog box will not show at all when pasting multiple lines of text. So maybe your session is not set `Term` in the `session property` dialog to `xterm` or `xterm-256color` or the server does not support `xterm` term. You can execute `echo $TERM` to check if the server is `Linux`. 

If the problem persists, is the result of pasting the same text to other clients correct?

**Comment by xzhuiz** [comment]
Set :set paste  in vi and try again

**Comment by pjgao** [comment]
Thanks you all a lot!
It turn out to be that the file itself is right infact even through it displays not so good when pasting when I `cat` it after exit the vim.
Still, after adding `set paste` in `~/.vimrc`,  the display is working right too!

**Comment by kingToolbox** [comment]
@xzhuiz Thank you for your help. :smile:
@pjgao I am very happy that the problem has been resolved. But I still recommend to check the `Term` settings (in the `Session Property` Dialog), because according to the design, pasting multiple lines of text in `VI` will not display the paste dialog box, but paste the text directly.

**Comment by pjgao** [comment]
It seems that the `Term` variable and settings are same. ![image](https://user-images.githubusercontent.com/22350313/129723166-ca87075a-f469-4bb7-a319-b037f8dbfdd6.png)

**Comment by kingToolbox** [comment]
@pjgao That would be strange. The `Paste` dialog box does not affect the use, but it is more convenient to paste directly. This is why WindTerm will detect whether it is in `VI` to determine whether to pop the `Paste` dialog box. If I encounter this issue during my own testing, I will fix it. Thank you very much.

**Comment by kingToolbox** [comment]
@pjgao By the way, you can make powerline characters look neater by setting the line height factor, you can refer to [this comment](https://github.com/kingToolbox/WindTerm/issues/146) for details. :smile:
