### ISSUE TITLE
新建会话表单，建议增加【主机名称】字段

### ISSUE THREAD

**Issue by CodesWatching** [kingToolbox/WindTerm#1563]
新建会话界面，建议增加【主机名称】字段，因为连接局域网服务器时，可能是通过内网穿透方式访问了，主机地址都一样，端口来做区分，新增【主机名称】字段，显示时可以将不同主机区分开来

**Comment by dazer007** [comment]
Please use English

**Comment by zsedcbm** [comment]
有个标签字段可以用来填写主机名称

**Comment by littlecong** [comment]
![图片](https://user-images.githubusercontent.com/1177264/229730850-e42c4261-b146-435d-b469-aef044c85de8.png)
