### ISSUE TITLE
Doesn't start if current directory is not the same directory as the app

### ISSUE THREAD

**Issue by JustinGrote** [kingToolbox/WindTerm#16]
I should be able to start the app from anywhere without needing my working directory to be the same folder. If it is not you get this error:

![image](https://user-images.githubusercontent.com/15258962/91592938-2229bd80-e914-11ea-8500-f74aa7be116f.png)

**Comment by kingToolbox** [comment]
Thank you. This issuse has been confirmed and will be fixed in the next version.

**Comment by kingToolbox** [comment]
This issue has been fixed in the new version 1.6, which is expected to be released in mid-September.

Btw, you can also fix it yourself by following the steps below:

1. Create a new file named "qt.conf" in the WindTerm install folder.
2. Open "qt.conf" and input and save:
```
[Paths]
Plugins = plugins
```

**Comment by JustinGrote** [comment]
Thank you for the fast resolution!

**Comment by kingToolbox** [comment]
It's my pleasure.

**Comment by kingToolbox** [comment]
The new version 1.6 has been released, please download and check, thank you.
