### ISSUE TITLE
'ESC[?4m' is displayed when vim opens the file

### ISSUE THREAD

**Issue by MidCheck** [kingToolbox/WindTerm#1623]
WindTerm: WindTerm_2.5.0_Windows_Portable_x86_64
Vim:  9.0.1420
SSH： OpenSSH_9.3p1, OpenSSL 3.0.8 7 Feb 2023
Linux: ManjaroLinux 22.1.0

After connecting to the remote Linux SSH, use vim to edit the file and save it. When the file is reopened, this special character 'ESC[?4m' will be displayed at the last position of the cursor.
![image](https://user-images.githubusercontent.com/45385025/232655685-6d71a608-fa56-44e4-87a8-3d5edac6fb9b.png)
![image](https://user-images.githubusercontent.com/45385025/232655720-9a8df864-1594-4cc9-bda6-8d06f80ade8f.png)

edit text.txt:
![image](https://user-images.githubusercontent.com/45385025/232655998-269ece63-1802-4523-b582-6a2918cfc0b1.png)

reopen:
![image](https://user-images.githubusercontent.com/45385025/232656105-10f1a063-21ef-4e00-b274-36f2ae2d5f76.png)

This character will be deleted along with the deletion of this line of characters.

**Comment by leehow1988** [comment]
原因是 `~/.bash_profile` 文件多了一些内容

```
# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/.local/bin:$HOME/bin

export PATH
export PS1="$PS1\[\e]1337;CurrentDir="'$(pwd)\a\]'

```

是多了最后一行导致了每个命令结束都会打印额外的信息。

修改 `~/.bash_profile` 文件为

```sh
# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/.local/bin:$HOME/bin

export PATH
```

https://github.com/kingToolbox/WindTerm/issues/1018

**Comment by MidCheck** [comment]
I found a solution to this problem on stackoverflow: [i-compile-vim9-by-my-self-but-esc4m-keeps-showing-up-whyhow-to-fix-this](https://stackoverflow.com/questions/75318113/i-compile-vim9-by-my-self-but-esc4m-keeps-showing-up-whyhow-to-fix-this)

More information: [Vim issues 11728](https://github.com/vim/vim/issues/11728)

Write these into .vimrc:
```
set keyprotocol=
let &term=&term
```

**Comment by MidCheck** [comment]
> 原因是 `~/.bash_profile` 文件多了一些内容
> 
> ```
> # .bash_profile
> 
> # Get the aliases and functions
> if [ -f ~/.bashrc ]; then
>         . ~/.bashrc
> fi
> 
> # User specific environment and startup programs
> 
> PATH=$PATH:$HOME/.local/bin:$HOME/bin
> 
> export PATH
> export PS1="$PS1\[\e]1337;CurrentDir="'$(pwd)\a\]'
> ```
> 
> 是多了最后一行导致了每个命令结束都会打印额外的信息。
> 
> 修改 `~/.bash_profile` 文件为
> 
> ```shell
> # .bash_profile
> 
> # Get the aliases and functions
> if [ -f ~/.bashrc ]; then
>         . ~/.bashrc
> fi
> 
> # User specific environment and startup programs
> 
> PATH=$PATH:$HOME/.local/bin:$HOME/bin
> 
> export PATH
> ```
> 
> #1018

I don't have this in my bash configuration file, and I just found out it's vim.

**Comment by MidCheck** [comment]
I found a solution to this problem on stackoverflow: [i-compile-vim9-by-my-self-but-esc4m-keeps-showing-up-whyhow-to-fix-this](https://stackoverflow.com/questions/75318113/i-compile-vim9-by-my-self-but-esc4m-keeps-showing-up-whyhow-to-fix-this)

More information: [Vim issues 11728](https://github.com/vim/vim/issues/11728)

Write these into .vimrc:
```
set keyprotocol=
let &term=&term
```

**Comment by kingToolbox** [comment]
The `ESC [?4m` control sequence (XTQMODKEYS , Query key modifier options) was introduced in `vim 9.0`. [WindTerm 2.7.0 Prerelease 2](https://github.com/kingToolbox/WindTerm/releases/tag/2.7-prerelease-2) now supports parsing `ESC [?4m`. Please download and try it. Thank you.
