### ISSUE TITLE
screen 会话中未自动调整windows 大小

### ISSUE THREAD

**Issue by atmgnd** [kingToolbox/WindTerm#1640]
复现步骤:
1. ssh登陆任一linux, 调查window大小, 以使window列数在140左右
2. 运行``screen -S test``命令, 新建一screen 会话
3. 按键``Ctrl + A, c``新建一子终端
4. 按键``Ctrl + A, Shift + '``, 进入子终端列表, 可以看到显示布局是错误的, 其他ssh 客户端没有此问题

如图, screen 会话中的列为80, 没有自动调整为实际的149
![2023-04-25_14-55-55 mp4_snapshot_00 16_ 2023 04 25_15 10 42](https://user-images.githubusercontent.com/12344491/234201400-4c7dfb40-08af-452e-9190-7e477d642c57.jpg)

**Comment by atmgnd** [comment]
https://user-images.githubusercontent.com/12344491/234201678-876fd0fd-40c0-47b2-b9ae-56ca82563203.mp4

**Comment by atmgnd** [comment]
放弃, 转投mobaxterm 了

**Comment by psgh01** [comment]
https://blog.csdn.net/dreamer2020/article/details/101858976
改screen配置貌似可以解决
