### ISSUE TITLE
希望可以简化鼠标右键的功能

### ISSUE THREAD

**Issue by jaychoubaby** [kingToolbox/WindTerm#1692]
使用过很多的ssh工具，已经非常习惯了鼠标选中则复制，鼠标右键则粘贴，希望能够支持一下，目前的鼠标右键功能太杂了，需要点选很多次，很麻烦

**Comment by jackfahdin** [comment]
设置的终端和文本两个选项中可以设置右键粘贴与选中复制功能

**Comment by jaychoubaby** [comment]
> 设置的终端和文本两个选项中可以设置右键粘贴与选中复制功能

设置好了 非常感谢
