### ISSUE TITLE
Reconnect session shortcut not work?

### ISSUE THREAD

**Issue by fuhuo** [kingToolbox/WindTerm#17]
When i try to use shortcut Return to reconnect a session that closed，it cannot work.
![image](https://user-images.githubusercontent.com/6127614/93960137-d8ee5180-fd8b-11ea-9793-680c5d45bf20.png)

**Comment by kingToolbox** [comment]
Sorry for the late reply. This issue has been confirmed and fixed in the new version 1.7, which will be released in early October. Thanks for reporting the issue.

**Comment by fuhuo** [comment]
Thank you very much

**Comment by kingToolbox** [comment]
The fix has been released, please download the new prelease version 1.7 and check, thank you.

**Comment by fuhuo** [comment]
i check it everything ok in my usage scenarios of version 1.71.thanks you!
