### ISSUE TITLE
Agent Authentication failed, please try another method.

### ISSUE THREAD

**Issue by rainsun007** [kingToolbox/WindTerm#170]
Agent Authentication failed, please try another method.

Always need a password

**Comment by kingToolbox** [comment]
When the `Session property dialog - SSH - Authentication - Attemp pageant authentication` option is turned on (it is turned on by default), WindTerm will detect whether `pageant.exe` is started when logging in, and  `Agent Authentication failed, please try another method.` will be displayed if it is not detected. If you do not use `pageant authentication`, then this message does not affect your login and you can ignore it. 

If you need to log in with your password automatically, please check `Auto login next time` in the login wizard. If you want to use `pageant authentication`, please make sure that `pageant.exe` has been started and the correct private-key file has been loaded.

**Comment by kingToolbox** [comment]
When the `Session property dialog - SSH - Authentication - Attemp pageant authentication` option is turned on (it is turned on by default), WindTerm will detect whether `pageant.exe` is started when logging in, and  `Agent Authentication failed, please try another method.` will be displayed if it is not detected. If you do not use `pageant authentication`, then this message does not affect your login and you can ignore it. 

If you need to log in with your password automatically, please check `Auto login next time` in the login wizard. If you want to use `pageant authentication`, please make sure that `pageant.exe` has been started and the correct private-key file has been loaded.

**Comment by rainsun007** [comment]
Auto login next time  checked 
restart WindTerm
need a password

**Comment by kingToolbox** [comment]
Sorry, I am a little confused. Do you want to use `password authentication` to log in automatically or use `agent authentication` to log in automatically? I tested both several times with `WindTerm_2.1.0_Windows` just now, and I didn't encounter any problems. 

BTW: Would you like to tell me what version of WindTerm (Main menu - Help) and operating system are you using? Thank you. And if you are willing, please rename the `WindTerm_install_path/profiles` folder to `WindTerm_install_path/profiles_bak`, then start WindTerm and create a new session to test it, and see if it works? After the test is complete, delete the newly created `profiles` folder, and then rename `profiles_bak` back to `profiles`, you can restore all existing configurations.

**Comment by rainsun007** [comment]
OS:  Windows 10 home  20H2    19042.1165
WindTerm:  2.1.0

I tried it the way you said
The issue is not resolved

**Comment by kingToolbox** [comment]
Sorry for the late reply. I just finished a long trip, and because there is no Internet, I can't deal with the issue in time. 

Please download [WindTerm_2.2.0_Prerelease_1](https://github.com/kingToolbox/WindTerm/releases/tag/2.2-prerelease) and try it, because the new version has changed a lot and this issue may have been fixed. If you still have problems, please let me know. Thank you.

**Comment by rainsun007** [comment]
unsolved problem
show  dialog  "please input master password"
