### ISSUE TITLE
How to restore this font with a hyphen to normal?

### ISSUE THREAD

**Issue by cfikt** [kingToolbox/WindTerm#1702]
如何将这种带-的字体恢复成正常，但是保留其颜色
![image](https://github.com/kingToolbox/WindTerm/assets/109979597/9f7a99ee-fcb3-463a-9b78-255668b8aeb1)

**Comment by kingToolbox** [comment]
Open the `WindTerm_installed_path/global/themes/dige-black/scheme.theme` file and then just modify
```json
{
	"name": "Function argument",
	"scope": "variable.parameter",
	"style": {
		"fontStyle": "italic",
		"foreground": "#FD971F"
	}
},
```
 to:
```json
{
	"name": "Function argument",
	"scope": "variable.parameter",
	"style": {
		"foreground": "#FD971F"
	}
},
```

I also think that this italic font is not really necessary. It will be changed to a regular font in the next version. Please stay tuned, thank you.

**Comment by cfikt** [comment]
好的谢谢，已经解决了
