### ISSUE TITLE
What does the underscore mean?

### ISSUE THREAD

**Issue by leon-k24** [kingToolbox/WindTerm#1706]
<img width="889" alt="1" src="https://github.com/kingToolbox/WindTerm/assets/136284896/cc766b12-8e54-4050-8d08-3ed300839e6c">
下划线是什么意思？什么情况下文件会有下划线呢？
大佬？

**Comment by zml910724** [comment]
https://kingtoolbox.github.io/2023/06/06/trigger_built-in_unarchiver/

**Comment by leon-k24** [comment]
> https://kingtoolbox.github.io/2023/06/06/trigger_built-in_unarchiver/

牛逼~

**Comment by kingToolbox** [comment]
Thanks to @zml910724. The underscore is used to indicate compressed files, and by pressing `Ctrl` and clicking, you can quickly enter the decompression command. In fact, you can also customize your own triggers based on the [Trigger](https://kingtoolbox.github.io/tags/trigger/) instructions.
