### ISSUE TITLE
I want the macos arm version

### ISSUE THREAD

**Issue by izhangguapi** [kingToolbox/WindTerm#1711]
I use the macbook m2, but only the x64, and I want the arm version

**Comment by kingToolbox** [comment]
As `WindTerm 3.1.0` will switch to Qt version 6.0 for development, the original plan to create an ARM version using `Qt 5.15.9` has been canceled. Please be patient and wait for a while, as the ARM version will be provided in the second half of the year and is expected to be available around October.

**Comment by izhangguapi** [comment]
Ok, I see. Thank you very much
