### ISSUE TITLE
the program crashed

### ISSUE THREAD

**Issue by iA10N3** [kingToolbox/WindTerm#1713]
When I type` . /configure --prefix=/`, the program crashes, and my system is windows 10.

**Comment by kingToolbox** [comment]
May I ask which version are you using? If it's not the latest version, please update to the latest version [WindTerm 2.6.0 Prerelease 2](https://github.com/kingToolbox/WindTerm/releases/tag/2.6-prerelease), which is more stable. If you are already using the latest version, I will investigate this issue.
