### ISSUE TITLE
连接 SSH 版本为 ssh-2.0-OpenSSH_7.4 时，客户端失败

### ISSUE THREAD

**Issue by BytesPirate** [kingToolbox/WindTerm#1738]
当连接 ssh-2.0-OpenSSH_7.4 版本，连接失败，错误内容如下：
![image](https://github.com/kingToolbox/WindTerm/assets/74055444/85968492-a460-4ce3-afd1-454b73dccbfb)

**Comment by yoursh** [comment]
我也遇到这个问题了，不过服务器的sshd版本是OpenSSH_9.1p1

**Comment by exyb** [comment]
我也遇到了这个问题, 会话日志中看到读取用户名读取为 none 或者 unknown 导致的失败 (ssh_packet_userauth_failure: Access denied for 'unknown'.)
在验证中取消"使用键盘交互", 可以正常进行密码输入和验证
![image](https://github.com/kingToolbox/WindTerm/assets/6635577/6e6e490a-84bc-4a56-9008-3d0d3135a9e0)

**Comment by kingToolbox** [comment]
Thank you very much for your detailed bug report. Please download and try the latest [WindTerm_2.6.0_Prerelease_8](https://github.com/kingToolbox/WindTerm/releases/tag/2.6-prerelease), which fixes some connection issues. If there are still problems, please let me know.
