### ISSUE TITLE
Use Enter to reconnect the session, the entire application crashes

### ISSUE THREAD

**Issue by xzhuiz** [kingToolbox/WindTerm#18]
Use the latest version 1.7, 100% appeared
For example: after successful login, exit, then press enter

**Comment by kingToolbox** [comment]
Thank you very much, this is my mistake.
Since this is a very serious fault, I have fixed and released a new version 1.71, please download and check. Thanks again.

**Comment by xzhuiz** [comment]
Thank you very much, the repair is so fast

**Comment by kingToolbox** [comment]
Anytime, this is my duty. This issue will be closed and welcome to continue submitting new issues and feature requests.
