### ISSUE TITLE
When using vim/vi,  `ESC[?4m` will be automatically added to the screen

### ISSUE THREAD

**Issue by amaoo** [kingToolbox/WindTerm#1814]
When using vim/vi,' ESC[?4m' will be automatically added to the screen, and it will disappear automatically when saving or exiting.

<img width="333" alt="image" src="https://github.com/kingToolbox/WindTerm/assets/48399388/680e3012-7877-471a-b4a3-a00c74627852">
<img width="402" alt="image" src="https://github.com/kingToolbox/WindTerm/assets/48399388/f2741646-a6ec-4382-b82f-b07d6b2feb7a">

**Comment by amaoo** [comment]
https://github.com/kingToolbox/WindTerm/issues/1623
Has been solved.

**Comment by jeffcao** [comment]
hello,  i have the same issure.
how to fix this?  thanks.

**Comment by amaoo** [comment]
@jeffcao 
Write these into .vimrc:

```
set keyprotocol=
let &term=&term
```

**Comment by jeffcao** [comment]
> @jeffcao Write these into .vimrc:
> 
> ```
> set keyprotocol=
> let &term=&term
> ```

I did. but when i run cmd 'vi aa.txt' , below error msg show:

```
Error detected while processing /usr/share/vim/vimrc[53]../etc/vim/vimrc.local:
line    1:
E518: Unknown option: keyprotocol=
Press ENTER or type command to continue

```

**Comment by amaoo** [comment]
@jeffcao 

`vi ~/.vimrc`
It doesn't matter if `.vimrc` doesn't exist.

**Comment by amaoo** [comment]
@jeffcao 

Use this.

```
echo 'set keyprotocol=' >> ~/.vimrc
echo 'let &term=&term' >> ~/.vimrc
```

**Comment by jeffcao** [comment]
![image](https://github.com/kingToolbox/WindTerm/assets/3163213/d5901310-9b00-4b53-958b-8a13e2db9899)
@amaoo  Thank your replay, but still does't work. see above pic.

**Comment by amaoo** [comment]
@jeffcao 
This is what I refer to.
https://github.com/kingToolbox/WindTerm/issues/1623#issuecomment-1654928805

I tried again, and there was no such problem. What's your version of vim?

**Comment by jeffcao** [comment]
> @jeffcao This is what I refer to. [#1623 (comment)](https://github.com/kingToolbox/WindTerm/issues/1623#issuecomment-1654928805)
> 
> I tried again, and there was no such problem. What's your version of vim?

yes, i have noticed that it's my vim version caused the problem.  my vim version is 8.2.2121.

**Comment by amaoo** [comment]
Then can you try vim9?

**Comment by jeffcao** [comment]
> Then can you try vim9?

yes, i have installed vim 9.1.16 from github source. but, the "unkonwn option: keyprotocol=" error still is there.

**Comment by kingToolbox** [comment]
Duplicate of #1623

The `ESC [?4m` control sequence (XTQMODKEYS , Query key modifier options) was introduced in `vim 9.0`. [WindTerm 2.7.0 Prerelease 2](https://github.com/kingToolbox/WindTerm/releases/tag/2.7-prerelease-2) now supports parsing `ESC [?4m`. Please download and try it. Thank you.
