### ISSUE TITLE
连接某些服务器时,输入密码报Unkown error

### ISSUE THREAD

**Issue by javaSunson** [kingToolbox/WindTerm#1922]
其他ssh客户端都能链接，请问应用日志在哪可以看

**Comment by gachoyi** [comment]
![image](https://github.com/kingToolbox/WindTerm/assets/8298971/08a83575-4583-4287-9e06-06704c16ec31)
勾掉这个

**Comment by javaSunson** [comment]
非常感谢，您解决了我的问题
