### ISSUE TITLE
愚人节玩笑成真了？

### ISSUE THREAD

**Issue by asundust** [kingToolbox/WindTerm#1926]
愚人节玩笑之后就发了一个预览版，此后再无发版消息了，就怕成真了，挺好的一个项目。

**Comment by jackfahdin** [comment]
@kingToolbox 偶尔出来冒个泡呗，让我们有点期待

**Comment by Huaweidev** [comment]
为什么没有更新了？

**Comment by michaelsara** [comment]
> 为什么没有更新了？

Because of the impact of the epidemic on income, there is not enough energy to continue development

**Comment by asundust** [comment]
希望软件能继续发展下去，并开通捐助渠道。
