### ISSUE TITLE
2.6.0 prerelease3 "Paste" not work.

### ISSUE THREAD

**Issue by h31105** [kingToolbox/WindTerm#1946]
I'm glad to see a new version available, but I've encountered a bug. In Windterm 2.6 pre3, the paste function doesn't work properly, and I'm unable to paste any content into Windterm.

**Comment by zml910724** [comment]
I also encountered the same problem. Using the mouse wheel can paste normally, but using shift+ins key cannot work

**Comment by kingToolbox** [comment]
This is my negligence. While fixing the bug:

>  [SESSION] When multiple lines of text are selected, the Paste Selected Text operation failed to pass the text to the Paste dialog, but instead sent it directly to the server.

I accidentally overwrote the same-named function in the base class and failed to thoroughly test it myself.

As this would make the `WindTerm_2.6.0_Prerelease_3` version almost unusable, The new version [WindTerm_2.6.0_Prerelease_4](https://github.com/kingToolbox/WindTerm/releases/tag/2.6-prerelease) has been released. Please download and try it out. Sorry for the trouble caused.
