### ISSUE TITLE
2.5.0几个小问题反馈，希望新版本能够解决

### ISSUE THREAD

**Issue by WengerChan** [kingToolbox/WindTerm#1953]
1.  复制会话时把原会话保存的密码一起复制：在以前版本（记不清是2.1还是多少了）是支持的，2.5中移除了
2. 会话的密码发生改变时，能够自动保存新输入的密码，而不是要去会话设置中清除“已保存自动认证”才能保存新的。

**Comment by kingToolbox** [comment]
Yes, this feature was supported in the past, but it was removed after receiving feedback from users who reported that after duplicating sessions, they often wished to log in with a different username, and duplicating the previous login information caused interference. Therefore, it was cancelled, and I also feel that cancelling is more reasonable, so there is no consideration of restoring it at this time. Please understand.

Regarding your second suggestion, in the new [WindTerm_2.6.0_Prerelease_5](https://github.com/kingToolbox/WindTerm/releases/tag/2.6-prerelease) version , once you log in successfully with a new password, it will be automatically saved without the need to clear the existing logged-in information first. You can give it a try.

Additionally, I recommend that you use the [OneKey](https://kingtoolbox.github.io/tags/onekey/) feature, which allows you to log in with just one click without having to re-enter your username, password, or other information, even if you've duplicated the session. It's very convenient.

**Comment by WengerChan** [comment]
Thank you for your reply, I hope this project can get better and better, and a new stable version can be released as soon as possible.
