### ISSUE TITLE
How to move my ssh Files

### ISSUE THREAD

**Issue by waittingsummer** [kingToolbox/WindTerm#1958]
![image](https://github.com/kingToolbox/WindTerm/assets/32017265/79fa86e1-8cb8-425e-93cf-3bcd63aa58ca)
As shown in the figure, I copied .wind from the P2 directory to P4, but when I ran the program under P4, only part of it was recognized
如图，我从P2目录把.wind复制导P4，但是运行P4下的程序，只识别了一部分

Now I have to run the program in the P4 directory, but the session directory is specified to P2, which is not the way to go
现在我不得不把程序运行在P4目录下，但是会话目录指定到P2，这样终究不是办法

**Comment by Kendarou** [comment]
在你的配置文件目录中的 `.wind\profiles\default.v10\terminal\user.sessions` 是你保存的会话列表。该目录下其它几个文件分别对应相应的配置项。

**Comment by kingToolbox** [comment]
What do you mean by only recognizing part of the configurations? Which configurations have not been recognized?

**Comment by waittingsummer** [comment]
> What do you mean by only recognizing part of the configurations? Which configurations have not been recognized?

I think I have found the reason, first set the ".wind" directory in the P4 program to its current directory, and then replace the ".wind" in P2
