### ISSUE TITLE
Lock Screen 能否关闭或者自定义生效时间

### ISSUE THREAD

**Issue by gofftang** [kingToolbox/WindTerm#196]
最近用WindTerm串口做长时间测试，要保存测试打印数据，但由于Lock Screen生效（大概30分钟后）导致打印数据不被记录，希望可以设置Lock Screen关闭或者自定义生效时间。

**Comment by helloxz** [comment]
出于安全性考虑WindTerm默认30分钟后自动锁屏，并要求用户输入密码，如果您不希望自动锁屏，可以修改global\wind.config将application.lockScreenTimeout设置为0或负数即可(需要重启客户端)。参考：[https://www.xiaoz.me/archives/16314](https://www.xiaoz.me/archives/16314)

**Comment by yang-kai-shuo** [comment]
怎么好久都没有更新了呢

**Comment by helloxz** [comment]
> 怎么好久都没有更新了呢

不知道啊，可能作者有事吧。

**Comment by kingToolbox** [comment]
Duplicat of #140 #179

Sorry for the late reply. I just finished a long trip, and because there is no Internet, I can't deal with the issue in time. 

Please open the config file WindTerm_install_path/profiles/default.v10/user.config. Then add `"application.lockScreenTimeout": 0` to it to disable the lock screen. Thank you.

**Comment by kingToolbox** [comment]
I have completed the development of the `Settings` dialog box. Now you can easily disable the `Lock Screen` feature by the setting `Menubar - Session - Preperences - Settings - Security - Lock screen timeout`. So please download and check the new [WindTerm_2.2.0_Prerelease_2](https://github.com/kingToolbox/WindTerm/releases/tag/2.2-prerelease), thank you.

**Comment by kingToolbox** [comment]
I have completed the development of the `Settings` dialog box. Now you can easily disable the `Lock Screen` feature by the setting `Menubar - Session - Preperences - Settings - Security - Lock screen timeout`. So please download and check the new [WindTerm_2.2.0_Prerelease_2](https://github.com/kingToolbox/WindTerm/releases/tag/2.2-prerelease), thank you.

**Comment by kingToolbox** [comment]
This issue has been solved and will be closed. Welcome to continue submitting new feature requests and bugs, thank you.
