### ISSUE TITLE
2.6.0 Pre4版本TAB页切换快捷键问题

### ISSUE THREAD

**Issue by SimonsSoft** [kingToolbox/WindTerm#1962]
1. 之前版本是 “ALT+数字键” 来切换TAB1 到 TAB5页 ；
2. 当前2.6.0 pre4 变为 “CTRL+数字键” ；
导致使用起来很不习惯，建议能否：
1. 变更为 “ALT+数字键” 来切换TAB页，不限制1-5；
2. 可自定义快捷键；

感谢！

**Comment by SimonsSoft** [comment]
验证可以，非常感谢您的回复！

**Comment by kingToolbox** [comment]
The shortcut keys `Alt+1` and others have been restored in version `2.6.0 Prerelease 5`. Please download and use [WindTerm_2.6.0_Prerelease_5](https://github.com/kingToolbox/WindTerm/releases/tag/2.6-prerelease). Thank you.

**Comment by SimonsSoft** [comment]
> The shortcut keys `Alt+1` and others have been restored in version `2.6.0 Prerelease 5`. Please download and use [WindTerm_2.6.0_Prerelease_5](https://github.com/kingToolbox/WindTerm/releases/tag/2.6-prerelease). Thank you.

大神你好~~好的~
