### ISSUE TITLE
pre 4 用 alt+数字键 快速切换tab页的功能失效了

### ISSUE THREAD

**Issue by Ro0tk1t** [kingToolbox/WindTerm#1964]
pre 4 用 alt+数字键 快速切换tab页的功能失效了

**Comment by lunalean** [comment]
使用ctrl+数字键就可以了

**Comment by Ro0tk1t** [comment]
索达寺内

**Comment by kingToolbox** [comment]
The shortcut keys `Alt+1` and others have been restored in version `2.6.0 Prerelease 5`. Please download and use [WindTerm_2.6.0_Prerelease_5](https://github.com/kingToolbox/WindTerm/releases/tag/2.6-prerelease). Thank you.
