### ISSUE TITLE
Whether the string can be automatically copied after the mouse selects it? 鼠标选中字符串之后 能否自动复制? 

### ISSUE THREAD

**Issue by Xiyun2022** [kingToolbox/WindTerm#1968]
It is highly recommended to copy the string automatically after the mouse selects it without right-clicking it.
强烈建议 鼠标选中字符串之后就自动复制 不用右键选择复制

mobaxterm simply copies the string after it is selected.
mobaxterm就是选中字符串之后 就直接复制字符串

@kingToolbox

**Comment by so1exa** [comment]
https://github.com/kingToolbox/WindTerm/issues/58
support copy on select and right click paste

**Comment by Xiyun2022** [comment]
Thank you very much for your reply


But what I mean is that the mouse selects the string and then you can copy the selected string to the clipboard without having to right-click and select copy







At 2023-11-26 11:39:45, "so1exa" ***@***.***> wrote:

#58
support copy on select and right click paste

**Comment by Jonson-zhang** [comment]
you can do as blow pic
![image](https://github.com/kingToolbox/WindTerm/assets/36395108/55868d11-6c06-4127-bb64-07c7128727d1)

**Comment by Xiyun2022** [comment]
@Jonson-zhang  get it,  thks
