### ISSUE TITLE
Crash when typing new folder name.

### ISSUE THREAD

**Issue by replydev** [kingToolbox/WindTerm#20]
if I try to write with the keyboard the name of a new folder, pressing new folder in the integrated sftp client, wind term crasha after about 1 second.

How to reproduce the bug:

- Connect to a server with ssh
- Open the new dialog directory using sftp client.
- Type anything

**Comment by kingToolbox** [comment]
Thank you very much, This issue has been confirmed.
Since this is a very serious fault, I have fixed and released a new version 1.72, please download and check. Thanks again.

**Comment by replydev** [comment]
Now all works flawlessy. Thanks for your work, please consider to release all the source code.
