### ISSUE TITLE
screenlock passwd

### ISSUE THREAD

**Issue by laoola** [kingToolbox/WindTerm#2000]
The extracted file has not undergone any configuration modifications. By default, the screen will lock after a certain period of time, but without setting a lock password, it cannot be unlocked and can only be closed and restarted。
Linux 2.5.0版本
![image](https://github.com/kingToolbox/WindTerm/assets/42239744/b0d8d9fc-f143-4f45-a8d8-058930d78a48)

**Comment by Kendarou** [comment]
Just press `Enter`
