### ISSUE TITLE
如何还原菜单栏

### ISSUE THREAD

**Issue by LunkLing** [kingToolbox/WindTerm#2019]
我把上面的菜单栏干掉了，如何还原？
![image](https://github.com/kingToolbox/WindTerm/assets/94232199/56e8d126-b079-44b3-93f4-afe549bab98a)

**Comment by Remember-the-past** [comment]
离谱 复现了一下  结果我也回不去了

**Comment by LunkLing** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Remember-the-past** [comment]
> 我把上面的菜单栏干掉了，如何还原？ ![image](https://private-user-images.githubusercontent.com/94232199/290745922-56e8d126-b079-44b3-93f4-afe549bab98a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2OTU4NDgsIm5iZiI6MTcwMjY5NTU0OCwicGF0aCI6Ii85NDIzMjE5OS8yOTA3NDU5MjItNTZlOGQxMjYtYjA3OS00NGIzLTkzZjQtYWZlNTQ5YmFiOThhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDAyNTkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1NTQ1M2E2YjcyYWVkMzJmZGJhN2I1YTUxYmI5MzJkMDExYjM0NDE4ZDQ4MzU4ZWViMDUyMjllZDFiYzdhNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SZ_nv5yKPdn9sXXBdd48ML31BQ3xufwo_1n9K6C9M3Y)

I opened it again and tried a new one. You need to type the following characters alt+w, alt+M

**Comment by LunkLing** [comment]
Done。非常感谢你的回答，根据操作，我已恢复菜单栏
