### ISSUE TITLE
Broken layout when running tmux session selector

### ISSUE THREAD

**Issue by char101** [kingToolbox/WindTerm#202]
How to reproduce:

1. run tmux, create two or more sessions
2. type <C-b>s
3. move between sessions by using arrow up/down

Expected output:

1. arrow up/down moves selection between session while the lower pane gives overview of the session windows

Actual output:

The terminal layout is broken.

**Comment by kingToolbox** [comment]
Sorry for the late reply. I just finished a long trip, and because there is no Internet, I can't deal with the issue in time. 

I tried following your steps and everything is OK. Is it convenient for you to take a screenshot to see what the broken layout looks like? Thank you.

**Comment by char101** [comment]
Thanks for the response.

Here are the comparison screenshots for the following sequence of commands

```
$ tmux
in tmux:
<C-b>:new-session -s test
<C-b>:new-session -s test2
<C-b>s
```

I have changed the Color Theme font to `M+ 1m`.

How it should look like
![right](https://user-images.githubusercontent.com/71255/134909924-62cd0e45-b587-48e7-8159-5229ba037026.png)

How it look in windterm
![windterm](https://user-images.githubusercontent.com/71255/134909956-f3915813-866d-446f-9d6a-24bfba8b38af.png)

**Comment by char101** [comment]
So I changed the color scheme to another color scheme which uses the original font, and the result is correct. So I guess this is caused by the (mis?)calculation of the font width?

**Comment by char101** [comment]
This is the link to the font https://mplusfonts.github.io/ . The font is definitely fixed width, so maybe the font width calculation can be made more robust?

**Comment by kingToolbox** [comment]
Thank you for the detailed description. I have reproduced this issue, although mine screen does not look as bad as in your screenshot. I will try to fix this problem in the next prerelease version. Please stay tuned, thank you.

**Comment by kingToolbox** [comment]
This issue has been solved and will be closed. Welcome to continue submitting new feature requests and bugs, thank you.
