### ISSUE TITLE
Cannot connect to server using ipv6

### ISSUE THREAD

**Issue by blueboyggh** [kingToolbox/WindTerm#2028]
Cannot connect to server using ipv6

**Comment by blueboyggh** [comment]
i'm using 2.6.0 Prerelease 5

**Comment by DreamFirstSnow** [comment]
I think this is a bug. I encountered the same problem, but after switching to version 2.5.0, I successfully connected to the IPv6 server.

**Comment by wukakal** [comment]
I encountered the same problem. 
I have an asusrouter and registered a DDNS. The domain xxx.asuscomm.com resolves to an IPv6 address.
I can use SSH to connect to xxx.asuscomm.com using 2.50, but using 2.60pre5 or 2.60pre8 will fail and I will receive an error message saying "connection timed out."
I had intended to provide more detailed logs, but unfortunately, the logs related to the session in the ". wind \ profiles \ default.v10 \ terminal \ logs \ Session Name" directory did not record any information.

![image](https://github.com/kingToolbox/WindTerm/assets/29480086/8c4b3bf0-22f5-434b-98c1-099d22caa36c)

![image](https://github.com/kingToolbox/WindTerm/assets/29480086/0b7f219c-412a-4a81-9315-ca62876e1132)

![image](https://github.com/kingToolbox/WindTerm/assets/29480086/088fbd49-4004-4bb9-9b12-27963571f426)
![image](https://github.com/kingToolbox/WindTerm/assets/29480086/b0fc4694-42fc-404c-b3e4-789311dbb589)

**Comment by kingToolbox** [comment]
Thank you very much for your detailed error report. The new [WindTerm_2.6.0_Prerelease_9](https://github.com/kingToolbox/WindTerm/releases/tag/2.6-prerelease) should have fixed some connection issues. Please download and use it, and let me know if there are still any problems.

**Comment by wukakal** [comment]
The issue of IPv6 connection failure has been resolved in prerelease9.
Thank you very much!

**Comment by blueboyggh** [comment]
> Thank you very much for your detailed error report. The new [WindTerm_2.6.0_Prerelease_9](https://github.com/kingToolbox/WindTerm/releases/tag/2.6-prerelease) should have fixed some connection issues. Please download and use it, and let me know if there are still any problems.

Yes, the problem has been resolved in p9, thanks!

**Comment by woshi-Tom** [comment]
Hello, when I am using 2.6.1 to connect via IPv6, it shows a connection failure. I am not sure if this is caused by a bug. The specific error message for my system's Windows 11 is as follows
```
Failed opening file D:/100_data/140_dateBases/windTerm_data/.wind/profiles/default.v10/terminal/logs/【my ipv6】_2024-07-18_18-10-27.log for writing: invalid argument
会话已断开连接，按回车重新连接。
```

I tested version 2.6.0 and found that IPv6 addresses can connect normally. I'm not sure if it's a new bug in 2.6.1
