### ISSUE TITLE
有的服务器 文件管理器，无发自动同步

### ISSUE THREAD

**Issue by SiSe13** [kingToolbox/WindTerm#2065]
服务器是 天翼云    系统 Linux ecs-c69e-1129695 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux        本机:win10      例： 连接服务器后， 输入命令 cd /home    文件管理器  还是在刚开始的目录呆着，没有变化。
 连接其他的服务器 腾讯云  阿里云 没发现这个问题，这是和服务商有关？

**Comment by waittingsummer** [comment]
看我这里https://github.com/kingToolbox/WindTerm/issues/2004
look this:https://github.com/kingToolbox/WindTerm/issues/2004
![image](https://github.com/kingToolbox/WindTerm/assets/32017265/1af52069-682d-4081-a8a8-71168cd6fa22)
Conclusion: Here F9 must be selected！
结论：这里必须选中

**Comment by SiSe13** [comment]
选中了

**Comment by waittingsummer** [comment]
> 选中了

那就有可能这个操作系统不支持

![image](https://github.com/kingToolbox/WindTerm/assets/32017265/ec056864-ab52-4bf0-972d-57890e7c170b)
![image](https://github.com/kingToolbox/WindTerm/assets/32017265/5a5702ce-8948-4d8f-9338-9c801360d063)

**Comment by SiSe13** [comment]
嗯
