### ISSUE TITLE
Add the ability to save custom commands

### ISSUE THREAD

**Issue by wxpid1** [kingToolbox/WindTerm#2071]
有时候一些命令都是重复的操作，而且很容易忘记，如果软件功能记录这些命令，那这个软件真的是太完美了
Sometimes the commands are repeated and it's easy to forget that the software is perfect if the functionality logs them
![1705205005687](https://github.com/kingToolbox/WindTerm/assets/45633931/83cc5bf7-637a-4072-8335-abac367a9998)

**Comment by zhaoxiangyublzcat** [comment]
This feature is already available

**Comment by kingToolbox** [comment]
Thank you for your very good suggestion. This feature already exists. Please refer to the operations in [WindTerm - QuickBar](https://kingtoolbox.github.io/2020/08/22/quickbar/).

**Comment by wxpid1** [comment]
OK, thank you very much
