### ISSUE TITLE
How can I get windterm to better adapt to 4k?

### ISSUE THREAD

**Issue by allegrox** [kingToolbox/WindTerm#2072]
My OS is kali 2023.4 using a 4k monitor and when I run windterm the fonts for menus etc are very small and the zoom function only adjusts the font size in the terminal. I have turned on hidpi mode on the OS and all other software scales fine. How can I get windterm to better adapt to 4k please?

**Comment by kingToolbox** [comment]
If you need to adjust the interface font, you can modify the `font-size` of `QWidget` in the `WindTerm_Installed_Path/global/themes/dige-black/gui.theme`:

``` c
QWidget {
	font-family: "Roboto Mono", "Fira Code", "${SystemFonts}";
	font-size: 9pt;
	background-color: #1c1c1c;
	color: #bbbbbb;
}
```

Better support for high-resolution displays may have to wait for version `3.x`, which will use `Qt 6.x` and have better high-resolution support. Please stay tuned, thank you.
