### ISSUE TITLE
[feature-request] please add GB2312 charset!

### ISSUE THREAD

**Issue by dangbinghoo** [kingToolbox/WindTerm#208]
Hi, it seems that 2.1 version lacks of GB2312 charset, request to add this.

 thanks!

**Comment by kingToolbox** [comment]
WindTerm supports GB18030, which is a superset of GB2312, so it should be able to meet your needs.

**Comment by kingToolbox** [comment]
This issue has been solved and will be closed. Welcome to continue submitting new feature requests and bugs, thank you.
