### ISSUE TITLE
多网卡时无法连接

### ISSUE THREAD

**Issue by zyong419** [kingToolbox/WindTerm#2082]
很喜欢使用这个软件，感谢作者们的付出！最近遇到无法连接的问题：
1. 有两个网卡连接：一个是无线网络可以连接Internet，ip地址是10.72.38.25；一个是有线网络，ip地址是172.20.0.226（这是一个直连我开发板的网络）；
2. 使用WindTerm创建SSH连接到172.10.0.11，总是无法连接，一直弹出key选项界面；
3. 使用一个命令行工具ssh.exe(ssh root@172.10.0.11)可以正确连接到172.10.0.11；

**Comment by zyong419** [comment]
我有另外一台开发板，ip地址是192.168.1.11，同样把本地有线网络配置到192网段，使用WindTerm可以正常连接；使用SSH命令行工具也可以连接。

**Comment by GuguguBear** [comment]
*Note: The author has clearly stated in some problem reports in other countries’ languages that English should be used for problem reports to increase uniformity and facilitate viewing. No matter which country you are from, you should abide by this. For native English-speaking authors to frequently use their own country’s language to report problems in projects is disrespectful to the author. This is a very serious personal quality issue that we hope can be improved.
