### ISSUE TITLE
2.6.0 pre 10  no Sysmon ？？？

### ISSUE THREAD

**Issue by topsage** [kingToolbox/WindTerm#2088]
disappear？

![image](https://github.com/kingToolbox/WindTerm/assets/51810073/4afe8ed9-5f0f-4281-9872-955be1387dff)

**Comment by dawnlh** [comment]
You can try to turn on the sysmon through session setting, refer to ![](https://private-user-images.githubusercontent.com/51009775/297031882-571a9c96-445d-48d6-88be-eafd7d09b692.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5ODU2MzksIm5iZiI6MTcwNTk4NTMzOSwicGF0aCI6Ii81MTAwOTc3NS8yOTcwMzE4ODItNTcxYTljOTYtNDQ1ZC00OGQ2LTg4YmUtZWFmZDdkMDliNjkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDA0NDg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlYzE1ZDNmZDUzMWY4OTdjNWI5MWRhNjIxMDI5ZThhYTNkYmZhMGJhMTIwY2FjMjNhMjVkNTRiYTJjN2MyMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7A-nHfN_F4kvVxKlAaCwv2OwQQbd1_Vos3Kw2gYI_A4)
