### ISSUE TITLE
SSH会话密码字符显示不正确

### ISSUE THREAD

**Issue by csosmumu** [kingToolbox/WindTerm#2097]
SSH会话输入大写字母密码时 密码字符显示不正确 会出现输入一个字母为三个占位符

![bedafe7a52c06f747cd8e8111fe04c6](https://github.com/kingToolbox/WindTerm/assets/131222730/d071aba0-1f1f-42e5-958e-e434cd80fb0b)

![a75c44d9bdf9863bf05ba74696eed11](https://github.com/kingToolbox/WindTerm/assets/131222730/2144baf8-1bad-4a29-9f75-e795c4d7a917)

**Comment by Nowlang** [comment]
有没有可能是因为你设置里面开了随机回显字符，而不是bug

**Comment by jan-bar** [comment]
这是特性吧，不让别人知道密码长度。

**Comment by csosmumu** [comment]
> 有没有可能是因为你设置里面开了随机回显字符，而不是bug

你是说这个吗
![b14eda8cffe8a19a629a5a23caa1381](https://github.com/kingToolbox/WindTerm/assets/131222730/75607508-f3ce-4a16-b652-7b9c9c627df3)

**Comment by Nyar233** [comment]
It's a feature.

**Comment by jiangxianxu** [comment]
这个和在其它系统上输入密码时回显*是一个道理吧，就是只要输入的人搞对了就行了，回显什么是扰乱看的人的视线的。如果准确回显，至少泄漏了你的密码长度这个信息。所以这不是一个问题，而是一个功能。

**Comment by csosmumu** [comment]
> 这个和在其它系统上输入密码时回显*是一个道理吧，就是只要输入的人搞对了就行了，回显什么是扰乱看的人的视线的。如果准确回显，至少泄漏了你的密码长度这个信息。所以这不是一个问题，而是一个功能。

这一方面我还真没想过,因为记不住密码只能靠字符个数确定是否正确
