### ISSUE TITLE
can add double click the softlink to change into directory of the sftp filer?thanks

### ISSUE THREAD

**Issue by fuhuo** [kingToolbox/WindTerm#21]
I can't change the softlink(may not be hardlink also) to the link directory when i use the sftp filer change directory. 
but i can change into softlink direcrtory when i use input path's command of the filer.
can add it？thank you!

**Comment by kingToolbox** [comment]
This issue has been fixed in the version 1.72, please download and check, thank you.

Btw: Would you please check the issue #17 too, which you submitted earlier, if it has been fixed, please close it or notify me to close it, thanks.

**Comment by fuhuo** [comment]
Thanks for fixing.it's ok in version 1.72. And i think it would be great if the link icon better recognizable.

**Comment by kingToolbox** [comment]
It should be great :smile:, please download the new version [1.8 prerelease 1](https://github.com/kingToolbox/WindTerm/releases/tag/1.8) to check if the link icon is what you want now, thank you.

**Comment by fuhuo** [comment]
Nice!!!!
