### ISSUE TITLE
How can I solve the problem where macos uses windterm and pops up a window every time it restarts?

### ISSUE THREAD

**Issue by xingyue52077** [kingToolbox/WindTerm#2100]
"I am using macOS, and every time I restart the system, there is a popup when using the software. How can I set it to not show the popup?"
<img width="618" alt="Snipaste_2024-01-23_21-08-31" src="https://github.com/kingToolbox/WindTerm/assets/40156855/3cd1ce4b-e9f9-4f45-a264-d4ccff28556c">

**Comment by SnDream** [comment]
Linux is also affected by this issue.

As a work around, edit global/wind.config

```diff
@@ -62,7 +62,7 @@
   "terminal.mouseTracking.move": true,
   "terminal.mouseTracking.rightClick": false,
   "terminal.mouseTracking.wheel": true,
-  "terminal.reimportShellSessions": true,
+  "terminal.reimportShellSessions": false,
   "terminal.screen.pasteDialog": true,
   "terminal.startupSessions": "LastSessions",
   "terminal.rightClickAction": "ShowMenu",
```


or

find user.config in your windterm config path
Backup user.config and add this line:
```
    "terminal.reimportShellSessions" : false,
```
(noting the comma placement)

**Comment by xingyue52077** [comment]
Thank you very much for your answer, the problem is solved.

**Comment by kingToolbox** [comment]
I confirm that this is a bug, I will fix it. Please stay tuned, thank you.

**Comment by kingToolbox** [comment]
[WindTerm 2.7.0 Prerelease 2](https://github.com/kingToolbox/WindTerm/releases/tag/2.7-prerelease-2) has addressed this issue, but the macOS version may not be released until the end of the month. Please be patient. Thank you.
