### ISSUE TITLE
Rainbow brackets make writing code in Linux a mess. How to turn off this feature?

### ISSUE THREAD

**Issue by jaco00** [kingToolbox/WindTerm#2111]
If you use vim to open the code, the unmatched brackets in the current screen are marked in red. We all know that the code cannot be completely displayed on one screen, so the brackets on the current screen cannot match perfect。The key thing is that If you see red brackets in your code, it might be indicating a syntax error or a problem that the compiler has identified.
![Untitled](https://github.com/kingToolbox/WindTerm/assets/48374089/6211ff03-71e5-4373-affe-17334ed41524)

**Comment by jaco00** [comment]
I removed the relevant configuration from scheme.theme so it looks correct now.In fact, the editor already has similar functions, which will conflict with the terminal.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/kingToolbox/WindTerm/issues/2111#issue-2101261506

@jaco00, https://github.com/kingToolbox/WindTerm/releases/tag/2.7-prerelease#:~:text=%5Bgui%5D%20disables%20rainbow%20brackets%20on%20the%20alt%20screen%20to%20avoid%20conflicts%20with%20features%20in%20editors%20like%20vim.%20%232111 appears to state that this has been remediated.

**Comment by jaco00** [comment]
I've seen the updates，This makes things much more convenient now, thank you!

**Comment by jaco00** [comment]
> > [#2111 (comment)](https://github.com/kingToolbox/WindTerm/issues/2111#issue-2101261506)
> 
> @jaco00, https://github.com/kingToolbox/WindTerm/releases/tag/2.7-prerelease#:~:text=%5Bgui%5D%20disables%20rainbow%20brackets%20on%20the%20alt%20screen%20to%20avoid%20conflicts%20with%20features%20in%20editors%20like%20vim.%20%232111 appears to state that this has been remediated.

I've seen the updates，This makes things much more convenient now, thank you!

**Comment by RokeJulianLockhart** [comment]
> https://github.com/kingToolbox/WindTerm/issues/2111#issuecomment-2035047800

@jaco00, is it worth closing this consequently?

**Comment by kingToolbox** [comment]
@RokeJulianLockhart
Thank you very much.

@jaco00
Great to hear that it seems to be working well so far, that's really fantastic. I originally thought about making it an option, but in the end, I still felt that completely disabling it was simpler and more straightforward. Of course, if I weren't traveling the whole time, I would have directly sought your advice.

This issue will be closed. If you have any other questions, feel free to reach out at any time. Thank you.

**Comment by jaco00** [comment]
> is it worth closing this consequently
Sure thing

**Comment by RokeJulianLockhart** [comment]
> https://github.com/kingToolbox/WindTerm/issues/2111#issuecomment-2035350299

@kingToolbox, so it doesn't exist in the regular terminal anymore? (I can't test because of https://github.com/kingToolbox/WindTerm/discussions/2259#discussioncomment-8998481.) If so, that's a shame, because I really like that feature in my text editors, and have always wanted it in my terminal.

**Comment by kingToolbox** [comment]
@RokeJulianLockhart 
It's my fault for not explaining clearly. What's being canceled is only the `rainbow brackets` in the `alternative screen`, such as `vi`, etc. The main screen is not affected, which means you will still see `rainbow brackets` when you are entering command lines.
