### ISSUE TITLE
The passphrase for OneKey for public key authentication is stored but not working

### ISSUE THREAD

**Issue by ViceEye** [kingToolbox/WindTerm#2120]
Why the passphrase is stored but when try to log in it's not able to pass

![image](https://github.com/kingToolbox/WindTerm/assets/17517159/aef30f64-bcd6-441a-8c58-6e9eaca3c34f)

![image](https://github.com/kingToolbox/WindTerm/assets/17517159/1941fa92-08d2-4cea-aeff-8fdb73dd863e)

I have to manually type in the passphrase to log in, the passphrase is the same as it stored

**Comment by ViceEye** [comment]
but not using onekey, log in the session manually and check auto-login, it can be saved and worked well, where did it save to?

**Comment by PMExtra** [comment]
I have the same problem. Does anyone have a solution?

**Comment by dodedov** [comment]
OneKey doesn't work for me either. I use save password.

**Comment by vfhky** [comment]
the same problem

**Comment by PMExtra** [comment]
@ViceEye @dodedov @vfhky I found that, OneKey (public key) does not work if the ssh server enabled the password authentication.

After I set the `PasswordAuthentication no` and restarted sshd, OneKey works well as expected.

I believe this is really a bug, I'm looking forward it be fixed. @kingToolbox

**Comment by vfhky** [comment]
> @ViceEye @dodedov @vfhky I found that, OneKey (public key) does not work if the ssh server enabled the password authentication.
> 
> After I set the `PasswordAuthentication no` and restarted sshd, OneKey works well as expected.
> 
> I believe this is really a bug, I'm looking forward it be fixed. @kingToolbox

i'm not sure the reson you said for i have forbided passwordAuthentication. lastly i have turned around to termius.

**Comment by Junohea** [comment]
This seems like its still an issue.

Load password-protected private key & put in the passphrase
![image](https://github.com/user-attachments/assets/862bf1f4-11cb-4a21-99e9-f6f379686226)

attempt to connect and get an authentication failure. enter the passphrase again and it logs in
![image](https://github.com/user-attachments/assets/13df57d7-b4bd-467f-852b-39d1ab8e8d41)

tried going into the auth settings and selecting only public-key, issue still persists
![image](https://github.com/user-attachments/assets/da6decb9-cc6e-4af7-8b7f-52497f944120)

also tried a number of different combinations on the SSH server for PasswordAuthentication / PAM / etc and the issue still persists. Was able to test with BitVise and there were no issues.

Anyone know whats going on here?
