### ISSUE TITLE
Could you release x86_64 binraries?

### ISSUE THREAD

**Issue by skbeh** [kingToolbox/WindTerm#213]
Almost every modern x86 cpu supports 64bit and benefits from it. Windows 11 even dropped the support of 32bit x86 cpu.

**Comment by kingToolbox** [comment]
Sorry, x86_64 version will not be considered for the time being. That will increase the workload of release and maintenance. At present, x86 version can run well in various systems, including Windows 11. Although the system resources cannot be fully utilized, there are no reports of insufficient performance. 

The current focus is still on developing new features, and when the development of new features is almost complete, I will release the x86_64 version. Please stay tuned, thank you.

**Comment by skbeh** [comment]
For example, its cmd shortcut starts 32bit cmd because Windows redirected the path to C:\Windows\SysWOW64\cmd.exe . The powershell which starts from Windterm faces the same problem and the 32bit powershell may not able to call 64bit dll modules.

**Comment by kingToolbox** [comment]
When scanning `cmd` and `powershell` to generate the default shells, WindTerm does only automatically scan the 32-bit `cmd` and `powershell`, which is intended to provide better compatibility. But as you said, 64-bit modules cannot be run. The solution is very simple, you can create a 64-bit `cmd` or `powershell` session configuration by yourself. 

- New session and select `Shell` tab.
- Select `Custom` from the `Shell - Shell` drop-down box. 
- Input the x64 path of `cmd` or `powershell` in the `Shell - Shell` combo box.
- Done.

The default 64-bit `cmd` and `powershell` will be added in the next version, and this does not require WindTerm to be compiled into a 64-bit program. Thank you.
