### ISSUE TITLE
Support android app

### ISSUE THREAD

**Issue by Pumpkinor** [kingToolbox/WindTerm#2186]
would you mind add android app to releases platform

**Comment by Pumpkinor** [comment]
and ios app so on

**Comment by RokeJulianLockhart** [comment]
> https://github.com/kingToolbox/WindTerm/issues/2186#issuecomment-1974576461

@Pumpkinor, you need to rename this issue to "Mobile" rather than "Android", and/or create a separate issue for iOS, if you want both.
