### ISSUE TITLE
Chinese-Language Support

### ISSUE THREAD

**Issue by duanqichao** [kingToolbox/WindTerm#22]
You did a amazing job！Can it support Chinese? What to do to make it support Chinese?

**Comment by kingToolbox** [comment]
What does it mean to support Chinese? If it refers to the Chinese user interface, there is not yet. But if it means supporting Chinese text display and input method, yes, it has been supported already.

**Comment by duanqichao** [comment]
I mean Chinese user interface.

**Comment by kingToolbox** [comment]
Multilingual interface is already supported, but there is no translation file, not only Chinese, but also Japanese, French, etc.

These require a lot of assistance. It is expected that this can only be done after a certain number of users. I hope that 2.x series can be translated into multiple languages.

**Comment by duanqichao** [comment]
I am glad to hear the news.If necessary, I can help translate the Chinese part. My English is not very good, but I can refer to other similar software translations.

**Comment by kingToolbox** [comment]
Thank you, I really appreciate it!

The most important thing now is to release the Linux and Mac version. So I expect to provide Multilingual interface in the 2.x series, starting with Chinese. The time is estimated to be around the end of this year. Looking forward to your help, thanks again.

**Comment by kingToolbox** [comment]
The new [WindTerm_2.2.0_Prerelease_4](https://github.com/kingToolbox/WindTerm/releases/tag/2.2-prerelease) version has been released and the Chinese interface has been supported, please download and check it, thank you.

**Comment by funkpopo** [comment]
> The new [WindTerm_2.2.0_Prerelease_4](https://github.com/kingToolbox/WindTerm/releases/tag/2.2-prerelease) version has been released and the Chinese interface has been supported, please download and check it, thank you.

I am sorry to make a reply to this CLOSED Issue! But still thank you for the amazing job! I just found out that I can edit locale files to correct the language mistakes. But I cannot find any locale files' index in the forked source code. What can I do to help you improve the locale files? I also met few inconvenient problems but I am gonna open another Issue to discuss them.

**Comment by kingToolbox** [comment]
Just file new issues and I will deal with them. :smile: Because there are still a few strings that have not been extracted from source, the locale files will be uploaded after the `WindTerm_2.2.0` version is released. You are welcome to update the translation at that time, thank you very much.
