### ISSUE TITLE
how to save password in order to auto login next time？怎么保存密码，下次自动登录？

### ISSUE THREAD

**Issue by skykis** [kingToolbox/WindTerm#220]
how to save password in order to auto login next time？
怎么保存密码，下次自动登录？
I need to input password and user after close it everytime ,now

**Comment by kingToolbox** [comment]
Hi, I think you should have found out, you only need to check the `Auto login next time` in the login wizard to log in automatically. You can read [auto-login](https://kingtoolbox.github.io/2020/01/23/auto-login/) to learn more, thank you.
