### ISSUE TITLE
How do I use Sysmon?

### ISSUE THREAD

**Issue by 404invalid-user** [kingToolbox/WindTerm#2216]
i have seen https://kingtoolbox.github.io/2022/08/21/sysmon/ but it gives no info on what to do if its not there 

i am running the latest version 1.6.0 on macos connecting to Ubuntu based systems and just don't see the option 
<img width="241" alt="Screenshot 2024-03-11 at 20 02 37" src="https://github.com/kingToolbox/WindTerm/assets/68563978/ade50e06-b0f8-486a-a8f0-7fce0fe830ed">

**Comment by chcc789** [comment]
you can open it when you open or config a session 
![1726652056461](https://github.com/user-attachments/assets/c4ffd7ba-98ab-4d10-8c2b-de70579e17cc)

**Comment by 404invalid-user** [comment]
as i said it was not there I resolved my issue by removing the app/config and downloading it again
