### ISSUE TITLE
when I use windows10 firewall block windterm all ".exe" files network connection, it can still connect remote server via ssh

### ISSUE THREAD

**Issue by shinebay** [kingToolbox/WindTerm#222]
block windterm directory all ".exe" files network connection, but still ssh works well, sftp works well
(server connect proxy option: SOCKS5 proxy)
I want to know the reason
thank you

**Comment by kingToolbox** [comment]
WindTerm uses `libssh` to implement the `SSH` and `SFTP` features, so all SSH sockets are connected by the `ssh.dll` share library. I guess for this reason, you need to prohibit `ssh.dll` from connecting in the firewall. To be honest, I don't know how to block a `.dll` in a firewall.

The rest of the connections are completed by WindTerm itself, so after the firewall is enabled, WindTerm theoretically should not be able to `Telnet` to any remote host, you can verify it. Thank you.

**Comment by kingToolbox** [comment]
This issue has been solved and will be closed. Welcome to continue submitting new feature requests and bugs, thank you.
