### ISSUE TITLE
命令行自动换行

### ISSUE THREAD

**Issue by Leetion07** [kingToolbox/WindTerm#2252]
1. 使用版本 2.6.0 预发
2. 背景：当命令行输入长命令 或者 命令行输出了不换行的输出时，没有自动换行，导致必须拉下面的进度条。有点影响使用体验。
3. 请问该问题有办法设置或者在更新的版本中解决吗

**Comment by speakchan** [comment]
你找到解决办法了嘛？我是直接按ctrl键加鼠标滚动轴，把字体变小点，解决问题！不知道有没有地方设置长命令多少字符自动换行的

**Comment by Leetion07** [comment]
> 你找到解决办法了嘛？我是直接按ctrl键加鼠标滚动轴，把字体变小点，解决问题！不知道有没有地方设置长命令多少字符自动换行的

菜单栏:`模式`，选择`自动换行` 即可。
