### ISSUE TITLE
Suggestion: Put "profiles.config" under "%APPDATA%\WindTerm\" on Windows OS

### ISSUE THREAD

**Issue by robot-dot-win** [kingToolbox/WindTerm#2263]
Reasons:
1. A user may not have sufficient privilege to write the program directory;
2. There may be many users on a same system.

**Comment by kingToolbox** [comment]
Thank you, but this will make it difficult to migrate the configuration file of `WindTerm` to other machines. Since `WindTerm` is a portable software, I don't recommend placing it under a special path that requires special permissions.

**Comment by owenstake** [comment]
This is not a good idea.
