### ISSUE TITLE
MacBook prompts to reimport the Shell sessions every time it starts the software

### ISSUE THREAD

**Issue by Z46I4W5476SJA** [kingToolbox/WindTerm#2287]
macbook每次启动软件提示
The following new features have been added to Shell sessions:

- Supports "--login", "-i"
- Supports new "macOS" system
- Supports new "wsl" system
- Automatic locale detection

Do you want to reimport the Shell sessions?

If I choose not to import, I can close the pop-up window, but it will prompt me again next time I open the software.
If I choose to import, after importing, and restart the software again, a pop-up window will still appear.

So how can I close this pop-up window?

![image](https://github.com/kingToolbox/WindTerm/assets/45085951/635f82fc-29e4-4c1f-a1b3-974447740269)

**Comment by ErBWs** [comment]
Hi, i'm wondering how you solve this problem? cause I encoutered this problem too

**Comment by AlanBrian-z** [comment]
I am also experiencing the same issue.

**Comment by dongwei1220** [comment]
I am also experiencing the same issue. how to solve it?

**Comment by junyangfan** [comment]
I am also experiencing the same issue. how to solve it?

**Comment by AlanBrian-z** [comment]
Can refer to this https://github.com/kingToolbox/WindTerm/issues/2119

**Comment by liamlycoder** [comment]
change this option to 2 in ~/.wind/profiles/default.v10/user.config
{
"terminal.reimportShellSessions" : 2
}

**Comment by junyangfan** [comment]
> change this option to 2 in ~/.wind/profiles/default.v10/user.config { "terminal.reimportShellSessions" : 2 }

yes，i know,thanks

**Comment by billy-he** [comment]
right, thanks

> change this option to 2 in ~/.wind/profiles/default.v10/user.config { "terminal.reimportShellSessions" : 2 }

**Comment by zengzzzzz** [comment]
it does work. thanks.

**Comment by tv21** [comment]
Just for the benefit of anyone who may come across this, in version 2.6.1 (at least in the Linux version) the location of this setting appears to have changed, it is now in <program directory>/global/wind.config and the setting you are looking for is

"terminal.reimportShellSessions": true,

and you want to change the true to false.  Do NOT try to add the setting to ~/.wind/profiles/default.v10/user.config if it's not there or you will lose all your configuration settings.  Don't ask me how I know! :(

(To the developer:  How about a "Don't ask again" checkbox on that popup?)
