### ISSUE TITLE
The tab bar is too wide

### ISSUE THREAD

**Issue by ZHAIXINGZHAIYUE** [kingToolbox/WindTerm#23]
Hello,
When I have a lot of sessions, the tab bar is too wide to display.

**Comment by kingToolbox** [comment]
There is currently no interface to set. You need to open and modify the **gui.theme** of the current theme.

For example, assuming that the current theme is black, please open **WindTerm-Install-Path/global/themes/dige-black/gui.theme** and set the **min-width** of **#ViewGroup > QTabBar::tab** to a smaller value and restart.
```
#ViewGroup > QTabBar::tab {
  max-width: 20em;   /* The maximum width of the tab. */
  min-width: 7em;    /* The minimum width of the tab. */
}
```

**Comment by ZHAIXINGZHAIYUE** [comment]
Thank you!
