### ISSUE TITLE
使用Minicom跳转之后部分换行符出现异常。

### ISSUE THREAD

**Issue by no553216989** [kingToolbox/WindTerm#2369]
内容是在环境用minicom连串口后的显示效果
![image](https://github.com/kingToolbox/WindTerm/assets/15682049/c904cc4a-8893-47d6-894a-42ba5cbae806)
源内容：应该是类似这种
![image](https://github.com/kingToolbox/WindTerm/assets/15682049/129e384a-b243-4175-a936-5436a0348858)
看起来dw10 , 后面的没有显示出来直接显示下一行了

**Comment by no553216989** [comment]
进展：应该是因为minicom会根据当前的窗口列数设置每行打印字符上限，现在软件限制窗口是47x80
![image](https://github.com/kingToolbox/WindTerm/assets/15682049/55419013-f689-41e7-93cf-b1c0345b492d)
并且我在设置中的修改无法生效，请问一下这个是什么原因？
![image](https://github.com/kingToolbox/WindTerm/assets/15682049/ec662dac-1f37-4f38-9aa5-384986703198)

**Comment by yonghuizhan** [comment]
> 进展：应该是因为minicom会根据当前的窗口列数设置每行打印字符上限，现在软件限制窗口是47x80 ![image](https://private-user-images.githubusercontent.com/15682049/331958839-55419013-f689-41e7-93cf-b1c0345b492d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzODc2ODEsIm5iZiI6MTcxOTM4NzM4MSwicGF0aCI6Ii8xNTY4MjA0OS8zMzE5NTg4MzktNTU0MTkwMTMtZjY4OS00MWU3LTkzY2YtYjFjMDM0NWI0OTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA3MzYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViYTAwMTVhMGM1Zjk4YTc2MGYxMjQ4NjBkNmQzYzI5ZTA5OGU3ZTQ3ZWQ5YzcyYzJkZDU1OTI1ZjUzY2I2MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S0sRGG9h7DW0jcGhqV36CaTDDgpZKTEVksA3SSpiqIU) 并且我在设置中的修改无法生效，请问一下这个是什么原因？ ![image](https://private-user-images.githubusercontent.com/15682049/331959004-ec662dac-1f37-4f38-9aa5-384986703198.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzODc2ODEsIm5iZiI6MTcxOTM4NzM4MSwicGF0aCI6Ii8xNTY4MjA0OS8zMzE5NTkwMDQtZWM2NjJkYWMtMWYzNy00ZjM4LTlhYTUtMzg0OTg2NzAzMTk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA3MzYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3MjQ1NGI2YWM2YTQwNDY1YTQxMjBmMDI1ZjRhN2E2NWZmMWUwYWYwM2QxODA3YWUxNjE5YmE2YTdjOGQ3ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aFIn3nebQEvTZ6k9g1iBvZ23sbwyajSLLachUzgopzI)
选择编辑默认选项修改就可以了
![image](https://github.com/kingToolbox/WindTerm/assets/96530629/70685d92-e3ee-4a4a-b5fd-5a2b7827304a)

**Comment by no553216989** [comment]
> > 进展：应该是因为minicom会根据当前的窗口列数设置每行打印字符上限，现在软件限制窗口是47x80 ![image](https://private-user-images.githubusercontent.com/15682049/331958839-55419013-f689-41e7-93cf-b1c0345b492d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzODc2ODEsIm5iZiI6MTcxOTM4NzM4MSwicGF0aCI6Ii8xNTY4MjA0OS8zMzE5NTg4MzktNTU0MTkwMTMtZjY4OS00MWU3LTkzY2YtYjFjMDM0NWI0OTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA3MzYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViYTAwMTVhMGM1Zjk4YTc2MGYxMjQ4NjBkNmQzYzI5ZTA5OGU3ZTQ3ZWQ5YzcyYzJkZDU1OTI1ZjUzY2I2MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S0sRGG9h7DW0jcGhqV36CaTDDgpZKTEVksA3SSpiqIU) 并且我在设置中的修改无法生效，请问一下这个是什么原因？ ![image](https://private-user-images.githubusercontent.com/15682049/331959004-ec662dac-1f37-4f38-9aa5-384986703198.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzODc2ODEsIm5iZiI6MTcxOTM4NzM4MSwicGF0aCI6Ii8xNTY4MjA0OS8zMzE5NTkwMDQtZWM2NjJkYWMtMWYzNy00ZjM4LTlhYTUtMzg0OTg2NzAzMTk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA3MzYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3MjQ1NGI2YWM2YTQwNDY1YTQxMjBmMDI1ZjRhN2E2NWZmMWUwYWYwM2QxODA3YWUxNjE5YmE2YTdjOGQ3ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aFIn3nebQEvTZ6k9g1iBvZ23sbwyajSLLachUzgopzI)
> > 选择编辑默认选项修改就可以了
> > ![image](https://private-user-images.githubusercontent.com/96530629/343054567-70685d92-e3ee-4a4a-b5fd-5a2b7827304a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzODg0NTUsIm5iZiI6MTcxOTM4ODE1NSwicGF0aCI6Ii85NjUzMDYyOS8zNDMwNTQ1NjctNzA2ODVkOTItZTNlZS00YTRhLWI1ZmQtNWEyYjc4MjczMDRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA3NDkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmMjBhOTZmNDYwZDA5Mzk2M2VjNDA5MjhlNmJjY2RlM2IyZTlhZTE1NjVjM2FhN2IyYjFkZjY5ODFlMGE0NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ke9gX1p7XXlZZkvNIQGyv0B3wkBqv6SMg_yVQac9YUM)

![image](https://github.com/kingToolbox/WindTerm/assets/15682049/53bf27fd-2558-4ffe-a53e-4364095ae9d5)
已经找到原因了，主要是这个调整窗口行列的√要去掉
