### ISSUE TITLE
2.5.0版本，不知道点了哪里，命令行总是显示换行符。如何不显示换行符呢？

### ISSUE THREAD

**Issue by p-feng** [kingToolbox/WindTerm#2405]
![image](https://github.com/kingToolbox/WindTerm/assets/55753926/bbd6eda0-a841-4fa3-95f3-51eeb4645abb)

**Comment by GmanStak** [comment]
菜单栏->查看->符号，取消勾选行尾

**Comment by p-feng** [comment]
> 菜单栏->查看->符号，取消勾选行尾

好使。多谢了

**Comment by p-feng** [comment]
houhou
