### ISSUE TITLE
中文下两个地方乱码

### ISSUE THREAD

**Issue by zhongzhichun** [kingToolbox/WindTerm#242]
直接看图吧
1.
![图片](https://user-images.githubusercontent.com/12390350/139019285-d5ecf6aa-3b46-4f15-9c62-0f82a58e2e2a.png)
2.
![图片](https://user-images.githubusercontent.com/12390350/139019351-4791fab1-e00c-4474-9afe-d2bfa2d0d797.png)

**Comment by kingToolbox** [comment]
The new [WindTerm_2.2.0_Prerelease_4](https://github.com/kingToolbox/WindTerm/releases/tag/2.2-prerelease) version has been released and this issue has been fixed, please download and check it, thank you.

**Comment by zhongzhichun** [comment]
> 
> 
> The new [WindTerm_2.2.0_Prerelease_4](https://github.com/kingToolbox/WindTerm/releases/tag/2.2-prerelease) version has been released and this issue has been fixed, please download and check it, thank you.

**Comment by kingToolbox** [comment]
I am glad you like `WindTerm`. With the improvement of basic features, we have just begun. :smile: Starting from the next 2.3.0 version, `WindTerm` will bring exciting and innovative features, you can read [this comment](https://github.com/kingToolbox/WindTerm/issues/239#issuecomment-951934488) to learn more. If you have any needs and ideas, please let me know. Thank you.
