### ISSUE TITLE
2.6.1 cannot connect remote-host with ipv6

### ISSUE THREAD

**Issue by woshi-Tom** [kingToolbox/WindTerm#2459]
cannot connect with ipv6

**Comment by woshi-Tom** [comment]
Hello, I encountered an error while connecting to an IPv6 host using version 2.6.1 and am unable to connect.
System: Win11 Home Edition

**error info:**
```
Failed opening file D:/100_data/140_dateBases/windTerm_data/.wind/profiles/default.v10/terminal/logs/
[my IPv6]_2024-07-19_11-29-53.log for writing: invalid argument
会话已断开连接，按回车重新连接。

```


I tested version 2.6.0 and it can connect using IPv6. I'm not sure why version 2.6.1 cannot connect using IPv6, maybe it's a bug

**Comment by GitCourser** [comment]
Did you automatically import the configuration of the `.ssh/config` file? The ipv6 address in it has square brackets `[]`. In the session settings in windterm, you can log in by removing the `[]` square brackets from the host address in the session settings.

**Comment by woshi-Tom** [comment]
> 您是否自动导入了文件的配置？其中的 ipv6 地址带有方括号。在windterm的会话设置中，您可以通过在会话设置中删除主机地址的方括号来登录。`.ssh/config``[]``[]`

Yes, when I upgraded from 2.6.0 to 2.6.1, I imported the config file for 2.6.0. I later learned through a network search that I directly filled in the IPv6 address, but it still doesn't seem to work, and it is also an error
```
Failed opening file D:/100_data/140_dateBases/windTerm_data/.wind/profiles/default.v10/terminal/logs/fe80%3A%3A20c%3A29ff%3Afea5%3A13e9/fe80::20c:29ff:fea5:13e9_2024-08-05_14-54-49.log for writing: invalid argument
会话已断开连接，按回车重新连接。
```

![image](https://github.com/user-attachments/assets/b31584f2-192f-452d-abe4-b08ecab464ee)
![image](https://github.com/user-attachments/assets/f89d4b1c-36a6-404c-8ae1-906e906af3f5)

**Comment by woshi-Tom** [comment]
> 您是否自动导入了文件的配置？其中的 ipv6 地址带有方括号。在windterm的会话设置中，您可以通过在会话设置中删除主机地址的方括号来登录。`.ssh/config``[]``[]`

Yes, when I upgraded from 2.6.0 to 2.6.1, I imported the config file for 2.6.0. I later learned through a network search that I directly filled in the IPv6 address, but it still doesn't seem to work, and it is also an error
```
Failed opening file D:/100_data/140_dateBases/windTerm_data/.wind/profiles/default.v10/terminal/logs/fe80%3A%3A20c%3A29ff%3Afe25%3A8e1a/fe80::20c:29ff:fe25:8e1a_2024-08-05_15-05-49.log for writing: invalid argument
会话已断开连接，按回车重新连接。
```
![image](https://github.com/user-attachments/assets/65da54ee-7d48-42ad-a4fa-8a2411448f60)
![image](https://github.com/user-attachments/assets/34ee7210-2520-4873-84b4-e21317b222d7)

The above is the configuration information

**Comment by GitCourser** [comment]
In the configuration I imported before, the host was `user@[xxxx:xxxx:xxxx....]` but the connection could not be connected. If I changed it to `user@xxxx:xxxx:xxxx....` I could connect.
Version: 2.6.1
Make sure your ipv6 address can really connect, such as `ping` or `openssh`

**Comment by woshi-Tom** [comment]
> 在我之前导入的配置中，主机是，但无法连接。如果我将其更改为我可以连接。版本： 2.6.1 请确保您的 ipv6 地址可以真正连接，例如 或`user@[xxxx:xxxx:xxxx....]``user@xxxx:xxxx:xxxx....``ping``openssh`

Thank you for your reply, I'll try again

**Comment by woshi-Tom** [comment]
> In the configuration I imported before, the host was `user@[xxxx:xxxx:xxxx....]` but the connection could not be connected. If I changed it to `user@xxxx:xxxx:xxxx....` I could connect. Version: 2.6.1 Make sure your ipv6 address can really connect, such as `ping` or `openssh`



> In the configuration I imported before, the host was `user@[xxxx:xxxx:xxxx....]` but the connection could not be connected. If I changed it to `user@xxxx:xxxx:xxxx....` I could connect. Version: 2.6.1 Make sure your ipv6 address can really connect, such as `ping` or `openssh`

Thanks, it was solved according to your method
