### ISSUE TITLE
3 New feature advices about the choice & upload files to host. This will help users to easily use the upload files function.

### ISSUE THREAD

**Issue by yaray** [kingToolbox/WindTerm#247]
1. New feature advice: add a sort by file extension function when choice & upload files to host. This will help users to easily find the target file.

2. New feature advice: remember the choice file dialog window's size and location. When users open the dialog window again, it can restore the remembered window's size and location.

3. New feature advice: When users press the Ctrl key in the choice file dialog window, they can choose multiple files to upload.

I hope these features can be append the development schedule in the future.
Thank you very much!

**Comment by kingToolbox** [comment]
Thank you for your suggestions. I checked and confirmed that the first and third requirements should have been met, at least in the `Windows` operating system. You can try it. If your system is not `Windows`, please tell me the system name and version number.

For the second requirement, I will complete it in the next prerelease version. I will update the progress here, please stay tuned, thank you.

**Comment by yaray** [comment]
Sorry for the first suggestion, it was not carefully tested last night. When the file upload window is first opened, the file is listed in List View mode, file name sequence; switch to Detail View mode, then click on file type to sort by file type mode, and then switch back to List View mode, it lists the file in file type mode. When opening the file upload window again, it lists files in file type. This is the expected way that I want.

For the third suggestion, when I hold the Ctrl key and click multiple files separately, the filename input box always shows the last clicked filename, rather than the expected multiple filenames separated by commas.
OS: Windows 7 旗舰版 SP1
WindTerm_2.2.0_Prerelease_3_Windows_Portable

Thanks for your reply!

**Comment by kingToolbox** [comment]
I tested this in the `Windows 7 Professional` operating systems, everything is Ok. but instead of separating files with commas, the dialog use spaces, such as `"123.txt" "456.txt" "789.json"`. Please note that only `Upload dialog` supports multiple selection, not `Download dialog`. 

BTW:
The second feature you mentioned has been completed and will be released in the next prerelease 4 version, which is expected within this week. :smile:

**Comment by yaray** [comment]
Yes, it's the upload file dialog window, press F4 hot key or click pop-menu item "&Upload to current folder...     (F4)" to open it in the left side Filer pane.
Not mind it is commas or space, quote the filename is perfect.

Very good message!

**Comment by kingToolbox** [comment]
Sorry for the late reply.

It seems that the single-selection bug you mentioned is still exists. I will test on more `Windows 7` to see if it can be reproduced. 

BTW:
When you select multiple files by pressing `Ctrl`, although it seems that only the last file is selected, but if you click `Upload`, will the last selected file or all the selected files be uploaded?

**Comment by kingToolbox** [comment]
The new [WindTerm_2.2.0_Prerelease_4](https://github.com/kingToolbox/WindTerm/releases/tag/2.2-prerelease) version has been released and when the `Download/Upload` dialog is opened, the last geometry will be restored, please download and check it, thank you.

**Comment by yaray** [comment]
I downloaded and upgraded to the "WindTerm_2.2.0_Prerelease_4_Windows_Portable" version last night. I confirmed the second feature is OK. Thank you very much!

After upgrade to the "WindTerm_2.2.0_Prerelease_4_Windows_Portable" version, I test the upload file function, it just upload the last click file to the host, it seems same as the before version (WindTerm_2.2.0_Prerelease_3_Windows_Portable).

**Comment by kingToolbox** [comment]
Can you test `choose multiple files to upload` on another machine? Because I have tested it on multiple machines and there is no problem. Thank you.

**Comment by yaray** [comment]
Sorry for the late reply.

I test select multiple files in Windows 7, confirmed the Ctrl key is OK.
Sorry, I haven't another machine to test this function.

Now that you've tested it on multiple machines, I think it's best to turn it off first, after all, it won't affect too much, thanks for your efforts!
