### ISSUE TITLE
Is the WindTerm 2.2.0 Prerelease 3 version not for Linux?

### ISSUE THREAD

**Issue by kendling** [kingToolbox/WindTerm#249]
I can't find the download url of the WindTerm 2.2.0 Prerelease 3 version for Linux?

**Comment by kingToolbox** [comment]
As stated in the [release notes](https://github.com/kingToolbox/WindTerm/releases/tag/2.2-prerelease):

 **Linux version and MacOS version will be released after the Windows version is stable, and are expected to be released as 2.2.0 Prerelease 4.**

So there is no `WindTerm 2.2.0 Prerelease 3` Linux version. But the good news is that the `WindTerm 2.2.0 Prerelease 4` Linux version will be released this week. Please stay tuned, thank you.

**Comment by helloxz** [comment]
> As stated in the [release notes](https://github.com/kingToolbox/WindTerm/releases/tag/2.2-prerelease):
> 
> **Linux version and MacOS version will be released after the Windows version is stable, and are expected to be released as 2.2.0 Prerelease 4.**
> 
> So there is no `WindTerm 2.2.0 Prerelease 3` Linux version. But the good news is that the `WindTerm 2.2.0 Prerelease 4` Linux version will be released this week. Please stay tuned, thank you.

Look forward to releasing it as soon as possible.

**Comment by kendling** [comment]
Thank you for your hard work!

**Comment by kingToolbox** [comment]
The new [WindTerm_2.2.0_Prerelease_4](https://github.com/kingToolbox/WindTerm/releases/tag/2.2-prerelease) version has been just released, please download and check it, thank you.
