### ISSUE TITLE
Chinese Characters in Session Titles Display as Garbled Text

### ISSUE THREAD

**Issue by huangming** [kingToolbox/WindTerm#2502]
Hi there,

I am currently using WindTerm and have encountered an issue with the display of session titles in the "openssh sessions" section. Specifically, when a session title contains Chinese characters, the text appears as garbled or unreadable.

Steps to Reproduce:

1.rename the title of test configuration on ~/.ssh/config:
```
Host test-测试
    HostName YOUR_SERVER_IP
```
2.login the server useing powershell

3.reopen WindTerm and view the session in the openssh-sessions list.

Expected Behavior:
The session titles with Chinese characters should display correctly and be readable.

Actual Behavior:
The titles with Chinese characters are shown as garbled text.

Additional Information:

WindTerm version: [WindTerm_2.6.1_Windows_Portable_x86_64]
Operating System: [win10]
![image](https://github.com/user-attachments/assets/53fd87a0-e508-446f-90ea-c2e7a4bd0355)

Suggestions:
This issue might be related to character encoding settings. Please check if there's a way to ensure that Chinese characters are properly encoded and displayed.

Thank you for your attention to this matter.

Best regards,

**Comment by gooker** [comment]
编码不要使用utf8,使用gbk就好了

**Comment by huangming** [comment]
> 编码不要使用utf8,使用gbk就好了

你是说~/.ssh/config这个文件的编码么？修改了确实可以。我以前用tssh的，修改了编码后tssh里面就乱码了。不过tssh可以指定其他配置文件，问题不是很大。就是不知道这个文件一般的标准是什么编码的。
谢谢解答
