### ISSUE TITLE
左滑复制 命令行端会直接ctrl+c 中断命令

### ISSUE THREAD

**Issue by youxihu** [kingToolbox/WindTerm#2517]

**Comment by fjh1997** [comment]
See https://github.com/kingToolbox/WindTerm/issues/2296#issuecomment-2316686021

**Comment by youxihu** [comment]
Thank you very much. After reviewing the commit records, the issue has been resolved

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月02日 21:52 |
| 收件人 | kingToolbox/WindTerm ***@***.***> |
| 抄送人 | youxihu ***@***.***>,
State ***@***.***> |
| 主题 | Re: [kingToolbox/WindTerm] 左滑复制 命令行端会直接ctrl+c 中断命令 (Issue #2517) |

See #2296 (comment)
