### ISSUE TITLE
使用clear命令后，输出无法全部清空

### ISSUE THREAD

**Issue by oocococo** [kingToolbox/WindTerm#257]
版本 ：2.2.0 Prerelease 4
环境：通过ssh连接到archlinux
当日志较长时，使用clear命令后，窗口内会残余半个窗口的日志。
![image](https://user-images.githubusercontent.com/39755142/141115859-a38dba0d-adf5-4805-b502-c1d30b550b62.png)

如图所示，右侧滚动条没有清零，当往上滚屏，依然有之前的日志。

**Comment by kingToolbox** [comment]
The command `Clear` will only clear the current screen, not the scroll history. Please try to use the right-click menu item `Clear All` to clear all output.

**Comment by mzky** [comment]
use  ctl+shift+l
