### ISSUE TITLE
怎么删除会话中的SSH链接？

### ISSUE THREAD

**Issue by junyangfan** [kingToolbox/WindTerm#2573]
版本：2.6.1
设备：Mac

怎么删除会话中的SSH链接？
![1](https://github.com/user-attachments/assets/fff72d11-8016-45e0-8a1c-6568b6c4d32e)

**Comment by 107295472** [comment]
还有其他好用的工具吗

**Comment by junyangfan** [comment]
> 还有其他好用的工具吗

tabby 也挺好用的

**Comment by 107295472** [comment]
那不是网页的吗，不流畅

**Comment by MzoroHaHa** [comment]
bitvise, 操作习惯差别有点大，但挺好用的。会话文件好保存

**Comment by junyangfan** [comment]
> 那不是网页的吗，不流畅

哪个是网页版？软件:https://github.com/Eugeny/tabby/tree/master

**Comment by junyangfan** [comment]
> bitvise, 操作习惯差别有点大，但挺好用的。会话文件好保存

用这个挺不错的，但是没找到删除会话的地方

**Comment by GodRuiAn** [comment]
<img width="352" alt="image" src="https://github.com/user-attachments/assets/461b993f-bf4e-438e-b890-cced983cac24">
你右键菜单没有删除？
