### ISSUE TITLE
Feature Requests：“Duplicate tab/view” Mouse Action

### ISSUE THREAD

**Issue by tinyhare** [kingToolbox/WindTerm#258]
Version 2.2.0 Prerelease 4
I want to Duplicate a tab by Double click it,  like other terminal do, So need a new action, thankyou.
![image](https://user-images.githubusercontent.com/6851513/141309439-67be1b5d-eeeb-4598-a789-a1112e1d1d2d.png)

**Comment by kingToolbox** [comment]
Thank you, it's done. You will get this feature in the `WindTerm_2.2.0` version, which will be released this week. 

In addition, I am a little curious, which client provides such a feature, I hope to study it.

**Comment by tinyhare** [comment]
> which client provides such a feature

Xshell

**Comment by kingToolbox** [comment]
The new [WindTerm_2.2.0_Prerelease_5](https://github.com/kingToolbox/WindTerm/releases/tag/2.2-prerelease) version has been released, and this feature has also been completed, please download and check it, thank you.

**Comment by tinyhare** [comment]
Perfect！ thank you.
