### ISSUE TITLE
需要更多主题配色，比如 solarized dark

### ISSUE THREAD

**Issue by snowdream** [kingToolbox/WindTerm#2595]
[WindTerm](https://github.com/kingToolbox/WindTerm)功能非常强大，还免费使用。👍👍👍

需要更多主题配色，比如 solarized dark

https://github.com/altercation/solarized

<img width="700" alt="image" src="https://github.com/user-attachments/assets/92fd60d0-b4c3-4b83-88a5-f67876df33b6">

**Comment by fullwaywang** [comment]
https://github.com/fullwaywang/windterm-solarized-dark-theme.git
Enjoy!
