### ISSUE TITLE
SSH port forwarding issue

### ISSUE THREAD

**Issue by mrcancer91** [kingToolbox/WindTerm#26]
Hi, 
I'm using a Raspberry with Squid proxy server (172.172.1.111:3128), I want to open SSH connections using the port forwarding. 
The SSH will be configured socks5 proxy via localhost:1080

When I turned on the PC, a SSH connection with the Rasp is established with **dynamic** port forwarding, listening on 1080.

The problem is, everything is normal using PuTTY, but same configuration for WindTerm doesn't work as expected!
Below is the configuration of WindTerm:
![image](https://user-images.githubusercontent.com/4757156/100960450-e164c480-3552-11eb-9103-56be07d64693.png)

And here is the equivalent config of PuTTY:
![image](https://user-images.githubusercontent.com/4757156/100960635-43252e80-3553-11eb-818a-392ceebb01ec.png)

Thanks!

**Comment by mrcancer91** [comment]
Sorry, 
The issue comes from my wrong understanding. 
I just removed the check mark "Perform DNS Lookup with proxy" and SSH connections are established well as expected. 
Please ignore this issue. 

Thanks again for your great efforts on this software!

**Comment by YuLei-Note** [comment]
Hi Admin,

I'm using Windterm v2.6.1
I want to set a ssh port forwarding on session.
But seems there is no this object under session setting.
![image](https://github.com/user-attachments/assets/e25219ab-70a0-4522-8ed4-324230ba3e0c)

how to move on?

**Comment by kingToolbox** [comment]
[WindTerm_2.7.0_Prerelease_3](https://github.com/kingToolbox/WindTerm/releases/tag/2.7-prerelease-3) fixes the bug where dynamic port forwarding couldn't proxy DNS lookups. Please download and try it. Thank you.
