### ISSUE TITLE
x11 application clipboard

### ISSUE THREAD

**Issue by zzhzero** [kingToolbox/WindTerm#261]
Like:
![image](https://user-images.githubusercontent.com/26578967/141715411-4f452eb0-e66c-48ae-ad03-3b98fdbcd8be.png)
This is a great option

**Comment by kingToolbox** [comment]
Thank you. In the `WindTerm_2.4.0` version, `Windows X11 Server` will be greatly improved：

- Replace `XMing.exe` with `vcxsrv.exe` for better display and functions.
- Support custom `vcxsrv.exe` command line parameters.

The second improvement is what you want:

```
VcXsrv Device Dependent Usage:
-[no]clipboard
      Enable [disable] the clipboard integration. Default is enabled.

-[no]clipboardprimary
          [Do not] map the PRIMARY selection to the windows clipboard.
          The CLIPBOARD selection is always mapped if -clipboard is enabled.
          Default is mapped.
```
You can refer to [vcxsrv help](https://sourceforge.net/p/vcxsrv/wiki/Using%20VcXsrv%20Windows%20X%20Server/) for specific `vcxsrv.exe` parameters. And for some parameters, some graphical interfaces will be provided for more convenient use.

**Comment by zzhzero** [comment]
Thank you. I'm looking forward to the new version

**Comment by kingToolbox** [comment]
I forgot to mention that the new `WindTerm_2.4.0` is expected to be released in December or January next year.

**Comment by zzhzero** [comment]
> I forgot to mention that the new `WindTerm_2.4.0` is expected to be released in December or January next year.

I found vcxsrv in the latest version. How can I set it?

**Comment by kingToolbox** [comment]
Hello, sometimes it is difficult to keep up with the development plan. Sorry for the waitting.

You can set the configuration you want in the `Settings` dialog, `Menu - Preferences - Settings - X Server`. 
![image](https://user-images.githubusercontent.com/51009775/163319335-647ae7b6-b795-4764-994d-68b7bbd4658c.png)

If there are parameters that do not provide interface settings, you can fill them in the `Additional Parameters` lineedit. I believe it should meet all your needs. :smile:

**Comment by zzhzero** [comment]
It works very well, thank you.
