### ISSUE TITLE
2.1.0版本的ZModem功能在ubuntu 21.10版本中不能用

### ISSUE THREAD

**Issue by zhangyuebj** [kingToolbox/WindTerm#268]
【WindTerm版本】：2.1.0
【操作系统】：Ubuntu 21.10
【问题描述】：
无法使用Zmodem方式发送和接收文件，在windows下使用2.2.0 Prerelease 3版本可以正常发送和接收文件。

**Comment by kingToolbox** [comment]
I do not currently have `Ubuntu 21.10`, I will investigate this issue later, and any progress will be updated here, please stay tuned, thank you.

**Comment by kingToolbox** [comment]
I installed `Ubuntu 21.10` and tested using `sz` to send files to another system and `rz` to receive files from another system without any problems. Can you give a more detailed description, such as operation steps, the phenomenon of error, the messages of error, etc.

**Comment by zhangyuebj** [comment]
非常感谢！我这边已经解决了。解决过程如下：
1、我仔细看了下，错误的时候提示“进程/venders/lrzsz/rz启动失败。”。
2、我手动执行venders/lrzsz/rz命令，提示“error while loading shared libraries: libnsl.so.1: cannot open shared object file: No such file or directory”
3、安装libnsl库后，再次使用WindTerm执行rz命令，成功了。

所以是缺少libnsl.so.1库导致的，非常感谢。

建议：
解压后，好像在某些linux（ubuntu、fedora）系统中，venders/lrzsz目录中的rz和sz命令无执行权限。请关注下这个问题，谢谢。

**Comment by kingToolbox** [comment]
I am glad that your problem has been resolved. But I'm afraid there is nothing I can do about the `privileges` you mentioned. After all, `WindTerm` is a portable software, so it can only be left to the user to solve it by himself. :disappointed:

**Comment by zhangyuebj** [comment]
好的，谢谢开发如此好用的软件！
