### ISSUE TITLE
2.2.0 Prerelease 3鼠标停留在标签上切换能不能去掉这个功能或者设置

### ISSUE THREAD

**Issue by EverythingGoesWithTheFlow** [kingToolbox/WindTerm#269]
使用鼠标时经常会自动切换标签

**Comment by funkpopo** [comment]
左上角 "会话" - "首选项" - "设置" - "标签" - "悬停后激活选项卡"，将时间设定为你所需要的时间即可。
Top left side, choose "Session" - "Preferences" - "Settings" - "Tabs" - "Activate the tab after hovering", set the activate time as you wish.

**Comment by funkpopo** [comment]
> 使用鼠标时经常会自动切换标签

左上角 "会话" - "首选项" - "设置" - "标签" - "悬停后激活选项卡"，将时间设定为你所需要的时间即可。
Top left side, choose "Session" - "Preferences" - "Settings" - "Tabs" - "Activate the tab after hovering", set the activate time as you wish.

**Comment by kingToolbox** [comment]
Please set it as mentioned by @funkpopo , and thank you, funkpopo.

**Comment by EverythingGoesWithTheFlow** [comment]
> > 使用鼠标时经常会自动切换标签
> 
> 左上角 "会话" - "首选项" - "设置" - "标签" - "悬停后激活选项卡"，将时间设定为你所需要的时间即可。左上侧，选择"会话" - "首选项" - "设置" - "选项卡" - "悬停后激活选项卡"，按您的意愿设置激活时间。

已经设置谢谢

**Comment by dingwei0022** [comment]
能够关闭标签页预览功能，把鼠标放到标签页上面就显示预览了
