### ISSUE TITLE
Hope support rz and sz

### ISSUE THREAD

**Issue by lishuhuakai** [kingToolbox/WindTerm#27]

**Comment by kingToolbox** [comment]
This feature is already in the todo list. But because the related libraries are mostly under GPL license, I have to implement it myself. So it should be completed in the first quarter of next year.

**Comment by kingToolbox** [comment]
The the new version [2.1.0_prerelease_2](https://github.com/kingToolbox/WindTerm/releases/tag/2.1) has been released and supports ZModem well. You can download and check, thank you!

**Comment by lishuhuakai** [comment]
thanks !
