### ISSUE TITLE
Cant input square brackets ("[" "]") in terminal in prerelease 4 and 5

### ISSUE THREAD

**Issue by pedromaribeiro98** [kingToolbox/WindTerm#271]

**Comment by kingToolbox** [comment]
Sorry, I cannot reproduce this bug in `SSH`, `Cmd`, `Powershell` and etc. Can you give a more detailed description, such as the remote system version, and in what scenarios the `[` and `]` keys cannot be inputed. Thank you.

**Comment by pedromaribeiro98** [comment]
I'm accessing a Centos 7 machine. I'm using the PT keyboard layout, where the key combination is ´alt gr´+´8´ or  ´alt gr´+´9´. When I try to input them, I just don't get nothing on the console.

**Comment by kingToolbox** [comment]
Thank you, I will investigate this issue. Because I usually just use the us keyboard layout, so there may be problems in handling the `alt gr` key. I will update any progress here, please stay tuned.

**Comment by pedromaribeiro98** [comment]
Btw in the prerelease 2 it worked fine. only when i upgraded to the prerelease 4 and 5 i started to get this problem

**Comment by kingToolbox** [comment]
Thank you very much for providing such an important clue. In this way, it is obvious that the following changes should have caused the problem.

> Changes in Version 2.2.0 Prerelease 4
>
> [TERM] Add and modify hundreds of pre-defined key values under `Normal keypad mode` and `Application keypad mode` of `vt52`, `vt100`, `vt102`, `vt220`, `vt340`, `vt420`, `vt520`, `xterm` and `xterm-256color`. 

I will find out the exact cause and fix it as soon as possible. Once fixed, a `bugfix` version will be released.

**Comment by kingToolbox** [comment]
I am happy to inform you that [WindTerm_2.2.1](https://github.com/kingToolbox/WindTerm/releases/2.2) has been released and this issue has been fixed, please download and check it, thank you.

**Comment by pedromaribeiro98** [comment]
Hi.
Yes, it's fixed.
Thank you so much.
Continue with the good work that you've put into this project. Is awesome 😁
