### ISSUE TITLE
Select-to-copy not working

### ISSUE THREAD

**Issue by PnPH** [kingToolbox/WindTerm#29]
Hi,
I've been playing around with Windterm and it's really promising, it checks almost all the features I need.

I noticed that the select-to-copy is featured in the readme but it's not working, do I need to enable it somewhere?

Thank you

**Comment by kingToolbox** [comment]
May I ask which version of WindTerm you are using? If you are using the version 1.8 of windows, then you need to manually set "text.autoCopySelection" to true to enable it. As I noted in the changelog:

> Warning: Select-to-copy is disabled by default on Windows. Set "text.autoCopySelection" in "WindTerm-Install-Path/global/wind.config" to true to enable it.

If you are using the prerelease version 1.9 of Linux, then this will be a bug and I will fix it in the next version.

**Comment by PnPH** [comment]
I'm really sorry I completly missed that warning, I'm on Windows ver. 1.8 and after enabling that it's working fine.

Sorry for wasting your time.

**Comment by kingToolbox** [comment]
It's ok, I am very glad that your problem has been resolved. If you have any questions or needs, just ask. :smiley:
