### ISSUE TITLE
in windows no-response

### ISSUE THREAD

**Issue by vhuang0501** [kingToolbox/WindTerm#290]
now open the windterm, any operation will be like this, I don’t know how to cause it, and I don’t know how to restore it. 
![1637731542](https://user-images.githubusercontent.com/57122114/143179939-ad162ba4-bc41-4cea-89bb-4ae73789e6d4.jpg)
![1637731542(1)](https://user-images.githubusercontent.com/57122114/143179948-fd43ad23-60df-4ecb-a878-3365cc59a1b7.jpg)

In addition, I mentioned a question about folders before, I hope there are sub-folders, that is, multi-level

**Comment by vhuang0501** [comment]
I’m not sure if it’s the issue, but now other software doesn’t show this

**Comment by kingToolbox** [comment]
If you want, you can zip the `WindTerm_install_path/profiles/default.v10/global/reopen.history` and `WindTerm_install_path/profiles/default.v10/terminal/reopen.history` files and paste the zipped file into your comment to upload. I will analyze these two files to see if I can find out the reason.

In addition, you can directly delete these two files to resume normal startup. These two files only contain the uuid of the tabs, the size of the windows and widgets, and do not contain any information about your sessions.

**Comment by vhuang0501** [comment]
I tried to delete `reopen.history` to no avail, but I found that there would be no such problem when opened in `cmd`, and the problem still exists when I double-click to open it.

**Comment by kingToolbox** [comment]
Sorry for the late reply. I just returned from vacation.

The new [Windterm_2.3.0_Prerelease_1](https://github.com/kingToolbox/WindTerm/releases/tag/2.3-prerelease) version has been released, please download and check it. If there are still bugs, please let me know, thank you.
