### ISSUE TITLE
How to apply root privileges to Filer?

### ISSUE THREAD

**Issue by SekiBetu** [kingToolbox/WindTerm#291]
My server forbids the root user to log in, so I log in with another account first, then switch to the root user to use it, resulting in Filer not being able to access the root path

**Comment by SekiBetu** [comment]
![image](https://user-images.githubusercontent.com/38283893/143267675-b4a03aaa-01b4-4ab1-b066-c3b9b211200f.png)
winscp provided a setting that can apply commands after login such as 'sudo -s', so i can access the root path after login

**Comment by SekiBetu** [comment]
or maybe provide a terminal to directly apply commands to the Filer window?

**Comment by kingToolbox** [comment]
I really haven't thought too much about this. I need time to think about it. But as far as I know, the `SFtp` protocol may not provide a way to grant  privileges, and I will update it if there is any progress. I will update this if there is any progress.

**Comment by SekiBetu** [comment]
![image](https://user-images.githubusercontent.com/38283893/143320002-0f65a9b4-fe40-46a4-a0df-4232e7afb181.png)
i don't know how WinSCP did it, but i just added `username ALL=(ALL) NOPASSWD:ALL` into the `/etc/sudoers` file, then after i connected to my server, i became root user, i can then access the /root path.

**Comment by kingToolbox** [comment]
You can refer to [this comment](https://github.com/pkg/sftp/issues/12#issuecomment-612186979), especially `modifying /etc/sshd_config` is worth a try. You don't need to create a new `subsystem`, just modify `sftp` directly, for example：

> Subsystem sftp sudo -n true && sudo -n /usr/lib/openssh/sftp-server || /usr/lib/openssh/sftp-server

If this method is workable, please let me know, thank you. For running the remote `sftp` through `exec` instead of `subsystem`, I am not sure if it is workable. When I have time, I will try it. This is also the method used by `WinScp`. If there is progress, I will update here.

**Comment by SekiBetu** [comment]
> You can refer to [this comment](https://github.com/pkg/sftp/issues/12#issuecomment-612186979), especially `modifying /etc/sshd_config` is worth a try. You don't need to create a new `subsystem`, just modify `sftp` directly, for example：
> 
> > Subsystem sftp sudo -n true && sudo -n /usr/lib/openssh/sftp-server || /usr/lib/openssh/sftp-server
> 
> If this method is workable, please let me know, thank you. For running the remote `sftp` through `exec` instead of `subsystem`, I am not sure if it is workable. When I have time, I will try it. This is also the method used by `WinScp`. If there is progress, I will update here.

yes, it works!

![image](https://user-images.githubusercontent.com/38283893/143412242-c356d211-40b2-4e58-babc-cf7525de17fd.png)
![image](https://user-images.githubusercontent.com/38283893/143412273-fa403dda-c3a5-47f3-a288-0b78de365e83.png)

**Comment by kingToolbox** [comment]
Good news. I think this should be the best solution at the moment. If this is workable, I don't think there is any need to try `exec` method, because it may introduce new risks. After all, it does not comply with the `SFtp` protocol, what do you think?

**Comment by SekiBetu** [comment]
Yeah, I guess that's the best way to go for now

**Comment by kingToolbox** [comment]
I'm glad we thought the same. If it is indeed necessary in the future, let's try the `exec` solution again. Now that this issue has been resolved, I will close it. Welcome to continue submitting new feature requests and bugs, thank you.
