### ISSUE TITLE
Serial ls print

### ISSUE THREAD

**Issue by yaronzz** [kingToolbox/WindTerm#292]
## WindTerm
![image](https://user-images.githubusercontent.com/15530958/143349452-bb93f68e-3e7c-4af4-9225-f8fd58e377d6.png)

## SecureCRT
![image](https://user-images.githubusercontent.com/15530958/143350157-b58031e6-bee1-49be-aa9d-76d0ed357828.png)

## WindTerm Settings
![image](https://user-images.githubusercontent.com/15530958/143350845-a5f43e88-f783-4886-b485-e57a7e36e396.png)

**Comment by kingToolbox** [comment]
This should be that the received data is not parsed correctly. Can you collect the debug log for me for further analysis, if possible, the steps are as follows:

- Open your session.
- Check the menu item `Menubar - Mode (7) - Debug Mode` before you excute `ls`.
- Excute `ls`.
- Uncheck the menu item `Menubar - Mode (7) - Debug Mode`.
- Click the menu item `Right click menu - Log - Open Log Folder`.
- Open the folder `debug` and paste your log file in your comment here. You can zip it before upload.

The log content is in plain text and will not contain any private information. You can use any editor to view it. Thank you.

**Comment by yaronzz** [comment]
## LOG 2021-11-25_14.41.49:
[WindTerm-Serial ls print #292.zip](https://github.com/kingToolbox/WindTerm/files/7600766/WindTerm-Serial.ls.print.292.zip)

**Comment by kingToolbox** [comment]
Thank you for providing `log`. I have analyzed it. It is true that there is a problem when parsing the received data, but the specific cause of the error is still being found. It is expected that this issue will be fixed in `WindTerm_2.3.0_Prerelease_1` version and released in early December. Please stay tuned, thank you.

**Comment by kingToolbox** [comment]
I am happy to inform you that [WindTerm_2.2.2](https://github.com/kingToolbox/WindTerm/releases/2.2) has been released and this issue has been fixed, please download and check it, thank you.

**Comment by yaronzz** [comment]
> I am happy to inform you that [WindTerm_2.2.2](https://github.com/kingToolbox/WindTerm/releases/2.2) has been released and this issue has been fixed, please download and check it, thank you.

fixed. thanks.👍
