### ISSUE TITLE
Screen Flickering starting nano text editor. Skip intro screen of vim and ne

### ISSUE THREAD

**Issue by lorenzo-patane** [kingToolbox/WindTerm#3]
When i start nano the terminal start flickering but if i use arrow button to move buttons the screen gets fixed.

To replicate bug just start nano text editor

**Comment by lorenzo-patane** [comment]
EDIT: The program skip the intro screen of vim and ne (nice editor)
![Screenshot_2](https://user-images.githubusercontent.com/43727434/73491511-16dad780-43af-11ea-8c4a-10ea9603cd95.png)

**Comment by kingToolbox** [comment]
Thank you. The bug of nano is fixing, a new version will be released within two days.

For the second issue, I use different window size for the main screen and the alt screen. When start the alt screen, for example start vim or ne, a new window size negotiation will be sent to server, which lead the server wipe the intro screen.

This has no effect on vim or ne, but Windterm will consider to improve it in short future.

**Comment by kingToolbox** [comment]
The new version is still under preparing, If you need to avoid this issue now, you can just open the session's property dialog and check the SSH - Window - Adjust the window columns.

**Comment by kingToolbox** [comment]
This has been fixed in version 0.92.
