### ISSUE TITLE
2.2.2 的MAC版本什么时候能提供下载

### ISSUE THREAD

**Issue by yuebo52** [kingToolbox/WindTerm#306]
有地方能找到吗？

**Comment by kingToolbox** [comment]
Today `Qt` will release `Qt 6.2.2`, and then the `WindTerm_2.3.0_Prerelease_1_Mac_Portable` version will start compiling, which is a univeral app and can run on the `M1` mac and `x86` mac. For performance reasons, `WindTerm` uses a lot of x86 `SSE/SSE2/SSE3` instructions, so it must be changed to the Arm `Neon` instructions, which will have a lot of work. It is expected that the `WindTerm_2.3.0_Prerelease_1_Mac_Portable` version will be released this month. You are welcome to download and use it at that time. Thank you.

**Comment by yuebo52** [comment]
谢谢。

**Comment by kingToolbox** [comment]
The MacOS version of WindTerm has been released, please download and check [WindTerm_2.3.0_Prerelease_2_MacOS_Portable](https://github.com/kingToolbox/WindTerm/releases/2.3-prerelease). If you encounter any problems, please let me know. Thank you.
