### ISSUE TITLE
菜单栏被隐藏后怎么让它再显示出来？

### ISSUE THREAD

**Issue by darrenluo1993** [kingToolbox/WindTerm#309]
菜单栏被隐藏后怎么让它再显示出来？

**Comment by u-Sir** [comment]
alt+w然后alt+m

**Comment by darrenluo1993** [comment]
> alt+w然后alt+m

非常感谢，我刚刚通过查看https://kingtoolbox.github.io/2021/06/28/ui_layout/页面上的内容也发现了显示/隐藏菜单栏的快捷键。
