### ISSUE TITLE
能不能提供一个quick connection panel,已方便建立一些临时的连接

### ISSUE THREAD

**Issue by jacquen** [kingToolbox/WindTerm#315]
能不能提供一个quick connection panel,已方便建立一些临时的连接
类似secureCRT的这个窗口
![image](https://user-images.githubusercontent.com/2107576/144202204-1496fcec-2bab-4246-9b06-d6021d5824f9.png)

**Comment by kingToolbox** [comment]
Thank you. The `Address Bar` is designed to create temporary connections. It is also very convenient to use. You can refer to [AddressBar / Non-existing Host](https://kingtoolbox.github.io/2020/06/20/addressbar-non-existing-host/) to learn more. I think it should be what you want.

**Comment by jacquen** [comment]
thanks very much
