### ISSUE TITLE
我并没有找到传输文件的按钮

### ISSUE THREAD

**Issue by shuncon** [kingToolbox/WindTerm#317]
我并没找到这个按钮。请问如何打开传输文件资源管理器
![image](https://user-images.githubusercontent.com/25509201/144203245-e9ea38bd-3b1c-43e9-b598-9a25cae1a9b3.png)
传输二进制这个选项太无语了
![image](https://user-images.githubusercontent.com/25509201/144203291-0280f00e-bfe6-47da-a288-bf683a345a93.png)

**Comment by shuncon** [comment]
版本是2.2.2
![image](https://user-images.githubusercontent.com/25509201/144203590-cdd47b0a-ab0b-42c8-8d84-b150f6abf415.png)

**Comment by kingToolbox** [comment]
Sorry for the late reply. I just returned from vacation.

There are related menu items in the context menu. You can read [XModem](https://kingtoolbox.github.io/2021/05/27/modem-xmodem/), [YModem](https://kingtoolbox.github.io/2021/05/27/modem-ymodem/) and [ZModem](https://kingtoolbox.github.io/2021/05/27/modem-zmodem/) to learn more. In addition, you only need to enter `sz filename` and `rz` to automatically trigger the transmission of `ZModem`, which is more convenient.
