### ISSUE TITLE
2.2.2版本锁屏密码是什么

### ISSUE THREAD

**Issue by shuncon** [kingToolbox/WindTerm#319]
锁屏密码是什么
输入为空也是错误
![image](https://user-images.githubusercontent.com/25509201/144206897-080abf49-6e61-4c8f-aad4-f6d53f517f62.png)

**Comment by Fcscanf** [comment]
@shuncon 大佬，所以怎么看这个锁屏密码呢

**Comment by kingToolbox** [comment]
The default master password is an empty string. The master password can only be set and cannot be viewed. Therefore, please keep it safe, otherwise all automatic login information will not be decrypted and the automatic login will fail.
