### ISSUE TITLE
windows下使用windedit作为默认编辑器无法正确打开

### ISSUE THREAD

**Issue by ender049** [kingToolbox/WindTerm#327]
在文件管理器中打开，选择使用默认编辑器打开，选择windedit
打开文件为空白文件，没有正确打开相应文件。
另外，设置完选择使用默认编辑器打开后，没有找到再次设置的地方，改不了了

**Comment by ender049** [comment]
删除 \profiles\default.v10\user.config 里的"filer.defaultEditor"后，可以再次选择了
选择notepad++没有问题

**Comment by kingToolbox** [comment]
Sorry, `WindEdit` still has many functions that have not been completed. For example, it does not support command-line parameters. This is why you cannot use `WindEdit` to open files. I will improve `WindEdit` next year, but now my focus is still on `WindTerm`, and there are still too many exciting features that need to be completed.

I am not sure which version of `WindEdit` you are using. But in the [WindEdit 1.0.0 Prerelease 1](https://github.com/kingToolbox/WindEdit/releases/tag/1.0-prerelease) version, `WindEdit` and `WindTerm` are already combined into one tool, and after you double-click the file in the `Filer`, it will automatically be opened directly in `WindEdit`, without the need to set `the default editor`. This will also be the future form of `WindTerm`.

In addition, you can click the `More` button in the toolbar of the `Filer` Pane, which has the **three-dot** icon, and execute `Set default editor...` from the pop-up menu without manually modifying the configuration file. :smile:

**Comment by ender049** [comment]
> I am not sure which version of `WindEdit` you are using. But in the [WindEdit 1.0.0 Prerelease 1](https://github.com/kingToolbox/WindEdit/releases/tag/1.0-prerelease) version, `WindEdit` and `WindTerm` are already combined into one tool, and after you double-click the file in the `Filer`, it will automatically be opened directly in `WindEdit`, without the need to set `the default editor`. This will also be the future form of `WindTerm`.

windterm 2.2.2  win10 windedit 1.0.0 prerelease 1
try it again ,still not open directly in windedit

> In addition, you can click the `More` button in the toolbar of the `Filer` Pane, which has the **three-dot** icon, and execute `Set default editor...` from the pop-up menu without manually modifying the configuration file. 😄

finded  it, annn
