### ISSUE TITLE
希望能够增加登录脚本功能

### ISSUE THREAD

**Issue by cnkmmk** [kingToolbox/WindTerm#328]
如同xshell的这个功能
![https://i.imgur.com/TnTInAh.png](https://i.imgur.com/TnTInAh.png)

**Comment by kingToolbox** [comment]
Duplicate of #312

Features such as `macros`, `triggers`, `events`, `notifications`, `plugins`, `scripts` and so on will be added in subsequent versions. I will update the progress here, please stay tuned, thank you.
