### ISSUE TITLE
Some more ideas to consider

### ISSUE THREAD

**Issue by cadayton** [kingToolbox/WindTerm#33]
When pulling in my PuTTy sessions (or any set of sessions), there are close to over 537 potential sessions to choose.  It is short of a pain to get to session 537.  Consider adding a filter option to the right-click menu, so a smaller subset of sessions appear.

Really liking what I've experienced so far.

**Comment by kingToolbox** [comment]
Thank you. What you said is already in my plan. However, there are several ways to quickly open it.

- In the session pane, there is a filter input box above the session tree, just input 537 to filter and press enter to open it.
- Press Alt+D to goto the address bar or just click the address bar, then you can input 537 and filter and press enter to open it.
- Press Alt+O to show the command palette, then you can input 537 to filter and press enter to open it.

WindTerm has been tested to manage and filter more than 100,000 sessions, so don't worry about the performance.

**Comment by kingToolbox** [comment]
Of course, it is also very good to use groups to manage a large number of sessions. You only need to set the group name of the session in the property box, and the session will be classified into the corresponding group. You can try.

For sessions in the same group, you can set them to use the same color icon or the same shape icon to better distinguish between different groups.

**Comment by cadayton** [comment]
Great and Thank you.
Sorry, I didn't notice the search filter bar in the session pane. This works perfect for me.

Craig Dayton
cadayton@protonmail.com
360-466-8778
https://keybase.io/cadayton/chat

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by cadayton** [comment]
Oh wow.  Sorry, I didn't notice the search filter bar in the session pane or the grouping potential.  With this in place, I'm going to close the request.  Thanks Again.
