### ISSUE TITLE
Small Tip for using private key exported from .ppk files

### ISSUE THREAD

**Issue by future93** [kingToolbox/WindTerm#333]
To make it short, if you want to export a plain text private key file from your .ppk file with PuTTY key generator, remember to use the **"Export OpenSSH key (force new file format)"** option.

If the author can leave a notice about this (and WindTerm's currently not supporting .ppk format) around the "import private key" option, I think this may help some users to save their time on wondering why their public key login is always failing.

**Comment by kingToolbox** [comment]
Sorry, it was my negligence. I will add support for `.ppk` soon, so that there is no need to distinguish between `OpenSSH Key` and `Putty Key`, and it will be more convenient. Thank you.
