### ISSUE TITLE
Suspend processing issues for a period of time

### ISSUE THREAD

**Issue by kingToolbox** [kingToolbox/WindTerm#334]
Hello, everyone, thank you all for your love and support for `WindTerm`. I will take the winter vacation and suspend the handling of the issues for a period of time, because I won’t have internet during that time. But I will continue to complete some features, bugs and especially **MacOS universal version** so that I can release the WindTerm v2.3.0 soon after I come back.

If you have any feature request or issue, please feel free to submit it. I will deal with it when I come back, thank you.

I wish you all the best for coming days. Let's meet again in December.

**Comment by funkpopo** [comment]
Thanks for your excellent work, hope you enjoy your vacation!

**Comment by DreamCreat** [comment]
you best

**Comment by kingToolbox** [comment]
Thank you all, I am back. This vacation is longer than I expected, and there are too many features and issues to be done. I hope that in the new year, I can provide you with a better terminal. Let's move on. :smile:
