### ISSUE TITLE
常用命令列表功能

### ISSUE THREAD

**Issue by dongasai** [kingToolbox/WindTerm#339]
常用命令列表，或者命令收藏，目前的大纲有点鸡肋

**Comment by bug65536** [comment]
> 常用命令列表，或者命令收藏，目前的大纲有点鸡肋

同意，就像xshell中的快速命令按钮

**Comment by dongasai** [comment]
> 最下面一行 不是有快速命令么？

大纲？

**Comment by mzky** [comment]
建议提问前先看下官方说明：
![image](https://user-images.githubusercontent.com/13345233/144954939-b305459a-a979-496e-b168-2649457cc2d7.png)
![image](https://user-images.githubusercontent.com/13345233/144955035-5e82529f-97af-4120-8eb6-60c6a81ff3c2.png)
详细说明：
https://kingtoolbox.github.io/2020/08/22/quickbar/

**Comment by dongasai** [comment]
非常棒
