### ISSUE TITLE
中文乱码

### ISSUE THREAD

**Issue by Asura88** [kingToolbox/WindTerm#347]
中文乱码

**Comment by funkpopo** [comment]
版本号、系统版本、截图。
不要再用这种过于简单的描述提issue

**Comment by bestv5** [comment]
> 中文乱码

你这有点狠了，就说乱码，其他啥信息也不提供，全靠让人猜 <g-emoji alias="smile" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f604.png" class="emoji">😄</g-emoji>

**Comment by Asura88** [comment]
操作系统：Mac OS 12.0.1

软件版本：2.1.0

终端查询文件，文件名是中文就乱码

![image](https://user-images.githubusercontent.com/25000885/146577852-58c927c9-cdf4-4bbb-ae4c-653fe41cbdce.png)

**Comment by bestv5** [comment]
这个是你本地的终端吧，你可以在session配置里修改下编码看看

**Comment by shvc** [comment]
Macos 11.6
WindTerm 2.3.0 
Chinese filename garbled(file contents OK)
<img width="840" alt="winterm-garbled" src="https://user-images.githubusercontent.com/12904584/152291529-9f620648-d286-4821-ad04-12e053561c73.png">

**Comment by shvc** [comment]
workaround
```
echo 'export LANG=zh_CN.UTF-8' >> ~/.zshrc
echo 'export LANG=zh_CN.UTF-8' >> ~/.bashrc
```

@Asura88  临时解决办法配置下LANG环境变量

**Comment by bestv5** [comment]
按下面的方法试试看。

> 在终端下输入
vi \~/.zshrc
或者使用其他你喜欢的编辑器编辑~/.zshrc 在文件内容末端添加：
export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8
接着重启一下终端，或者输入
source ~/.zshrc
一切就OK了。

**Comment by XRSec** [comment]
dpkg-config 啥来着

**Comment by XRSec** [comment]
应该是服务端的问题，当然如果普通终端不乱码，那问题就在你们软件上了

**Comment by shvc** [comment]
> dpkg-config 啥来着

大哥, Mac OS哪来的dpkg!

**Comment by yeahthon** [comment]
您的邮件已收悉，谢谢！

**Comment by XRSec** [comment]
@shvc 你是憨，我都说了应该是服务器问题，光设置环境变量有啥用，有没有装字符集字体还另说

**Comment by shvc** [comment]
> @shvc 你是憨，我都说了应该是服务器问题，光设置环境变量有啥用，有没有装字符集字体还另说

@XRSec  你才憨, 人家这是本地终端,本地本地文件名乱码, 哪来的服务器?
