### ISSUE TITLE
界面样式错误

### ISSUE THREAD

**Issue by xtsteven** [kingToolbox/WindTerm#348]
你好：

当电脑外接显示器时，由于外界显示器的分辨率和电脑自身显示器的分辨率的不同，造成界面样式错乱。

![微信截图_20211207171153](https://user-images.githubusercontent.com/33415855/145000714-7d1fec35-0a20-4d17-8f54-3d78b41b5c83.png)

而正常的样式，应该是下图这样的：
![微信截图2](https://user-images.githubusercontent.com/33415855/145000921-84a1ff6d-e597-416a-a3da-f6548ae6cd00.png)

**Comment by mzky** [comment]
> 你好：
> 
> 当电脑外接显示器时，由于外界显示器的分辨率和电脑自身显示器的分辨率的不同，造成界面样式错乱。
> 
> ![微信截图_20211207171153](https://user-images.githubusercontent.com/33415855/145000714-7d1fec35-0a20-4d17-8f54-3d78b41b5c83.png)
> 
> 而正常的样式，应该是下图这样的： ![微信截图2](https://user-images.githubusercontent.com/33415855/145000921-84a1ff6d-e597-416a-a3da-f6548ae6cd00.png)

试一下这个配置好不好使
![image](https://user-images.githubusercontent.com/13345233/145148240-2bbb3f9b-5d49-4ccf-8d71-2585a0d84e56.png)

**Comment by xtsteven** [comment]
> > 当电脑外接显示器时，由于外界显示器的分辨率和电脑自身显示器的分辨率的不同，造成界面样式错乱。
> 
> 试一下这个配置好不好使 ![image](https://user-images.githubusercontent.com/13345233/145148240-2bbb3f9b-5d49-4ccf-8d71-2585a0d84e56.png)

这个用的都是推荐值，改了还是一样，笔记本显示器是3K的，而外接显示器只有1080，是不是这个分辨率的问题。

**Comment by mzky** [comment]
估计是分辨率设置的太高了  这个好像不止这个工具有问题 别的工具也有这种情况

**Comment by xtsteven** [comment]
> 估计是分辨率设置的太高了 这个好像不止这个工具有问题 别的工具也有这种情况

希望是能修复的，这样就更完美了，我这边一直都是双屏的，这样贼难受

**Comment by mzky** [comment]
> > 估计是分辨率设置的太高了 这个好像不止这个工具有问题 别的工具也有这种情况
> 
> 希望是能修复的，这样就更完美了，我这边一直都是双屏的，这样贼难受

咱俩正好相反，我是一个显示器接两个主机，通过hdmi切换器切换显示，我的windows装了一个有意思的工具，可以模拟linux多桌面
![动画](https://user-images.githubusercontent.com/13345233/145177414-80c37c8c-bacc-4c2b-b5e8-7f1409f3b244.gif)

**Comment by kingToolbox** [comment]
@funkpopo Thank you for your help.

This issue should have been fixed after using the new `Qt 5.15.2`. Please download the latest version [WindTerm_2.3.0_Prerelease_2](https://github.com/kingToolbox/WindTerm/releases/2.3-prerelease) and check it, thank you.

**Comment by xtsteven** [comment]
> @funkpopo Thank you for your help.
> 
> This issue should have been fixed after using the new `Qt 5.15.2`. Please download the latest version [WindTerm_2.3.0_Prerelease_2](https://github.com/kingToolbox/WindTerm/releases/2.3-prerelease) and check it, thank you.

**_V2.3.0_**

![微信截图_20220124100545](https://user-images.githubusercontent.com/33415855/150710838-032308d6-a8cd-48fd-b172-b2e8398c3900.png)


切换到高分辨率的屏幕上后
![微信截图_20220124100632](https://user-images.githubusercontent.com/33415855/150710895-7e450a92-13c8-4377-89f2-d374d50c3041.png)

**Comment by kingToolbox** [comment]
I am happy to inform you that [WindTerm_2.3.1](https://github.com/kingToolbox/WindTerm/releases/tag/2.3.0) has been released and this issue has been fixed. Please download and check it. If there are still bugs, please let me know, thank you.
