### ISSUE TITLE
win10 卡死

### ISSUE THREAD

**Issue by RobotSong** [kingToolbox/WindTerm#355]
![1639063485(1)](https://user-images.githubusercontent.com/17350136/145424712-030b8c43-c490-49b1-b048-dc3d790d1f56.png)
2.2.2 版本 在 win10 下使用，一会后会卡死

**Comment by funkpopo** [comment]
Win10推荐使用的可执行程序为"WindTerm_Win10_Conpty.exe"。
尝试将该文件设置为"使用管理员身份启动"，如果无法修复，请暂时回退至v2.2.1。

**Comment by RobotSong** [comment]
"使用管理员身份启动" ，就可以

**Comment by kingToolbox** [comment]
@RobotSong 
The new [Windterm_2.3.0_Prerelease_1](https://github.com/kingToolbox/WindTerm/releases/tag/2.3-prerelease) version has been released, please download and check it. If there are still bugs, please let me know, thank you.
