### ISSUE TITLE
A question about ProxyCommand

### ISSUE THREAD

**Issue by magicknight** [kingToolbox/WindTerm#367]
Hi,
I have a ssh command like this using ProxyCommand, 
```bash
 ssh -i 'xxx/xxxx.pem' username1@xxx.xx -oProxyCommand="ssh -i 'xxx/xxx.pem' username2@xxx.xx -W %h:%p"
```
I tried to reproduce it on windterm using jump server, but didnt success. 
Just wondering how can I do it? Thank you!

**Comment by kingToolbox** [comment]
Sorry for the late reply. I just returned from vacation.

Has this issue been resolved? You can read [Jump Server](https://kingtoolbox.github.io/2021/03/11/proxy-jump-server/) to learn how to use `ProxyCommand` in WindTerm. If you still have questions, please let me know, thank you.
