### ISSUE TITLE
Ctrl+O default shortcut

### ISSUE THREAD

**Issue by Inokenty90** [kingToolbox/WindTerm#37]
By default Ctrl+O call in WindTerm open file in editor, but this shortcut used for save file in nano.

**Comment by kingToolbox** [comment]
Thank you, this bug also exists in Midnight Command and has been fixed. A new v1.9.2 will be released today, including some other fixes.

All keys in WindTerm are definable, and there is no hard-coded key in WindTerm. So you can easily fix it yourself, just open **WindTerm-Install-Path/global/wind.keymaps**, then search and delete:
```json
  { "keys": "<Ctrl+O>",
    "modes": "remote, widget",
    "when": "window.isScope('terminal.*')",
    "action": "Terminal.OpenSession"
  }
``` 
More detailed keyboard information can be referred to #13 . The later version will try to implement the configuration interface for keys.

**Comment by kingToolbox** [comment]
The new version 1.9.2 has been released, please download and check, thank you.

In addition to fixing the shortcut key Ctrl+O, also fixing the alt series shortcut keys in nano. But there are still a few keys that are used by WindTerm, such as Ctrl+N, Alt+T, Alt+F and so on. If you need these keys, please let me know or modify them in **WindTerm-Install-Path/global/wind.keymaps** yourself, thank you.

BTW, The Alt shortcut keys can be simulated by pressing **ESC** and the **key**, such as the shortcut key **Alt+F**, you can press **ESC** first, and then press **F**. They are the same thing.

**Comment by Inokenty90** [comment]
Thanks, everything working,

**Comment by kingToolbox** [comment]
I'm very glad to hear this. If you have other requests, please submit a new issue, thank you very much.
