### ISSUE TITLE
Please add one describe colume in Tunnels

### ISSUE THREAD

**Issue by telechow** [kingToolbox/WindTerm#373]
![image](https://user-images.githubusercontent.com/9656433/146304163-2e399b76-e717-4e4b-b186-df0b698e068a.png)

when you setting tunnels after a long time.

you maybe forgot ports means.

thx very much!

**Comment by kingToolbox** [comment]
Sorry for the late reply.

I am happy to inform you that [WindTerm_2.4.0_Prerelease_1](https://github.com/kingToolbox/WindTerm/releases/tag/2.4-prerelease) has been released and this feature has been implemented. Now you can not only give the `tunnel` a name, but also start, stop and manage independently running tunnels through the `Tunnels` button on the right side of the menu bar, which should be very convenient. In addition, the `tunnels` also supports `automatically open at startup`.

Please download and check it. If you have any questions, please let me know, thank you.
