### ISSUE TITLE
将 资源管理器 窗口设置为浮动，重启windterm后该设置失效

### ISSUE THREAD

**Issue by gh419** [kingToolbox/WindTerm#382]
OS:windows 10 21H2
WindTerm Version: 2.2.2

问题如上，不只是 资源管理器 窗口有该问题，文件管理器 等其他窗口也有该问题

**Comment by kingToolbox** [comment]
Sorry for the late reply. I just returned from vacation.

WindTerm does not support restoring the `floating state` after restart. To remember the floating state, there are too many parameters to save, including the position, size and so on of the `floating panes`. This will increase the complexity of the implementation, and there are very few requirements for this.
