### ISSUE TITLE
fcitx input method is not supported

### ISSUE THREAD

**Issue by jimifm** [kingToolbox/WindTerm#39]
Linux version does not support fcitx input method

**Comment by jimifm** [comment]
sorry! i got it

**Comment by kingToolbox** [comment]
The new [WindTerm_2.2.0_Prerelease_4](https://github.com/kingToolbox/WindTerm/releases/tag/2.2-prerelease) version has been released and this issue may has been fixed, please download and check it. If this problem persists, please let me know and I will continue to fix it, thank you.

**Comment by kgbook** [comment]
@kingToolbox 

Fcitx5 not supported  on WindTerm 2.4.0 

fcitx5 version:
```bash
$ fcitx5 --version
5.0.15
```

OS information:
```bash
$ screenfetch 
                   -`                 
                  .o+`                 kang@KONKA
                 `ooo/                 OS: Arch Linux 
                `+oooo:                Kernel: x86_64 Linux 5.17.5-arch1-1
               `+oooooo:               Uptime: 1h 5m
               -+oooooo+:              Packages: 1129
             `/:-:++oooo+:             Shell: bash
            `/++++/+++++++:            Resolution: 3840x1200
           `/++++++++++++++:           DE: KDE 5.93.0 / Plasma 5.24.5
          `/+++ooooooooooooo/`         WM: KWin
         ./ooosssso++osssssso+`        GTK Theme: Breeze [GTK2/3]
        .oossssso-````/ossssss+`       Icon Theme: breeze
       -osssssso.      :ssssssso.      Disk: 648G / 969G (71%)
      :osssssss/        osssso+++.     CPU: Intel Core i7-10510U @ 8x 4.9GHz [50.0°C]
     /ossssssss/        +ssssooo/-     GPU: UHD Graphics
   `/ossssso+/:-        -:/+osssso+-   RAM: 5627MiB / 7709MiB
  `+sso+:-`                 `.-/+oso: 
 `++:.                           `-/+/
 .`                                 `/

```

**Comment by kgbook** [comment]
> @kingToolbox
> 
> Fcitx5 not supported on WindTerm 2.4.0
> 
> fcitx5 version:
> 
> ```shell
> $ fcitx5 --version
> 5.0.15
> ```
> 
> OS information:
> 
> ```shell
> $ screenfetch 
>                    -`                 
>                   .o+`                 kang@KONKA
>                  `ooo/                 OS: Arch Linux 
>                 `+oooo:                Kernel: x86_64 Linux 5.17.5-arch1-1
>                `+oooooo:               Uptime: 1h 5m
>                -+oooooo+:              Packages: 1129
>              `/:-:++oooo+:             Shell: bash
>             `/++++/+++++++:            Resolution: 3840x1200
>            `/++++++++++++++:           DE: KDE 5.93.0 / Plasma 5.24.5
>           `/+++ooooooooooooo/`         WM: KWin
>          ./ooosssso++osssssso+`        GTK Theme: Breeze [GTK2/3]
>         .oossssso-````/ossssss+`       Icon Theme: breeze
>        -osssssso.      :ssssssso.      Disk: 648G / 969G (71%)
>       :osssssss/        osssso+++.     CPU: Intel Core i7-10510U @ 8x 4.9GHz [50.0°C]
>      /ossssssss/        +ssssooo/-     GPU: UHD Graphics
>    `/ossssso+/:-        -:/+osssso+-   RAM: 5627MiB / 7709MiB
>   `+sso+:-`                 `.-/+oso: 
>  `++:.                           `-/+/
>  .`                                 `/
> ```

.pam_environment configurations:
```bash
$ cat .pam_environment 
GTK_IM_MODULE DEFAULT=fcitx5
QT_IM_MODULE DEFAULT=fcitx5
XMODIFIERS DEFAULT=@im=fcitx5
INPUT_METHOD DEFAULT=fcitx5
SDL_IM_MODULE DEFAULT=fcitx5
GLFW_IM_MODULE DEFAULT=fcitx5
```
