### ISSUE TITLE
Feature: Close the Tab page when the shell exits normally.

### ISSUE THREAD

**Issue by EdenHell** [kingToolbox/WindTerm#397]
I hope there is an option:
The Tab page is closed when the shell exits normally.
For example, after I press ctrl+d, this tab can be closed. But if the network is disconnected, it will not be closed.

**Comment by EdenHell** [comment]
Sorry, I found that this issue is duplicated with #210.

**Comment by kingToolbox** [comment]
When the current session is disconnected, the new [WindTerm_2.4.0_Prerelease_1](https://github.com/kingToolbox/WindTerm/releases/tag/2.4-prerelease) supports pressing the shortcut key `Ctrl+D` to close the tab. Please download and use it, thank you.
