### ISSUE TITLE
gsudo do not start. Windows 10 Enterprise LTSC 1809

### ISSUE THREAD

**Issue by mr-crux** [kingToolbox/WindTerm#40]
Hello, 
launching WindTerm_Win10_Conpty when trying to create a session, gsudo does not correctly detect the OS version and does not start.

OS:  Windows 10 Enterprise LTSC 1809
Build: 17763.1637
![image](https://user-images.githubusercontent.com/55377814/103517302-948a4b80-4e7a-11eb-9aca-424740a5d9b2.png)

**Comment by mr-crux** [comment]
Ok, thank you. Think I've missed that part...

**Comment by kingToolbox** [comment]
Sorry, this is my mistake. I did not clearly mark the system requirements. Now I have added it in the release notes, thank you.
