### ISSUE TITLE
macos  deadline

### ISSUE THREAD

**Issue by liyanggyang** [kingToolbox/WindTerm#408]
Sorry, since the MacOS version has not been stable so far, the release of the WindTerm 2.2.0 MacOS version has been cancelled and it is expected that a brand new stable universal app will be released in December.

mark 2021.12.30 10:30

**Comment by kingToolbox** [comment]
Sorry for the late reply. I just returned from vacation.

I'm sorry I didn't release the MacOS version as expected, it took more work than I expected, but I'll try to release the MacOS version soon. Please stay tuned, thank you.

**Comment by kingToolbox** [comment]
The MacOS version of WindTerm has been released, please download and check [WindTerm_2.3.0_Prerelease_2_MacOS_Portable](https://github.com/kingToolbox/WindTerm/releases/2.3-prerelease). If you encounter any problems, please let me know. Thank you.
