### ISSUE TITLE
怎么让文件管理器在软件下面啊

### ISSUE THREAD

**Issue by 107295472** [kingToolbox/WindTerm#414]
![image](https://user-images.githubusercontent.com/6436116/147806812-beb61c87-759c-4e79-aba7-8d4af89474a6.png)
启动就这样，第次都要点一下，才出来。我想让它永远在下面显示

**Comment by u-Sir** [comment]
图里右上角齿轮添加不行？

**Comment by funkpopo** [comment]
右上角点选”专注模式“右侧的按钮
![image](https://user-images.githubusercontent.com/75678670/148154467-9272c8ba-3aba-49a2-a813-c4f0ac19fb1f.png)
将”底部停靠“开启。于底部停靠栏中通过齿轮图标开启文件管理器常驻。

**Comment by 107295472** [comment]
常驻,不行，关闭后，在启动还是在左边

**Comment by 107295472** [comment]
好用了，不能用中文bug多，英文就可以

**Comment by kingToolbox** [comment]
@u-Sir @funkpopo Thank you very much for your help.

@107295472 
After setting the language to `Chinese`, I tested the function and there was no problem. Maybe you can try again, thank you.
