### ISSUE TITLE
按Ctrl+s后，tab页面卡死,需要关闭后重新打开

### ISSUE THREAD

**Issue by yanshikun** [kingToolbox/WindTerm#417]
操作系统：windows
WinddTerm版本：2.2.2

**Comment by funkpopo** [comment]
Linux的Ctrl+s快捷键是将命令行暂时锁住。按Ctrl+q解锁。

**Comment by yanshikun** [comment]
好的,谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月5日(星期三) 中午11:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [kingToolbox/WindTerm] 按Ctrl+s后，tab页面卡死,需要关闭后重新打开 (Issue #417)





 
Linux的Ctrl+s快捷键是将命令行暂时锁住。按Ctrl+q解锁。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
