### ISSUE TITLE
ssh 无法连接(cecureCRT可正常连接)

### ISSUE THREAD

**Issue by yongxiangzheng** [kingToolbox/WindTerm#419]
ssh 无法连接，点击关闭后，界面卡死
![1112](https://user-images.githubusercontent.com/8653159/148018922-4bbd7c9d-f90c-4012-81a8-61f22cab6d37.gif)

**Comment by funkpopo** [comment]
建议优先考虑试用2.2.1版本，在密钥验证的稳定性上较好。
请顺便检查一下您的会话设置，是否有1、key未正确对应；2、端口未正确对应；3、是否手动设置了代理服务器；4、身份验证文件（key）是否仍在您的指定路径下

**Comment by yongxiangzheng** [comment]
会话设置：采用密码方式登录，确认端口也是正确，并不是所有ssh server登录都卡住，是在登录Dropbear 服务才会卡住，我又试了2.1.0和2.2.0 Prerelease 5同样出现卡住问题（2.2.1版本未找到）

**Comment by kingToolbox** [comment]
Sorry for the late reply. I just returned from vacation.

The new [Windterm_2.3.0_Prerelease_1](https://github.com/kingToolbox/WindTerm/releases/tag/2.3-prerelease) version has been released, please download and check it. If there are still bugs, please let me know, thank you.

**Comment by yongxiangzheng** [comment]
使用2.3.0版本问题依然存在
![1112](https://user-images.githubusercontent.com/8653159/148721731-082314d3-852f-44ec-9111-600ab4def540.gif)

**Comment by kingToolbox** [comment]
Does the server you are connected to have `SFTP` service? If not, can you try unchecking the `Session Property Dialog - SSH - SSH - Authentication - Enable SFTP` option and try connect again, as described in #325. If it still can't be solved, I will check and fix this issue. Thank you.

**Comment by yongxiangzheng** [comment]
按照您的步骤操作，已经可以正常连接了，谢谢。
![image](https://user-images.githubusercontent.com/8653159/149046730-e074c0ad-96cf-4906-932a-c4b5eb4a3741.png)

**Comment by kingToolbox** [comment]
That's great. I will see if I can detect whether the `SFTP` service exists to avoid deadlocks. You are welcome to continue submitting new issues. Thank you very much for your feedback.

**Comment by guguailf** [comment]
我这里有一台服务器，无法连接，把该会话验证里面的选项都去除了也无法登录，连用户名和密码的输入界面都没出来
![图片](https://user-images.githubusercontent.com/56786055/187187399-687befb8-0e48-4c7a-a98b-cc236db56cad.png)
其他ssh工具是没有问题的，很奇怪呀

**Comment by zhangweijie97** [comment]
2.5版本仍然存在此问题，并没有“检测该SFTP服务是否存在以防免死锁”

**Comment by a616567126** [comment]
如果mac使用clash for windows无法连接大陆以外的服务器可尝试更新Service Mode
