### ISSUE TITLE
关于会话切换的问题

### ISSUE THREAD

**Issue by CZMG** [kingToolbox/WindTerm#420]
版本：2.2.2
目前版本，我发现切换会话是通过鼠标移动，自动切换，但我并不想鼠标移动的时候切换标签，希望像crt、xshell那样，可以通过alt+数字来切换。界面上的设置里我没找到相关的，请问是不支持还是有别的方法？

**Comment by funkpopo** [comment]
左上角“会话” - “首选项” - “设置” - “标签”，选择第二个<悬停后激活选项卡>，将时间设定为你所需要的，单位为秒。
当前版本不支持快捷键切换会话标签。

**Comment by CZMG** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by CZMG** [comment]
> 左上角“会话” - “首选项” - “设置” - “标签”，选择第二个<悬停后激活选项卡>，将时间设定为你所需要的，单位为秒。 当前版本不支持快捷键切换会话标签。

多谢。

**Comment by kingToolbox** [comment]
Thank you @funkpopo for your help. Let me introduce the relevant shortcut keys:

|  Key | Action |
| ---- | ---- |
| Ctrl+Alt+1 | Activate the first tab |
| Ctrl+Alt+2 | Activate the second tab |
| Ctrl+Alt+3 | Activate the third tab |
| Ctrl+Alt+4 | Activate the fourth tab |
| Ctrl+Alt+5 | Activate the last tab |
| Alt+[ | Activate the previous tab |
| Alt+] | Activate the next tab |

**Comment by CZMG** [comment]
> Thank you @funkpopo for your help. Let me introduce the relevant shortcut keys:
> 
> Key	Action
> Ctrl+Alt+1	Activate the first tab
> Ctrl+Alt+2	Activate the second tab
> Ctrl+Alt+3	Activate the third tab
> Ctrl+Alt+4	Activate the fourth tab
> Ctrl+Alt+5	Activate the last tab
> Alt+[	Activate the previous tab
> Alt+]	Activate the next tab

Thank you for your answer.

**Comment by kingToolbox** [comment]
Ok, it looks like this issue has been resolved and can be closed. Welcome to continue submitting new issues and feature requests, thank you.

**Comment by jxcangel** [comment]
can we customize shortcut keys? I usually use alt+1 or alt+2 to switch tab

**Comment by funkpopo** [comment]
> can we customize shortcut keys? I usually use alt+1 or alt+2 to switch tab
You may use "Alt + O" to open the command line then use "Alt + 1" and "Alt + 2" to switch tabs for now. Or just use "Alt + [" and "Alt + ]".

**Comment by funkpopo** [comment]
> can we customize shortcut keys? I usually use alt+1 or alt+2 to switch tab

You may use "Alt + O" to open the command line then use "Alt + 1" and "Alt + 2" to switch tabs for now. Or just use "Alt + [" and "Alt + ]".

**Comment by kingToolbox** [comment]
@jxcangel 
You can read [this comment](https://github.com/kingToolbox/WindTerm/issues/86#issuecomment-825505179) to learn how to customize the shortcut keys to `Alt+Num`. 

But I suggest you wait patiently for the next `WindTerm_2.4.0` version, because the next version already supports switching tabs using `Alt+Num`.

`WindTerm_2.4.0_Prerelease_1` is expected to be released this week, and you are welcome to download and use it at that time. Before that, you can use the method provided by @funkpopo, thank you.

**Comment by kingToolbox** [comment]
I am happy to inform you that [WindTerm_2.4.0_Prerelease_1](https://github.com/kingToolbox/WindTerm/releases/tag/2.4-prerelease) has been released and this issue has been fixed. After redesigning the menu bar, `WindTerm` finally support `Alt+0~5` shortcut keys to activate tabs by default. :smile: Please download and use it, thank you.

Now the new shortcut keys:
|  Key | Action |
| ---- | ---- |
| Alt+0 | Activate the last tab |
| Alt+1 | Activate the first tab |
| Alt+2 | Activate the second tab |
| Alt+3 | Activate the third tab |
| Alt+4 | Activate the fourth tab |
| Alt+5 | Activate the last tab |
| Alt+[ | Activate the previous tab |
| Alt+] | Activate the next tab |

And shortcut keys such as `Ctrl+Alt+0~9` have been removed.
