### ISSUE TITLE
在某些串口终端无法使用backspace键

### ISSUE THREAD

**Issue by jgx91** [kingToolbox/WindTerm#421]
在串口连接进入liteos时，无法使用退格键删除输入的命令，而在xshell中没有这个现象

**Comment by jgx91** [comment]
Windows 2.2.2版本

**Comment by hongnod** [comment]
要选择一下backspace对应的码，华为的部分系统有此问题。

**Comment by kingToolbox** [comment]
Sorry for the late reply. I just returned from vacation.

@hongnod Thank you for your help.

Please try to set the key value of the `backspace` key to see if it can solve the problem. You can read [Backspcae And Delete Key](https://kingtoolbox.github.io/2020/08/22/keyboard-backspace-delete/) to learn more, thank you.

**Comment by jgx91** [comment]
谢谢，可以在键盘设置指定退格，是我自己没找到

**Comment by kingToolbox** [comment]
Ok, it looks like this issue has been resolved and can be closed. Welcome to continue submitting new issues and feature requests, thank you.
