### ISSUE TITLE
会话界面添加个菜单会更好用吧

### ISSUE THREAD

**Issue by lzpong** [kingToolbox/WindTerm#424]
会话界面添加个菜单会更好用吧
![image](https://user-images.githubusercontent.com/10493371/148191295-44f1d70b-fbed-403a-ae92-36350291df32.png)
![image](https://user-images.githubusercontent.com/10493371/148191340-2d4ee18c-40ac-409d-a540-2e4d18c65640.png)

**Comment by kingToolbox** [comment]
Thank you for your suggestion, `New Session` menu item has been added to the `Session` Pane. Please download [Windterm_2.3.0_Prerelease_1](https://github.com/kingToolbox/WindTerm/releases/tag/2.3-prerelease) version and check it.

If you have any more needs, please feel free to ask, thank you.
