### ISSUE TITLE
锁屏的初始主密码是多少?

### ISSUE THREAD

**Issue by lzpong** [kingToolbox/WindTerm#425]
锁屏 界面 的 初始 主密码 是多少?

**Comment by kirileec** [comment]
直接回车  为空

**Comment by 1104662797** [comment]
为空也不行，重新设置也不行，然后连接也需要主密码

**Comment by 1104662797** [comment]
可能是自己操作的时候没有仔细看设置了密码，我就是，把所有密码尝试一遍就好了.....

**Comment by secxue** [comment]
> 为空也不行，重新设置也不行，然后连接也需要主密码

重新设置在哪里啊 我没找到 我擦

**Comment by ddddddduan** [comment]
主密码是用户名。

**Comment by shiyi23** [comment]
> 直接回车 为空

这是正解哈哈

**Comment by cxq-haha** [comment]
能否关闭锁屏密码功能

**Comment by liuzonglin1** [comment]
不需要锁屏密码，直接回车就好

**Comment by loveanao** [comment]
我完全被搞晕了，直接解压本地使用，就要求数主密码，回车不对，操作系统登录密码也不对，也找不到去哪儿重置或者设置主密码。。。可不可以去掉这个功能，或者完善重置主密码的功能。

**Comment by LazySheeeeep** [comment]
> 直接回车 为空

correct

**Comment by OneCodeMonkey** [comment]
确实有问题啊，还有锁屏密码，压根就没有设置过 怎么就让输密码了？这块设计有问题

**Comment by viviwu** [comment]
这就是个bug

**Comment by CitrusFlavored** [comment]
我试了，是我第一次连接ssh时用的密码，不知道是不是中途设置过然后忘记了

**Comment by winlong** [comment]
> 我完全被搞晕了，直接解压本地使用，就要求数主密码，回车不对，操作系统登录密码也不对，也找不到去哪儿重置或者设置主密码。。。可不可以去掉这个功能，或者完善重置主密码的功能。

我试了回车是可以的

**Comment by forever-xyz** [comment]
无语，密码竟然是回车键

**Comment by jiang11034** [comment]
查到这个文件user.config文件（安装目录：WindTerm_2.5.0\.wind\profiles\default.v10），修改application.masterPassword 为false，重新启动即可

**Comment by Nyoli** [comment]
ohhhh 原来是默认secret是换车

**Comment by macsur** [comment]
修改这个文件user.config文件（安装目录：C:\Users\Administrator\.wind\profiles\default.v10\user.config），修改application.masterPassword 为false，重新启动即可
~~
C:\Users\Administrator\.wind\profiles\default.v10\user.config
~~
注意：其中的Administrator是你的用户名
试试这个，应该就可以了。
