### ISSUE TITLE
希望能添加一个连接会话后自动执行某个命令的功能

### ISSUE THREAD

**Issue by heisetanghulu** [kingToolbox/WindTerm#428]
在测试环境，看日志比较多，但不同微服务日志目录不同，希望可以添加一个像xshell那样的功能，每个会话可以设置一个连接后自动执行的命令，比如进入到某个目录的命令，会方便很多

**Comment by Vectorsmiracle** [comment]
有这个功能
![image](https://user-images.githubusercontent.com/22764532/148481680-bbe61f55-1c44-447b-823d-6a211b40b033.png)

**Comment by heisetanghulu** [comment]
> 有这个功能 ![image](https://user-images.githubusercontent.com/22764532/148481680-bbe61f55-1c44-447b-823d-6a211b40b033.png)

多谢，我还以为没这个功能

**Comment by kingToolbox** [comment]
Both `SSH` and `Shell` have the feature of automatically executing specified commands after startup.

- Shell: Session Settings Dialog - Shell - Shell - Process - Execute command after start.
- SSH:  Session Settings Dialog - SSH - SSH - Authentication - Execute command after authentication.

If you need to execute multiple commands, you can write them to a `.bat` or `.sh` file and then execute the script file.

**Comment by heisetanghulu** [comment]
> Both `SSH` and `Shell` have the feature of automatically executing specified commands after startup.
> 
> * Shell: Session Settings Dialog - Shell - Shell - Process - Execute command after start.
> * SSH:  Session Settings Dialog - SSH - SSH - Authentication - Execute command after authentication.
> 
> If you need to execute multiple commands, you can write them to a `.bat` or `.sh` file and then execute the script file.

**Comment by drcege** [comment]
SSH 登录后自动执行命令的时间太早了，这时候服务器还没加载完，所以这个命令根本没法成功执行。
希望能加一个延时设置，等SSH登录完毕后再执行命令。

**Comment by kingToolbox** [comment]
@drcege 
I am happy to inform you that [WindTerm_2.4.0_Prerelease_2](https://github.com/kingToolbox/WindTerm/releases/tag/2.4-prerelease) has been released and `delayed sending of commands` has been added. Please download and check it, thank you.

**Comment by Y2Kai** [comment]
认证后执行命令，命令显示出来，但是没有执行

**Comment by CcccFz** [comment]
@Y2Kai 在命令后面加个`\n`（linux）或`\r`（powershell）就可以执行

**Comment by C370228492** [comment]
请问如何支持执行多个命令?  期望"启动后执行命令(E)"文本框从单行输入改成多行输入.   类型快速命令的录入和执行方式一样
