### ISSUE TITLE
It will Automatically close inactive connections, every time I have to wait a long time to wait it recovery. How can I close the Automatically close?

### ISSUE THREAD

**Issue by 1104662797** [kingToolbox/WindTerm#432]
Thanks very much

**Comment by kingToolbox** [comment]
Please do the following two operations to set `keepalive` to see if this problem can be solved.

- Check the `Session Setting Dialog - SSH - Connection - Enable TCP keepalives (SO_KEEPALIVE option)`.
- Set Session `Setting Dialog - SSH - Connection - Sends null packet to keep session alive` to nonzero value, like 5 seconds.

If you still have problems, please let me know, thank you!

**Comment by 1104662797** [comment]
Thans
