### ISSUE TITLE
每次更新后，那些在老版本的会话，不能直接导入导出到新版本

### ISSUE THREAD

**Issue by qwz160** [kingToolbox/WindTerm#438]
每次更新后，那些再老版本的所有会话，不能直接导入导出到新版本，每次都需要重新手动输入，建议加导入导出会话功能

**Comment by ViCrack** [comment]
profiles文件夹里面有配置的数据 , 保存起来复制过去就行了

**Comment by funkpopo** [comment]
> profiles文件夹里面有配置的数据 , 保存起来复制过去就行了

将"profile"文件夹复制进入新版本的解压目标路径WindTerm文件夹内即可

**Comment by qwz160** [comment]
软件里面设置个导入导出会话功能吧，老的版本可以把会话导出，新的版本导入会话即可。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kingToolbox/WindTerm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月12日(星期三) 下午3:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kingToolbox/WindTerm] 每次更新后，那些在老版本的会话，不能直接导入导出到新版本 (Issue #438)





  
profiles文件夹里面有配置的数据 , 保存起来复制过去就行了
  
将"profile"文件夹复制进入新版本的解压目标路径WindTerm文件夹内即可
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kingToolbox** [comment]
As described in the release page.

> Upgrade
> For Windows and Linux, copy or move the profiles folder from the old Windows/Linux version to the new Windows/Linux version and all the sessions and configuration will be restored.

I think this is already a very easy way to upgrade. :smile:

**Comment by ViCrack** [comment]
另外说一下

`windows` 环境下使用 [scoop](https://github.com/ScoopInstaller/Scoop) 来自动更新也很方便

```powershell
# 添加官方软件仓库
scoop bucket add extras
# 安装
scoop install windterm
# 自动更新
scoop update windterm
```

**Comment by kingToolbox** [comment]
Ok, this issue has been well answered. By the way, thank you @ViCrack for providing a new way to install `WindTerm`.

**Comment by kingToolbox** [comment]
The new [WindTerm_2.4.0_Prerelease_1](https://github.com/kingToolbox/WindTerm/releases/tag/2.4-prerelease) supports specifying the storage path of `profiles`, which makes it more easier to transfer `profiles` to other devices. Welcome to download and use it. Thank you.

**Comment by ayuayue** [comment]
> 另外说一下
> 
> `windows` 环境下使用 [scoop](https://github.com/ScoopInstaller/Scoop) 来自动更新也很方便
> 
> ```powershell
> # 添加官方软件仓库
> scoop bucket add extras
> # 安装
> scoop install windterm
> # 自动更新
> scoop update windterm
> ```

but it's not work now

**Comment by ViCrack** [comment]
> ```powershell
> windterm
> ```

反馈给[Scoop](https://github.com/ScoopInstaller/Extras)

**Comment by ayuayue** [comment]
> > ```powershell
> > windterm
> > ```
> 
> 反馈给[Scoop](https://github.com/ScoopInstaller/Extras)

好的，但这回复也太快了
