### ISSUE TITLE
ANSI escape sequences ESC]8 bug

### ISSUE THREAD

**Issue by Editst** [kingToolbox/WindTerm#454]
I am using windterm to connect to a remote server. I am using zsh for the remote server. When I use `systemctl status caddy`,  I see  ESC]8 appear after the command like this.

```raw
Docs: ESC]8;;https://caddyserver.com/docs/https://caddyserver.com/docs/ESC]8;;
```

I suspect this is due to incomplete support for ANSI escape sequences. When I connect to the server with windows terminal, I see no such issues.

**Comment by kingToolbox** [comment]
Duplicate of #160 #453

Yes, `OSC 8` will be supported in the next `WindTerm 2.4` version, which expected to be released in February. Please stay tuned, thank you.

**Comment by kingToolbox** [comment]
I am happy to inform you that [WindTerm_2.3.0_Prerelease_3](https://github.com/kingToolbox/WindTerm/releases/tag/2.3-prerelease) has been released and this issue has been fixed, please download and check it, thank you.

**Comment by Editst** [comment]
This can be displayed perfectly, thanks so much for your fix
