### ISSUE TITLE
2.3.0 Prerelease 1 页面布局过段时间会自动重置

### ISSUE THREAD

**Issue by u-Sir** [kingToolbox/WindTerm#455]
刚升上来时正常的，过几天后就自动重置了。重新下过了也一样。
自动重置前：
![图片](https://user-images.githubusercontent.com/93647031/149644336-ad2b01c1-c31c-4a7a-9b1b-e2a4366d8d32.png)

自动重置后：
![图片](https://user-images.githubusercontent.com/93647031/149644290-dadc850d-165d-461f-836e-3d1d383572aa.png)

**Comment by 107295472** [comment]
中文的，bug很多还是用英文的好

**Comment by u-Sir** [comment]
> 中文的，bug很多还是用英文的好

切换为英文后，也出现布局重置了😂

**Comment by 107295472** [comment]
一直用英文的就好了

**Comment by kingToolbox** [comment]
This has nothing to do with language. Please update to the latest [2.3 Prerelease](https://github.com/kingToolbox/WindTerm/releases/2.3-prerelease) version and try again. If there are still problems, I will investigate this issue. Thank you.

**Comment by 107295472** [comment]
> This has nothing to do with language. Please update to the latest [2.3 Prerelease](https://github.com/kingToolbox/WindTerm/releases/2.3-prerelease) version and try again. If there are still problems, I will investigate this issue. Thank you.

It's easy to use, and it doesn't change when I switch back to the Chinese layout.

**Comment by kingToolbox** [comment]
Ok, maybe we need to wait for a while to see if this issue will appear in the new `2.3.0` version.

**Comment by u-Sir** [comment]
2.3.0 Prerelease 2没有出现了

**Comment by kingToolbox** [comment]
Thank you very much for your feedback.

**Comment by kingToolbox** [comment]
SORRY! `WindTerm_2.3.0_Prerelease_2` and `WindTerm_2.3.0_Prerelease_3` has a **serious SFTP bug** #487 and may cause file corruption after **uploaded**.

Please use the old versions or update to the [WindTerm_2.3.0_Prerelease_4](https://github.com/kingToolbox/WindTerm/releases/tag/2.3-prerelease) version. Thank you.
