### ISSUE TITLE
在会话设置中预设密码凭证

### ISSUE THREAD

**Issue by openmynet** [kingToolbox/WindTerm#456]
是否可以在会话设置中预设凭证；在某些极端情况下 SSH 服务器要求在短时间内 ( 1s ~ 2s) 做出回应，否则会断开连接。 在这么短的时间内无法手动完成密码凭证的输入。

**Comment by kingToolbox** [comment]
Yes, WindTerm supports [automatic login](https://kingtoolbox.github.io/2020/01/23/auto-login/), and you can also set up the `identity file` in the `Session Settings Dialog - SSH - SSH - Authentication - Identity file for authentication`. Both methods should be able to meet your needs.

**Comment by Dodotry** [comment]
Win11下V2.2.2、V2.3.0版本出现这个异常
![image](https://user-images.githubusercontent.com/48266156/153793136-a2039caa-d421-4f73-a9de-b7b2e15968a0.png)
