### ISSUE TITLE
Does not support Chinese? My folder names that contain Chinese characters are displayed as a bunch of question marks

### ISSUE THREAD

**Issue by prestu** [kingToolbox/WindTerm#462]
drwxr-xr-x    3 fanchengheng  staff    96 Dec 31 18:14 videos
drwxr-xr-x@   7 fanchengheng  staff   224 Sep  8 14:34 ????????????
drwxr-xr-x    4 fanchengheng  staff   128 Jul  6  2021 ????????????
drwxr-xr-x    2 fanchengheng  staff    64 Jan  6 13:52 ????????????
drwxr-xr-x    2 fanchengheng  staff    64 Jul  6  2021 ??????
drwxr-xr-x    3 fanchengheng  staff    96 Jul 14  2021 ????????????

**Comment by kingToolbox** [comment]
I guess you are connected to a `Mac` server.

First you need to make sure that `LANG` and `LANG_ALL` are set to `zh_CN.UTF-8`:
```
export LANG=zh_CN.UTF-8
export LANG_ALL=zh_CN.UTF-8
```
Then if the Chinese characters are still displayed as `???`, please use `ls -w` instead of `ls`.

**Comment by prestu** [comment]
ok,thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月20日(星期四) 下午3:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [kingToolbox/WindTerm] Does not support Chinese? My folder names that contain Chinese characters are displayed as a bunch of question marks (Issue #462)





 
I guess you are connected to a Mac server.
 
First you need to make sure that LANG and LANG_ALL are set to zh_CN.UTF-8:
 export LANG=zh_CN.UTF-8 export LANG_ALL=zh_CN.UTF-8  
Then if the Chinese characters are still displayed as ???, please use ls -w instead of ls.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kingToolbox** [comment]
Thank you very much for your feedback, you are welcome to continue submitting new issues.
