### ISSUE TITLE
The default theme(dige-black) 'active' tab contrast is very low.

### ISSUE THREAD

**Issue by staugur** [kingToolbox/WindTerm#465]
作者好，最近发现这款很棒的工具，我正逐步用它替换xshell，但是有个小问题。

我喜欢简洁，所以界面上尽可能去掉了所有功能窗口，仅保留代码窗口。

这时候使用 `dige-black` 主题，当前活动标签页顶部颜色对比其他标签页不好辨识，类似于 microsoft/terminal#771 这个问题。

我该设置哪个配置文件修改它的颜色或背景色呢？

### English

Hi author, recently discovered this great tool, I'm gradually replacing xshell with it, but there is a small problem.

I like simplicity, so all functional windows are removed as much as possible on the app page, and only the code window is retained.

At this time, the `dige-black` theme is used. The color at the top of the current active tab is not easy to identify compared to other tabs, similar to microsoft/terminal#771 issue.

Which configuration file I should modify to modify its color or background color?

#### Picture
![](https://static.saintic.com/picbed/staugur/2022/01/21/windterm.png)

**Comment by kingToolbox** [comment]
You are welcome.

You can modify the `WindTerm_install_path\global\themes\dige-black\gui.theme` file to customize the colors.

```
QTabBar::tab:selected {
	color: white;
	border-right: 1x solid #1c1c1c;
	background-color: #1c1c1c;
}
QTabBar::tab:!selected:hover {
	background-color: #444444;
}
...
#ViewGroup > QTabBar::tab:selected:!only-one {
	border-top: 2px solid #007acc;   # The height and color of the bar at the top of the activated tab.
}
```
The snippet above is the part related to the color of the tab. You can read [Stylesheet Reference](https://doc.qt.io/qt-5/stylesheet-reference.html) to learn more. Please feel free to reach out if you have any questions.

**Comment by staugur** [comment]
Great! 

I found the `#ViewGroup > QTabBar::tab:selected:!only-one` in the last few lines and got what I wanted, now I can see it clearly.
