### ISSUE TITLE
Connecting to Linux Server with 1.9.2

### ISSUE THREAD

**Issue by rezkin** [kingToolbox/WindTerm#47]
Getting response "Protocol type not supported"

![image](https://user-images.githubusercontent.com/22175622/104385964-cabe6f80-54f9-11eb-9def-57a078f195d4.png)

**Comment by kingToolbox** [comment]
This kind of error usually means address family not supported by protocol family.

I guess you are using an IPv6 address. If yes, please check if your system with no IPv6 address configured. This would probably happen on linux in a docker container or whatever the equivalent would be. Or, one could disable IPv6 manually. Another possibility is if your ISP is not assigning any GUAs to you, then you can not use IPv6 to connect to the outside servers too.

**Comment by kingToolbox** [comment]
Hi, has this issue been solved? If the issue is still valid just add a comment to keep it alive. If no further activity occurs during the next week, this issue will be closed. Thank you.

**Comment by kingToolbox** [comment]
This issue will be closed because the cause of the error is probably not related to WindTerm, and no further activity occurs during the last month. Please reopen this issue if it is still valid. Thank you.
