### ISSUE TITLE
Failed to request MFA code (OTP) using automatic-login option

### ISSUE THREAD

**Issue by nick2wang** [kingToolbox/WindTerm#476]
When I connect to jumpserver(an open source bastion host system) through ssh, it requires me to use Google Authenticator to generate a MFA code for further authentication. It works fine when I use putty or xshell for this circumstance. WindTerm can do this the first time I connect with automatic login option, but failed to request the MFA code forwardly after the first successful login, it seems to have some issues with that.

putty:
![image](https://user-images.githubusercontent.com/33473924/151097902-aaf18c5b-b5d1-41eb-835f-771f99595dbe.png)

xshell:
![image](https://user-images.githubusercontent.com/33473924/151097948-4b5d9ce2-53f0-4e76-9599-d18dd5431670.png)

first time on WindTerm:
![image](https://user-images.githubusercontent.com/33473924/151100069-e87cac50-701d-4e64-b5be-b32924a4b32f.png)

afterwards:
![image](https://user-images.githubusercontent.com/33473924/151108922-b4ae2e80-9546-423e-b436-65159ba66b43.png)

**Comment by kingToolbox** [comment]
I think this is because automatic login is only suitable for static `password`/`public key`. Since the `MFA` code changes every time, please use manual login.

**Comment by liuzhiming1988** [comment]
什么时候可以支持呢   这个真的很蛋疼

**Comment by kingToolbox** [comment]
I am happy to inform you that [WindTerm_2.4.1](https://github.com/kingToolbox/WindTerm/releases/tag/2.4.0) has been released and this bug has been fixed. Please download and check it, thank you.

**Comment by SOLOKEM** [comment]
如果同时使用了password和Google Authenticator 两种验证方式，在WindTerm下的登录真的很难绷。
似乎WindTerm不能调用已保存的用户密码（我已经设置了密码和键盘交互两种验证方式，并且保存了用户名及密码），每次打开都会提示验证失败，然后必须重新输入一遍密码，然后再切换到键盘交互选项卡，才能继续输入Verification code。
而在MobaXterm下则不需要二次输入已保存的密码，只需要输入Verification code即可。
难道是WindTerm有意而为？既然用了OTP，就必须要手敲用户密码？不能自动调用已保存的？

**Comment by SOLOKEM** [comment]
> 我很高兴地通知您，[WindTerm_2.4.1](https://github.com/kingToolbox/WindTerm/releases/tag/2.4.0) 已经发布，此错误已修复。请下载并检查一下，谢谢。

我搜了一下发现也有人在问这个问题，我就不开新的issue了。

我在用的版本是2.6.1

如果同时使用了password和Google Authenticator 两种验证方式，在WindTerm下的登录真的很难绷。

似乎WindTerm不能调用已保存的用户密码（我已经设置了密码和键盘交互两种验证方式，并且保存了用户名及密码），每次打开都会提示验证失败，然后必须重新输入一遍密码，然后再切换到键盘交互选项卡，才能继续输入Verification code。

而在MobaXterm下则不需要二次输入已保存的密码，只需要输入Verification code即可。

难道是WindTerm有意而为？既然用了OTP，就必须要手敲用户密码？不能自动调用已保存的？

总体来说WindTerm还是非常好用的，好在我只有一台服务器开了OTP，感谢作者的辛勤付出哈。

**Comment by auqf** [comment]
it's still not support, and not update?

**Comment by SOLOKEM** [comment]
> it's still not support, and not update?

yes, its still not support.
