### ISSUE TITLE
2.3.0 Pre release 3 - Rare file corrupt when uploading large file from Windows client to Linux host

### ISSUE THREAD

**Issue by nhanledev** [kingToolbox/WindTerm#487]
I upload this a big JAR file from my local drive to linux server with WinTerm 2.3.0 Pre 3, and it makes the JAR file corrupt and can not run.

I tested with sending the file via HTTP and it works normally, hence the WinTerm has some issue with uploading.

I used this file: `https://papermc.io/api/v2/projects/paper/versions/1.18.1/builds/177/downloads/paper-1.18.1-177.jar`

**Comment by kingToolbox** [comment]
Thank you, I will investigate this issue, and you can try the previous versions. If they work properly, it is recommended to use the old versions first. I will update any progress here. Please stay tuned.

**Comment by nhanledev** [comment]
I tried the current stable version 2.2.2 and it does not have this problem. Thank you for the fast response.

**Comment by kingToolbox** [comment]
Is it possible that it is the cause of `file permissions`? The `WindTerm_2.3.0_Prerelease_3` version will preserve the `file permissions` of uploading files. So `chmod +x` may be helpful. I do not think that the file was damaged during transmission. But I will verify it.

**Comment by nhanledev** [comment]
This is version 2.3.0 Pre 3. I dragged and dropped the file to upload it.

![image](https://user-images.githubusercontent.com/28459250/151649875-0ff1f98b-b754-411b-ab5e-60dfa40c0477.png)


This is version 2.2.2. I did the same thing. Same file.

![image](https://user-images.githubusercontent.com/28459250/151649903-3322a85f-61d0-4dea-8ebd-709ab208ff24.png)

By some reason the content of the file is modified :(

**Comment by kingToolbox** [comment]
I am very sorry for this, I have been compiling `WindTerm_2.3.0_Prerelease_3_Linux_Portable` version in `Linux` system since yesterday, so I did not verify this in time. I have just verified this with `WindTerm_2.3.0_Prerelase_3_Windows_Portable` and confirmed that this is a very **important and urgent** bug.

In order to avoid damaging more users' files, I will release a new bug-fix version as soon as possible. Thank you very much.

**Comment by kingToolbox** [comment]
The new [Windterm_2.3.0_Prerelease_4](https://github.com/kingToolbox/WindTerm/releases/tag/2.3-prerelease) version has been released, please download and check it. If there are still bugs, please let me know, thank you.

**Comment by nhanledev** [comment]
Hello, thank you for the very fast bug fixing.

I have tested the `WindTerm_2.3.0_Prerelase_4_Windows_Portable` and confirm that the file upload works just like in the stable version 2.2.2.

**Comment by l-we** [comment]
2.3.1 上传文件又有问题了， md5sum 对不上，文件损坏
