### ISSUE TITLE
How to dump and restore the ssh record data?

### ISSUE THREAD

**Issue by liu798675179** [kingToolbox/WindTerm#490]
I have many ssh ip and password pairs, about 30+, but when i updated software from 2.3.0 Prerelease 2 to Prerelease 4, the record just gone and all empty😂, so.......

Is there any way to dump and restore the ssh record data? by export to file or something?

Software Version: WindTerm_2.3.0_Prerelease_4_Mac_Portable_x86_64.dmg

**Comment by liu798675179** [comment]
The software is very easy to use, i hope the auther can consider this point, thanks.

**Comment by u-Sir** [comment]
look at usage in release note:
Upgrade

For Windows and Linux, copy or move the profiles folder from the old Windows/Linux version to the new Windows/Linux version and all the sessions and configuration will be restored.

For MacOS, copy or move the profiles folder from the old WindTerm.app/Contents/MacOS to the new WindTerm.app/Contents/MacOS and all the sessions and configuration will be restored.

The profiles folder is cross-platform.

**Comment by kingToolbox** [comment]
@u-Sir Thank you.
This issue has been solved and will be closed. Welcome to continue submitting new feature requests and bugs, thank you.
