### ISSUE TITLE
Cannot copy the error message

### ISSUE THREAD

**Issue by Lemonawa** [kingToolbox/WindTerm#492]
like this.I hope to search it on web,easily.
![image](https://user-images.githubusercontent.com/69106050/152680887-bbdf355a-4ecb-4b24-afce-1f6276e645d7.png)

**Comment by Lemonawa** [comment]
会话已断开连接，按回车重新连接 means:
The session has been disconnected, press enter to reconnect.

**Comment by kingToolbox** [comment]
Sorry for the late reply. Because I've been sick recently.

I will implement this feature in the next `WindTerm_2.4.0` version, `WindTerm_2.4.0_Prerelease_1` is expected to release this week, please stay tuned, thank you.

**Comment by Lemonawa** [comment]
> Sorry for the late reply. Because I've been sick recently.
> 
> I will implement this feature in the next `WindTerm_2.4.0` version, `WindTerm_2.4.0_Prerelease_1` is expected to release this week, please stay tuned, thank you.


OK, I'm sorry to hear that. Get well as soon as possible!

**Comment by kingToolbox** [comment]
I am happy to inform you that [WindTerm_2.3.1](https://github.com/kingToolbox/WindTerm/releases/tag/2.3.0) has been released and this issue has been fixed. Please download and check it. If there are still bugs, please let me know, thank you.

**Comment by Lemonawa** [comment]
> I am happy to inform you that [WindTerm_2.3.1](https://github.com/kingToolbox/WindTerm/releases/tag/2.3.0) has been released and this issue has been fixed. Please download and check it. If there are still bugs, please let me know, thank you.

OK, I will test it tonight.

**Comment by Lemonawa** [comment]
The BUG has been fixed.Thank you!
