### ISSUE TITLE
A strange problem, SSH does not send Client Protocol

### ISSUE THREAD

**Issue by xzhuiz** [kingToolbox/WindTerm#493]
After restarting the PC, WINDTERM does not work. 
Through the captain of the pcap, WINDTERM  do not send Client Protocol after TCP 3-way handshake.
Some SSH libraries have problems?

2.3.0, 2.2.0, 2.1.0 is the same, but putty,MobaXterm is working properly

**Comment by kingToolbox** [comment]
Sorry for the late reply. Because I've been sick recently.

Has this issue been solved? Thank you.
