### ISSUE TITLE
After switching user, the function of delete key and other control keys is confused

### ISSUE THREAD

**Issue by dyx9541** [kingToolbox/WindTerm#496]
Hello! 
I login in a Centos7 system, after switching users(to root), the delete key ,backspace key and arrow on the keyboard are disordered.

version:WindTerm_2.3.0

Yours Best

**Comment by dyx9541** [comment]
And also Ctrl+L  can not clear the screen.

**Comment by dyx9541** [comment]
![image](https://user-images.githubusercontent.com/43093521/153370024-ebaf69e7-b5ae-435f-81b9-22c6f65d02ea.png)

**Comment by dyx9541** [comment]
Hello
I've solved this problem by enter  "export TERM=linux".
![image](https://user-images.githubusercontent.com/43093521/153564018-4ea0c34f-51f6-4054-b8a6-de10f2830778.png)

Thks

**Comment by kingToolbox** [comment]
Sorry for the late reply. Because I've been sick recently.

I'm glad you've solved the problem yourself. I've had this problem before too, and I'm surprised that both `putty` and `mobaxterm` were able to handle this correctly. I will look into this issue again when I have time. Thank you.
