### ISSUE TITLE
How to download Windows binaries?

### ISSUE THREAD

**Issue by jlgarnier** [kingToolbox/WindTerm#498]
Hi all,

I'm probably (surely) dumb but couldn't find any to download Windows binaries: I'm just stuck at https://github.com/kingToolbox/WindTerm/releases and wander around without finding any clickable link.

Thanks in advance for your help and comprehension!

**Comment by jlgarnier** [comment]
Apologies for my dumbness... 🤦‍♂️

**Comment by kingToolbox** [comment]
Never mind, [WindTerm_2.3.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.3.0) has just been released and you are welcome to download and use it. :smile:
