### ISSUE TITLE
Error: No match for method mac algo client

### ISSUE THREAD

**Issue by franjorge** [kingToolbox/WindTerm#5]
Hello.

I got that error stating:

server [hmac-sha1-96,hmac-md5-96]

Regards

**Comment by kingToolbox** [comment]
Currently WindTerm only supports:
```
hmac-sha2-256-etm@openssh.com,
hmac-sha2-512-etm@openssh.com,
hmac-sha1-etm@openssh.com,
hmac-sha2-512,
hmac-sha2-256,
hmac-sha1,
none.
```
The hmac-sha1-96 and hmac-md5-96 will be supported in the next release.

**Comment by kingToolbox** [comment]
Hmac-sha1-96, hmac-md5-96 , hmac-sha1-96-etm@openssh.com and hmac-md5-96-etm@openssh.com has been added, please download the new prelease version 1.7 and check, thank you.

**Comment by kingToolbox** [comment]
Self-test passed, and this issue will be closed if no further activity occurs during the next week. If the issue is still valid just add a comment to keep it alive. Thank you.
