### ISSUE TITLE
The Chinese displayed is not readable

### ISSUE THREAD

**Issue by lnkForKing** [kingToolbox/WindTerm#509]
系统：window 7
版本：WindTerm_2.3.0_Prerelease_4_Windows_Portable_x86_64

命令窗口内中文字颜色与背景色一致，没法看
![image](https://user-images.githubusercontent.com/3646026/153814988-fa1d5e7c-8a03-4d00-a91f-dfa3a2f7e0d8.png)

菜单部分中文也看不见
![image](https://user-images.githubusercontent.com/3646026/153815178-30e81423-6f4e-4220-97ad-bd1d503a081c.png)

**Comment by lnkForKing** [comment]
改成白色主题也一样

**Comment by ViCrack** [comment]
更到最新试试 2.3.0release
Try to update to  2.3.0release
![图片](https://user-images.githubusercontent.com/18179821/153981380-411f4804-1cb9-48c4-93b7-7837854f029f.png)


https://github.com/kingToolbox/WindTerm/issues/460#issue-1108473992

**Comment by lnkForKing** [comment]
更新到WindTerm_2.3.0_Windows_Portable_x86_64了，还是一样
![image](https://user-images.githubusercontent.com/3646026/153994786-589eb3ef-6cb8-436f-9af2-67189ded865d.png)

**Comment by kingToolbox** [comment]
@lnkForKing 
Please upgrade to the latest version [WindTerm_2.3.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.3.0) as suggested, and thanks @ViCrack. 

Please let me know if you still have questions.

**Comment by kingToolbox** [comment]
This is really weird, I can't figure out why this is happening. It looks like Chinese characters are not being displayed in the tooltips correctly. However, this popup widget has been replaced by a menu in the new `WindTerm_2.4.0`, so there is no need to fix it.

Is there any other text that is not being displayed correctly, such as the other tooltips, and the output of the `echo` command you mentioned before?

**Comment by lnkForKing** [comment]
All Chinese characters are invisible in the command line window. But it can be replicated.

**Comment by ViCrack** [comment]
@lnkForKing 
我有个猜测，你是怎么更新软件的？有没把这几个文件夹都更新了。
或者你直接下载最新版本的压缩包解压到一个新目录再尝试一下？

![图片](https://user-images.githubusercontent.com/18179821/154194591-1c729202-ab32-4719-b00b-2088e0581548.png)

**Comment by lnkForKing** [comment]
@ViCrack 
我就是下载最新版本解压到一个新的目录运行的，里什么都没动

**Comment by kingToolbox** [comment]
If `WindTerm` can't display Chinese at all, I can explain it. However, it is very strange that some of the Chinese text is still being displayed in your screenshot.

Fortunately, there are still two methods you can try.

1. Open `MenuBar - Session - Preferences - Settings - Text - Font`, uncheck the `Prefer theme fonts` and set `Font family 1` to a font that supports Chinese.
2. If the above method does not work, please open `WindTerm_installed_path/qt.conf` and modify it to:
```
[Paths]
Plugins = plugins

[Platforms]
WindowsArguments = fontengine=freetype
```
Then restart `WindTerm` and check whether Chinese can be displayed correctly.

By the way, Which version of Windows operating system are you running? Is it a Chinese version?

**Comment by lnkForKing** [comment]
@kingToolbox 
Method one is worked.

I tried Method on version WindTerm_2.3.0_Prerelease_4_Windows_Portable_x86_64, and that didn't work. but the current version of WindTerm_2.3.0_Windows_Portable_x86_64 is worked.

Thank you.

**Comment by kingToolbox** [comment]
A very good news. :smile: 

I guess that the fonts installed in your system are a bit special, which makes Qt's font matching algorithm unable to find suitable Chinese fonts for rendering some Chinese characters.

Maybe Qt's font matching algorithm can be smarter in the future. But now this issue cannot be further fixed. Because the fonts installed in each system are different, I cannot preset special Chinese fonts as default. So far, only your system has encountered this problem. Please understand. Thank you.

**Comment by lnkForKing** [comment]
I understand, Let me close this issue;
