### ISSUE TITLE
Floating the window causes the shortcut to be disabled

### ISSUE THREAD

**Issue by EverythingGoesWithTheFlow** [kingToolbox/WindTerm#51]
I am trying to float the filer window, but the shortcut key for the new window is not working

**Comment by kingToolbox** [comment]
Thank you. This issuse has been confirmed and will be fixed in the next version. BTW, I have never used WindTerm this way, so I did not encounter this problem. :smile:

**Comment by kingToolbox** [comment]
The fix has been released, please download the new version [2.0.0_prerelease_3](https://github.com/kingToolbox/WindTerm/releases/tag/2.0.0) and check, thank you.

**Comment by kingToolbox** [comment]
Self-test passed in [v2.0.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.0), Please reopen this issue if it is still valid. Thank you.
