### ISSUE TITLE
Unable to log in to Cisco switches via SSH using public keys

### ISSUE THREAD

**Issue by cnkmmk** [kingToolbox/WindTerm#515]
刚才更新了2.3.0版本，登录思科交换机做测试。无法使用密钥登录，用户名密码可以登录。
密钥用xshell可以正常登录。

**Comment by kingToolbox** [comment]
Can you log in the switch using the [WindTerm_2.2.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.2) version?

**Comment by cnkmmk** [comment]
thx, I download 2.2.0, it is same problem.
