### ISSUE TITLE
Add Sponsorship to Repository

### ISSUE THREAD

**Issue by sifex** [kingToolbox/WindTerm#52]
Hey, just wanted to say I love the application! 

Can you please add the ability to Sponsor the repo, as I'd happily give money to help the development of this get better over time. Over PuTTy and other tools, I think this definitely has the ability to surpass as the default term app.

**Comment by kingToolbox** [comment]
Sorry for the late reply, I have been developing SSH ProxyCommand wholeheartedly in the last two days, which is the last unimplemented feature of the SSH protocol. After completion, all featurs of the SSH protocol are completed. I have been waiting for this day for more than ten years. 

I am very very grateful for your generosity. Your praise is my greatest reward, so please feel free to use WindTerm. Good tools need to be shared, and only sharing can make creation more valuable, just as I learned a lot from the open source community. Now WindTerm is still like a baby and needs my wholehearted care. Maybe when WindTerm is perfected, I will consider donating again. 

Please don't worry about the future of WindTerm. Developing WindTerm is my dream for many many years. I firmly believe that there is still too much room for improvement in terminals. As you have already experienced, syntax highlighting, folding, outlining, performance, etc., and there are still hundreds of unimplemented features on the todo list. I promise that I will continue to develop and make WindTerm better and better.

Once again, I express my heartfelt thanks to you for your kindness.
