### ISSUE TITLE
Feature about ssh private key storage

### ISSUE THREAD

**Issue by Lemonawa** [kingToolbox/WindTerm#523]
Sometimes, I might delete the ssh private key by mistake. So,can it NOT only store the file path of the key, store the content of the key?

**Comment by kingToolbox** [comment]
Sorry, this will cause very security issues.

Storing the content of the private key file means that you also have a copy of the private key file in `WindTerm_installed_path/profiles/default.v10/terminal/user.sessions`. When you copy `WindTerm` to other computers for use, the private key file will also be transferred, and it is difficult for you to realize it, which is very dangerous.

I recommend that you manage your private key files properly, and if they do get deleted by mistake, use a more secure local backup tool is fine.

**Comment by zeroxx1986** [comment]
This defeats the whole purpose of having a portable version of WindTerm. I'm struggling right now to set up a consistent development environment for both of my PCs, as the identity file's path is stored only, and not the content. Furthermore, environment variables are not translated either, like %SSH_KEYS_PATH%\whatever_key is not understood. I cannot make the ssh keys be stored in an identical path (on my PC it's on E:\ drive, on my laptop it's on C:\..), nor could that be expected of the users; not to mention path differences cross-platform. Having a password-based login is also not good as then i.e. VS Code asks for the password every time I connect to the host. You could argue we could have both password-based and identity file based logins simultaneously, but then that again does not provide any more security compared to storing the identity file's contents, as the password could be saved in the user.sessions file as I'm aware.
I'd leave the security issue resolution up to the users to decide what they would like to do, as long as it's implications are clear. i.e. for my use-case it's completely acceptable for me to have the key stored in a less secured manner as it's only for an internal development docker environment which has no external connectivity at all, residing on my own internal network.
