### ISSUE TITLE
Does not save path to private key with empty master password

### ISSUE THREAD

**Issue by vbortnikov** [kingToolbox/WindTerm#53]
Hi!
When I create ssh-session with empty master password the field with the private key path remains empty in saved session.
I have to enter it again next time I connect.
It always asks for the master password even if the empty password was supplied.
It would be perfect to have an option for default ssh-key for all sessions.
Thanks a lot!

**Comment by kingToolbox** [comment]
Sorry for late reply, I am working hard to prepare v2.0.0_Prerelease_3.

I have tested with the latest [v1.9.2](https://github.com/kingToolbox/WindTerm/releases) and did not find the problem you mentioned. I remember that there seems to be this problem in the very old version. Are you using the latest version and have you checked automatic login? If the automatic login is checked and the private key is correct, there is no need to re-enter as long as you successfully log in once.

Private key path has been redesigned in the development branch, and the path has a separate configuration item, like `IdentityFile in ~/.ssh/config`, and no longer depends on automatic login. This feature will be released in v2.0.0.

I think the feature of default ssh-key for all sessions you wanted is just [SSH agent forwarding](https://www.cloudsavvyit.com/25/what-is-ssh-agent-forwarding-and-how-do-you-use-it/), WindTerm supports `ssh-agent in linux` and `pageant.exe in Windows`, You can see the intro video [here](https://kingtoolbox.github.io/2020/08/22/ssh_agent_forwarding/). I will implement this feature internally in the future.

**Comment by vbortnikov** [comment]
Thanks a lot!
I downloaded v1.9.2, It works as expected.
I had the issue with v2.0.0. prerelease 2... (the item is inactive, I don't know the end)

**Comment by kingToolbox** [comment]
I am glad that this problem has been resolved. And I tested the v2.0.0_prerelease_2 and found no problems too. Is there anything I need to know more about this? Thank you.

**Comment by BortnikovaOlga** [comment]
Nop. Thanks a lot.

**Comment by vbortnikov** [comment]
Sorry, It was me. I mean BortnikovaOlga shares Chrome browser with me -)

**Comment by kingToolbox** [comment]
:smile: Anytime, and any issues are welcome.
