### ISSUE TITLE
Exit unexpectedly after config 'Jump Server'

### ISSUE THREAD

**Issue by zouwuyoung** [kingToolbox/WindTerm#532]
I config a jump server and connect to this server. Than windterm exit unexpectedly.
the version of windterm is WindTerm_2.3.0_Prerelease_1_Windows_Portable_x86_64.Only.Windows.10.11

**Comment by kingToolbox** [comment]
Sorry, I failed to reproduce this issue. Would you like to help me reproduce it once and submit the generated crash report here? The crash report is just in the current working directory after the crash, such as `8f9a5ae5-4ea2-170e-55e9b70e-05c9ab40.dmp`, you can post it as an attachment in the issue. I will analyze it and fix the problem. Thank you.

The crash report is a standard `minidump` file and does not contain any private information. You can read [this comment](https://github.com/kingToolbox/WindTerm/issues/110#issuecomment-875854346) to learn more.

**Comment by zouwuyoung** [comment]
[05d931ea-8f29-4f58-9e65-c023f24236a8.zip](https://github.com/kingToolbox/WindTerm/files/8106558/05d931ea-8f29-4f58-9e65-c023f24236a8.zip)

**Comment by zouwuyoung** [comment]
I upgrade to latest version(WindTerm_2.3.0_Windows_Portable_x86_64.zip). It wouldn't be crash. 
But I still can't config Jump Server. it shows 'Channel opening failure: channel 43 error (1) open failed". Any suggestion?

**Comment by zouwuyoung** [comment]
Probably my ssh version is too lower to use -J option.
