### ISSUE TITLE
how to upgrade with old configs

### ISSUE THREAD

**Issue by Reid00** [kingToolbox/WindTerm#537]
I want to upgrade to latest version, but i found while i open the latest version some configs (contains shortcuts, sessions, layout and so on) not sync. which file should i copy to new version?

![image](https://user-images.githubusercontent.com/38450639/154795526-96a22875-a17e-4bb3-9d7d-04916d3e2f47.png)
![image](https://user-images.githubusercontent.com/38450639/154795580-b2c5e892-08ab-4f95-be41-8a418b2c0a9d.png)

**Comment by lcmgithub** [comment]
更新说明里面说，把目录下面 profiles 文件夹复制过去

Upgrade
For Windows and Linux, copy or move the profiles folder from the old Windows/Linux version to the new Windows/Linux version and all the sessions and configuration will be restored.

For MacOS, copy or move the profiles folder from the old WindTerm.app/Contents/MacOS to the new WindTerm.app/Contents/MacOS and all the sessions and configuration will be restored.

The profiles folder is cross-platform.

**Comment by Reid00** [comment]
got it. thanks. keymaps i copy wind.keymaps also migrated.

**Comment by kingToolbox** [comment]
Sorry for the late reply.

The new [WindTerm_2.4.0_Prerelease_1](https://github.com/kingToolbox/WindTerm/releases/tag/2.4-prerelease) supports specifying the storage path of `profiles`, which makes it more convenient to transfer `profiles` to other devices. Welcome to download and use it. You can read the `Upgrade` section of the release page to learn how to upgrade.Thank you.
