### ISSUE TITLE
 I hide the menu bar. How can I  restore?

### ISSUE THREAD

**Issue by Kendarou** [kingToolbox/WindTerm#543]
I hide the menu bar. And close all the windows. How can I  restore ?

![Snipaste_2022-02-20_20-49-27](https://user-images.githubusercontent.com/13276572/154843310-805d402b-b770-4fae-8465-8847c7615bd9.png)

**Comment by miskin-lee** [comment]
how do you solve this problem? I encountered a problem same as you

**Comment by GodRuiAn** [comment]
> how do you solve this problem? I encountered a problem same as you

If you use Mac: Opt + W, Opt + M
If you use Windows: Alt + W, Alt + M

**Comment by miskin-lee** [comment]
> > how do you solve this problem? I encountered a problem same as you
> 
> 
> 
> If you use Mac: Opt + W, Opt + M
> 
> If you use Windows: Alt + W, Alt + M

thanks！i have solved this problem right now.
