### ISSUE TITLE
MacOS version cannot found commands

### ISSUE THREAD

**Issue by tsui603** [kingToolbox/WindTerm#545]
![WX20220221-144401](https://user-images.githubusercontent.com/25866452/154902737-c9140c96-ce48-48cd-97c7-255e7589711e.png)

求教 如何解决呢

**Comment by kingToolbox** [comment]
Please check the enviroment variable `PATH`, and you can compare it with the `PATH` in the macOS's terminal. You can read [How to Fix “Command Not Found” Errors in Mac Command Line](https://osxdaily.com/2018/05/24/command-not-found-mac-terminal-error-fix/) to learn more. In addition, you can set environment variables in the `Session Dialog - Shell - Shell - Process - Environment variables`, thank you.

**Comment by tsui603** [comment]
> 

谢谢，问题解决了，为什么不把回话设置，放到设置里面统一管理呢，（之前在找类似设置没找到）

**Comment by kingToolbox** [comment]
Good news, is it a path problem?

There are many settings for the session, so it is designed as a separate dialog box.

**Comment by tsui603** [comment]
> 

是的，把terminal里面的变量复制进去就解决了！

**Comment by kingToolbox** [comment]
Ok, this issue has been solved and will be closed. Welcome to continue submitting new feature requests and bugs, thank you.
