### ISSUE TITLE
[bug] Transfer items cannot be manipulated after disconnecting the session

### ISSUE THREAD

**Issue by lzpong** [kingToolbox/WindTerm#547]
连接断开之后,文件传输界面上的项就无法操作
连接断开之后,拖动本地文件到文件管理窗口会在传输界面增加一项任务,但是不能传输,也不能暂停或删除任务
连接断开之后,之前成功项的也无法删除

**Comment by kingToolbox** [comment]
If a session **disconnected**, its corresponding `filer` will also be **closed**. So this is not a bug.

**Comment by kingToolbox** [comment]
I re-tested and confirmed that there is a bug that transfer items cannot be deleted after disconnecting the session. I will fix it, please stay tuned, thank you.

**Comment by kingToolbox** [comment]
I re-tested and confirmed that there is a bug that transfer items cannot be deleted after disconnecting the session. I will fix it, please stay tuned, thank you.

**Comment by kingToolbox** [comment]
I am happy to inform you that [WindTerm_2.4.0_Prerelease_2](https://github.com/kingToolbox/WindTerm/releases/tag/2.4-prerelease) has been released and this issue has been fixed. Please download and check it. If there are still bugs, please let me know, thank you.

**Comment by lzpong** [comment]
ok , thks!
