### ISSUE TITLE
ProxyCommand 2.0 prerelease 3

### ISSUE THREAD

**Issue by Twink-Polar** [kingToolbox/WindTerm#55]
Downloaded the latest 2.0.0 prerelease today. 

I have SSH config that WindTerm picked up, but i don't think the ProxyCommand element was imported. I tried connecting to the SSH server but no joy. I looked at the properties of the entry via WindTerm and couldn't see a corresponding piece of information about ProxyCommand. The other pieces of information like HostName, User and IdentityFile are all displayed correctly.

An example of my SSH config:

---------------------------------------
Host tor-myserver
    HostName xxxxxxxxxxxxxx.onion
    User xxxxx
    IdentityFile xxx/xxx/xxxx
    ProxyCommand nc -X 5 -x 127.0.0.1:9050 %h %p
    CheckHostIP no
    VerifyHostKeyDNS no

----------------------------------------

Is there a way for me to check the information that gets read by WindTerm to see if it's seeing the ProxyCommand?

**Comment by kingToolbox** [comment]
Really happy to see you again. I was thinking about waiting for the introduction video to be finished before telling you to use the new version in the discussions. :smile: 

In WindTerm, it is very convenient to use jump servers/hosts now. Take your needs as an example, you only need to do the following steps:

- Create a new SSH session and set the host to 127.0.0.1 and the port to 9050.
- Open the property dialog of the session you want to use jump server. In `SSH - Proxy`, check `Jump Servers` and select `127.0.0.1` in the combo box below.
- Open the session and enjoy.

Strictly speaking, ProxyCommand is not implemented in the new version. ProxyCommand refers to starting an external shell program and redirecting stdin and stdout to the ssh channel. But ProxyCommand usually used to use a jump server or proxy server. So I simplified the design after I completed the first implementation of ProxyCommand. and it should be easier to use.

For import OpenSSH configuration, not all configurations are supported. In this case, it will be automatically imported only when the alias is used in ProxyCommand, such as:

```
Host tor-jump-server
   Hostname 127.0.0.1
   Port 9050
Host tor-myserver
   ProxyCommand nc tor-jump-server %h %p
   ...
```

**Comment by kingToolbox** [comment]
I reread the PorxyCommand in your SSH config and find that what your need is not a jump server but a socks5 proxy to use tor. You just need open the session property dialog and just follow the settings below.
![image](https://user-images.githubusercontent.com/51009775/109848207-f6084400-7c8a-11eb-8605-87933b58a123.png)

**Comment by Twink-Polar** [comment]
Thank you for the super quick response!

I think i've been checking for prerelease 3 nearly every day since the last prerelease lol.

I'll give the socks proxy settings a go.

**Comment by kingToolbox** [comment]
Sorry to keep you waiting for so many days.

As I said, after I finished the first design in mid-February, I realized that users need to understand the meaning of `ssh -q -x -W %h:%p` or `ssh -J` to use it correctly because it relied heavily on ssh.exe. So I redesigned a simple and elegant solution, and spent a lot of time to modify the framework to adapt to the new design. I think the redesign is worthwhile. I always hope WindTerm is simple enough to use.

If you encounter problems with proxy settings, just tell me and I will improve it in the next version. If nothing else, the next version will be the stable v2.0.0. From v2.0.0, WindTerm will finally become a full-featured SSH client, because all the main SSH features have been implemented.

So let us create some different features that have never appeared in other terminals in the future. :smile:

**Comment by Twink-Polar** [comment]
Socks proxy setting worked like a charm, once i set the correct path for the identityFile.

SFTP functioned as expected.

Thank you for your help.

**Comment by kingToolbox** [comment]
Thank you for your verification. This is really good news. I will keep this open until the stable version is released. If anyone has questions about ProxyCommand, they can see this.

Of course, welcome to continue submitting new issues and feature requests. Thank you! 😃

**Comment by kingToolbox** [comment]
The stable version [v2.0.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.0) has been finally released, thank you!
