### ISSUE TITLE
Can the tab title display the host name?

### ISSUE THREAD

**Issue by hisune** [kingToolbox/WindTerm#554]
Many hosts are now managed by jumpserver, so that all hosts can only display the name of jumpserver, and it is impossible to intuitively determine which server this is by tab name. Especially when using the functions related to synchronous input, it is impossible to tell which server is joining the group. 

![微信截图_20220223115039](https://user-images.githubusercontent.com/7941669/155258898-890ced3b-a48b-4a5c-88eb-a745011dd876.png)

![微信截图_20220223115101](https://user-images.githubusercontent.com/7941669/155258904-902a8573-153a-41b5-85b3-1cec9794f5e7.png)

Taking the screenshot above as an example, you can display `jump` as: "jump-host1", "jump-host2", etc. (`host1` and `host2` are the actual hostnames) to distinguish between different servers.

But people who don't use jumpserver may not need this feature. He can use it as a configuration item to decide whether to turn it on.

**Comment by kingToolbox** [comment]
Sorry, I don't understand why using `JumpServer` would cause related sessions to share the name of the `JumpServer`. You can read [Network Proxy / Jump Server](https://kingtoolbox.github.io/2021/03/11/proxy-jump-server/) first to see if there is a better way to use `JumpServer`, thank you.

**Comment by hisune** [comment]
Because I only used one server configuration, I don't need to manage the connections of all servers in WindTerm, but leave it to the jumpserver to manage. I just need to enter the jumpserver and select the next server I want to enter. So all servers I enter through the ssh configuration of jumpserver will display the same name.

![微信截图_20220223140141](https://user-images.githubusercontent.com/7941669/155269004-322f0e42-d2ce-4bc7-9c2a-3fa79e8abe15.png)

The jumpserver I use is this: https://github.com/jumpserver/jumpserver/blob/master/README_EN.md

**Comment by kingToolbox** [comment]
Subsequent versions will use the `group name` and the `tab's index` to identify a session, but this is not perfect as the `tab's index` may change due to actions such as dragging and dropping.

Your use is even more special. Since `WindTerm` is a generic terminal, it is almost impossible to understand the text in the session, so there is no way to extract `host1` or `host2`.

The only way I can think of right now is to rename the tabs manually. You can read [Tabbar / Rename Tab](https://kingtoolbox.github.io/2020/06/20/tabbar-rename-tab/) to learn more.

**Comment by hisune** [comment]
Xshell can display the host name to the title page. I don't know how it is implemented, as shown in the figure below:

![微信截图_20220223163343](https://user-images.githubusercontent.com/7941669/155284875-b2cc6978-4558-4669-b7e1-ac269ddfb1ae.png)



> Subsequent versions will use the `group name` and the `tab's index` to identify a session, but this is not perfect as the `tab's index` may change due to actions such as dragging and dropping.
> 
> Your use is even more special. Since `WindTerm` is a generic terminal, it is almost impossible to understand the text in the session, so there is no way to extract `host1` or `host2`.
> 
> The only way I can think of right now is to rename the tabs manually. You can read [Tabbar / Rename Tab](https://kingtoolbox.github.io/2020/06/20/tabbar-rename-tab/) to learn more.

**Comment by kingToolbox** [comment]
Please open the `Session Settings` dialog for your session, and check `SSH - Window - Change the tab title`, then you will get what you want.

**Comment by hisune** [comment]
> Please open the `Session Settings` dialog for your session, and check `SSH - Window - Change the tab title`, then you will get what you want.

Thanks, this is exactly what I want.

**Comment by RangerWolf** [comment]
> Please open the `Session Settings` dialog for your session, and check `SSH - Window - Change the tab title`, then you will get what you want.

似乎跟xshell比起来行为不是非常一样。我用的2.5.0版本， 看起来会显示hostname以及所在的目录。
而所在的目录地址通常都比较长。。。

不知道是否可以只显示hostname？
