### ISSUE TITLE
High CPU cost while showing docker status

### ISSUE THREAD

**Issue by lingex** [kingToolbox/WindTerm#558]
I have several containers on a remote server, and when I run `docker stats` in the session, it leads to high CPU usage (> 20%). 
![image](https://user-images.githubusercontent.com/13662998/155321736-22b3bccc-0ad2-4cd1-be98-4fff14585f91.png)

Version: WindTerm_2.3.0_Windows_Portable_x86_64
OS: Windows 10
CPU: i7-9700

**Comment by lingex** [comment]
After reopening the session, this issue never appears.

**Comment by kingToolbox** [comment]
Thank you for the additional information. I also did a test and nothing like this happened. I don't think this has much to do with `WindTerm`, because `WindTerm` is passive and doesn't actively refresh the server. But I will watch for a while to see if the same issue occurs again.

**Comment by lingex** [comment]
Thank you for your job, and I will also keep focusing on if it will happen again.

**Comment by kingToolbox** [comment]
If it reoccurs, please let me know and I will investigate the issue in detail.

**Comment by lingex** [comment]
I think I found something. It is related to the running time, in the last weekend, I kept the session monitoring, the CPU usage reached more than 50% today, and the MEM usage is more than 2GB (another problem). 

At this point, rerunning the command won't solve the problem, but `clear` will. 

Today I checked it again, in the past few hours, the CPU usage going higher and higher.

**Comment by lingex** [comment]
Thank you for your work, seems great. I'll try that later.

**Comment by kingToolbox** [comment]
Ok, please don't forget to set `Scrollback Lines` in the session's `Session Setting Dialog - SSH - Window - Lines of scrollback`. :smile:

**Comment by lingex** [comment]
After hours of several times tests, I believe it works well by setting the `Scrollback Lines`, which will take effect in a new session.

By the way, the `docker stats` is so weird. 😄
