### ISSUE TITLE
How to customize keyword highlight in the session?

### ISSUE THREAD

**Issue by darkhandz** [kingToolbox/WindTerm#560]
Current `linux` system highlight looks good, but I want to add more keyword(per session), Is there a regex to customize?

**Comment by kingToolbox** [comment]
Sorry for the late reply.

You can open the rule below in `WindTerm_install_path\terminal\schemes\linux\linux.lexer` and add the keywords you want to highlight. The grammar rules are similar to those of `vscode`. I believe it should be easy for you.

If you still have questions, don't hesitate to ask.
