### ISSUE TITLE
How do I turn off the master password setting

### ISSUE THREAD

**Issue by 0nlyuAarOn** [kingToolbox/WindTerm#565]
How do I turn off the master password setting，How do I turn off the master password setting？
![image](https://user-images.githubusercontent.com/27802843/155509615-4466f2c6-4490-45ee-bced-5c7c97d30266.png)

**Comment by kingToolbox** [comment]
You need to set the master password to an empty string to turn it off. Since you have already set a master password, please follow [Change Master Password ](https://kingtoolbox.github.io/2021/04/23/change-master-password/) to reset the password to an empty string.
