### ISSUE TITLE
Where can I change fonts in terminal?(solved)

### ISSUE THREAD

**Issue by ZiangGithub** [kingToolbox/WindTerm#59]
Hi , WindTerm developer! I can't find where to change fonts in terminal.

Could you please give some instructions about changing fonts?

有人知道怎么改字体吗。。。

**Comment by Liuhongdan** [comment]
Only know that Ctrl + middle-mouse-button can zoom the font.
View --> Zoom

**Comment by ZiangGithub** [comment]
> Only know that Ctrl + middle-mouse-button can zoom the font.
> 
> View --> Zoom

yes, I've noticed that.

**Comment by hongnod** [comment]
好似暂时还不支持改字体，现有字体个人觉得还行。

**Comment by kingToolbox** [comment]
WindTerm supports customization of almost everything. The detailed configuration file description can be read [here]().

For example, If you are currently using the dige-black theme and want to modify the font, you only need to open the configuration file `windterm-install-path/global/themes/dige-black/scheme.theme` and search `text.default`:
``` json
{
	"name": "text.default",
	"style": {
		"foreground": "#F8F8F2",
		"background": "#1c1c1c",
		"fontFamily": "Roboto Mono, Fira Code Retina, Lucida Sans Typewriter, Lucida Console, Monoca",
		"fontSize": 10
	}
}
```
Then modify the `fontFamily` to any font you want and restart WindTerm. In future versions, the font setting will be independent, allowing different themes to share the same font settings.

Starting from the version v2.2, the setting interface will be gradually provided to facilitate modification of the configuration. It is expected after April.
