### ISSUE TITLE
How to change the default text editor ?

### ISSUE THREAD

**Issue by mishka81** [kingToolbox/WindTerm#598]
I set my default text editor to Notepad++, but I'd like to change.
I can't see any option on this nor documentation.

**Comment by db-one** [comment]
![image](https://user-images.githubusercontent.com/20243226/158494743-2c2eabdb-6523-4742-a92a-14cae57fb56e.png)
Although the language is not the same, you can correspond to the location

**Comment by db-one** [comment]
And after testing, this can only be clicked on if the server is connected to set

**Comment by mishka81** [comment]
Thank you so much !
