### ISSUE TITLE
will it support chinese in the future.

### ISSUE THREAD

**Issue by lain-github** [kingToolbox/WindTerm#6]
thanks for your products.

**Comment by kingToolbox** [comment]
WindTerm will support multi-languages (includes chinese) in the future, please keep attation and thanks for your recognition.

**Comment by lain-github** [comment]
ok, thanks.

**Comment by kingToolbox** [comment]
The new [WindTerm_2.2.0_Prerelease_4](https://github.com/kingToolbox/WindTerm/releases/tag/2.2-prerelease) version has been released and Chinese interface has been supported, please download and check it, thank you.
