### ISSUE TITLE
默认的锁屏密码是多少

### ISSUE THREAD

**Issue by ZouTaooo** [kingToolbox/WindTerm#602]
第一次用 用着用着锁屏了。。还打不开，还跑着的程序呢

**Comment by 107295472** [comment]
默认没有密码

**Comment by kingToolbox** [comment]
Sorry for the late reply.

If you have not set a master password, the default master password is empty. You can read [Master Password](https://kingtoolbox.github.io/2021/03/11/protection-master-password/) and [Change Master Password](https://kingtoolbox.github.io/2021/04/23/change-master-password/) to learn more. 

@107295472
Thank you for your help.
