### ISSUE TITLE
Help translating into Chinese

### ISSUE THREAD

**Issue by Lemonawa** [kingToolbox/WindTerm#607]
Hello, I would like help translating into Chinese, what should I do?

**Comment by hisune** [comment]
Simplified Chinese can already be selected in the `Preferences -> Settings -> appearance` configuration.

**Comment by Lemonawa** [comment]
> Simplified Chinese can already be selected in the `Preferences -> Settings -> appearance` configuration.

Hmm, i meant, i want to improve Chinese translations

**Comment by Lemonawa** [comment]
> `WindTerm\global\locales` directory `zh-CN.Locale` file

okay, Thank you
