### ISSUE TITLE
清除屏幕功能无效

### ISSUE THREAD

**Issue by jamswell** [kingToolbox/WindTerm#610]
你好，我发现目前版本（2.3.1和2.4.0）中点清除回滚和全部清楚无效，这个是我操作不对么？

**Comment by jamswell** [comment]
![image](https://user-images.githubusercontent.com/9508548/159452558-18c81581-08d3-4fae-a81b-9fd2200b5a4b.png)

**Comment by kingToolbox** [comment]
If your device is a `dumb` device, please use `dumb` system, not `none` system, which can be set in the `Session Settings` dialog.
