### ISSUE TITLE
About the optimization of the menu bar

### ISSUE THREAD

**Issue by MilkTeaNo7** [kingToolbox/WindTerm#614]
![image](https://user-images.githubusercontent.com/74584122/159615887-e28e6374-6f3a-4d51-8de3-8e60242332fa.png)

As shown above, the menu after version 2.40 has only one button and cannot be displayed directly at the top as before, I don't know if there is a place to set it, and if so can there be an additional option to switch the menu display?

Thank you!

**Comment by kingToolbox** [comment]
No, there are no related settings for now. Menu items take up a lot of `Alt+...` shortcut keys, and designing it as a single item makes more shortcut keys available. For example, tabs can now be activated using `Alt+1`, `Alt+2`, etc.

If you really need the old style menu bar, you can open the `WindTerm_installed_path/terminal/configs/menu.config` and modify it as follows.

Replace:
``` json
	"Kit" : [
		{ "Menu" : "Men&u", "Actions" : [
			{ "Action" : "Terminal.NewSession" },
			{ "Action" : "Application.NewWindow" },
			{ "Separator" : true },
			{ "Menu" : "&Preferences", "Actions" : [
				{ "Action" : "Window.OpenSettings" },
				{ "Action" : "Terminal.OpenSessionSettings" }
			]},
			{ "Separator" : true },
			{ "Menu" : "&Session" },
			{ "Menu" : "&Edit" },
			{ "Menu" : "Searc&h" },
			{ "Menu" : "Selectio&n" },
			{ "Menu" : "&Goto" },
			{ "Menu" : "&View" },
			{ "Menu" : "&Mode" },
			{ "Menu" : "&Tool" },
			{ "Menu" : "&Window" },
			{ "Menu" : "&Help" }
		]}
	],
```
with:
``` json
	"Kit" : [
		{ "Menu" : "Session" },
		{ "Menu" : "Edit" },
		{ "Menu" : "Search" },
		{ "Menu" : "Selection" },
		{ "Menu" : "Goto" },
		{ "Menu" : "View" },
		{ "Menu" : "Mode" },
		{ "Menu" : "Tool" },
		{ "Menu" : "Window" },
		{ "Menu" : "Help" }
	],
```
and restart.

**Comment by kingToolbox** [comment]
Hello, the menu bar has been restored in the new [WindTerm_2.4.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.4.0), welcome to download and use it. Thank you.
