### ISSUE TITLE
Icon issue when creating a new session

### ISSUE THREAD

**Issue by mybdye** [kingToolbox/WindTerm#618]
When creating a new session(SSH), the icon next to the label cannot be changed, icons can only be reselected when modified.

version 2.3.1 on Mac
![tutieshi_640x395_15s](https://user-images.githubusercontent.com/21116709/159833115-d20a425d-0b0f-4f52-aedb-784dfa637e4d.gif)

**Comment by kingToolbox** [comment]
Thank you. I have confirmed this bug and will fix it in the `WindTerm_2.4.0_Prerelease_2` or `WindTerm_2.4.0_Prerelease_3` version, please stay tuned.

**Comment by kingToolbox** [comment]
I am happy to inform you that [WindTerm_2.4.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.4.0) has been released and this bug has been fixed. Please download and check it, thank you.

**Comment by mybdye** [comment]
good news
