### ISSUE TITLE
Can't customize file open mode in filer bar

### ISSUE THREAD

**Issue by Xuanyaz** [kingToolbox/WindTerm#620]
Right click on file in filer bar.
can see two option associate with open file, these are "open" and "open with default editor".
but once click "open with default editor" option and select the default editor ,I can't find way to change it.
Does it haven't this change function or I won't find this?

**Comment by kingToolbox** [comment]
If you want to change the default editor, please click the `More` button in the toolbar in the `filer` pane, which is the last button, and select `Set default editor...` in the pop-up menu.

**Comment by Xuanyaz** [comment]
thx you, I found it

**Comment by Xuanyaz** [comment]
> If you want to change the default editor, please click the `More` button in the toolbar in the `filer` pane, which is the last button, and select `Set default editor...` in the pop-up menu.

thx you, I found it

**Comment by yunnysunny** [comment]
![image](https://github.com/user-attachments/assets/3458a40c-2cff-453a-9116-44d639de35e2)
More is the button, in the red frame.
