### ISSUE TITLE
-bash: rx: command not found?

### ISSUE THREAD

**Issue by joshatt** [kingToolbox/WindTerm#622]
Following tutorial, I tried download single file with "xModem" (from local harddisk to VPS), then I got:
-bash: rx: command not found
Does this rely on anything?  or it just works on local ssh?

**Comment by lcmgithub** [comment]
VPS Server Installation Package `lrzsz`

**Comment by joshatt** [comment]
> VPS Server Installation Package `lrzsz`

Thank you so much.
