### ISSUE TITLE
升级为新版，原来的所有会话全没了

### ISSUE THREAD

**Issue by prestu** [kingToolbox/WindTerm#625]
这个操作，太闹心了吧，保存了好多会话，升级后一个都没了，还得一个一个手动再添加一遍，太影响工作效率了

**Comment by prestu** [comment]
@kingToolbox 您好，这个修复了吗，什么时候可以更新这个bug

**Comment by syuraking** [comment]
2.40下载区域不是写明了怎么旧版转换到新版，配置文件怎么移动？？？

**Comment by prestu** [comment]
> 2.40下载区域不是写明了怎么旧版转换到新版，配置文件怎么移动？？？

mac没有2.4，还有就是我下载软件必须把文字啥的全看完吗，你每次下载微信QQ还看看说明书？

**Comment by lcmgithub** [comment]
作者版本有有更新说明，建议看一下，这是个开源软件，理解一下作者。

`For MacOS, copy or move the profiles folder from the old WindTerm.app/Contents/MacOS to the new WindTerm.app/Contents/MacOS and all the sessions and configuration will be restored.`

**Comment by prestu** [comment]
> 作者版本有有更新说明，建议看一下，这是个开源软件，理解一下作者。
> 
> `For MacOS, copy or move the profiles folder from the old WindTerm.app/Contents/MacOS to the new WindTerm.app/Contents/MacOS and all the sessions and configuration will be restored.`

好滴，谢谢了，确实没注意到哦抱歉

**Comment by lcmgithub** [comment]
如果问题已解决，这个 issue 就关闭掉吧。

**Comment by prestu** [comment]
> 如果问题已解决，这个 issue 就关闭掉吧。
