### ISSUE TITLE
cat file is missing spaces

### ISSUE THREAD

**Issue by jan-bar** [kingToolbox/WindTerm#639]
I use ssh.exe and windterm to log in to the same server, but ssh.exe can handle the character '\0' in the string normally

![image](https://user-images.githubusercontent.com/14202095/162103553-8383a2f4-03e5-40c3-8888-ef38f85d5b44.png)

I hope it can be modified, otherwise it will be troublesome for me to copy the command line, thank you

**Comment by kingToolbox** [comment]
Sorry for the late reply. Recently I have been focusing on developing [WindTerm_2.4.0_Prerelease_2](https://github.com/kingToolbox/WindTerm/releases/tag/2.4-prerelease).

The handling of `WindTerm` is correct, while `OpenSSH` is not. You can read the description on [wikipedia - Null character](https://en.wikipedia.org/wiki/Null_character):

> The original meaning of this character was like [NOP](https://en.wikipedia.org/wiki/NOP_(code))—when sent to a [printer](https://en.wikipedia.org/wiki/Computer_printer) or a [terminal](https://en.wikipedia.org/wiki/Computer_terminal), it has no effect (some terminals, however, incorrectly display it as [space](https://en.wikipedia.org/wiki/Space_(punctuation))).

You can replace `NUL` with `Space` by `sed` before `cat`: `cat /proc/1/cmdline | sed 's/\x00/\x20/g'`.

**Comment by jan-bar** [comment]
> Sorry for the late reply. Recently I have been focusing on developing [WindTerm_2.4.0_Prerelease_2](https://github.com/kingToolbox/WindTerm/releases/tag/2.4-prerelease).
> 
> The handling of `WindTerm` is correct, while `OpenSSH` is not. You can read the description on [wikipedia - Null character](https://en.wikipedia.org/wiki/Null_character):
> 
> > The original meaning of this character was like [NOP](https://en.wikipedia.org/wiki/NOP_(code))—when sent to a [printer](https://en.wikipedia.org/wiki/Computer_printer) or a [terminal](https://en.wikipedia.org/wiki/Computer_terminal), it has no effect (some terminals, however, incorrectly display it as [space](https://en.wikipedia.org/wiki/Space_(punctuation))).
> 
> You can replace `NUL` with `Space` by `sed` before `cat`: `cat /proc/1/cmdline | sed 's/\x00/\x20/g'`.

Thank you for your reply, it seems that I can only operate according to the plan you provided.
