### ISSUE TITLE
Alt+Enter is not easy to use 

### ISSUE THREAD

**Issue by 107295472** [kingToolbox/WindTerm#64]
WindTerm - Sender Pane / Keyboard Shortcuts

**Comment by kingToolbox** [comment]
Hello, do you have any good suggestions? In addition, you can replace it with any shortcut key you like. Just open `WindTermInstallPath/global/wind.keymaps` and modify the "keys".
``` json
  { "keys": "<Alt+Enter>",
    "modes": "normal, command, widget",
    "when": "window.isScope('terminal.sender.*')",
    "action": "SenderPane.StartSender"
  }
```

**Comment by 107295472** [comment]
Thank you. It's easy to change to Ctrl + enter
