### ISSUE TITLE
Strange string when windterm restart from crash

### ISSUE THREAD

**Issue by chen1195585098** [kingToolbox/WindTerm#642]
When windterm crashed and restart, some strange string is occured in Label and title, which are different from what they should be.
![image](https://user-images.githubusercontent.com/25813537/162344392-f93a6246-afa2-433d-9790-b02fc6ee0f53.png)

**Comment by kingToolbox** [comment]
Sorry for the late reply. Recently I have been focusing on developing [WindTerm_2.4.0_Prerelease_2](https://github.com/kingToolbox/WindTerm/releases/tag/2.4-prerelease).

This usually happens after a crash. Possible scenarios are:
- Start `WindTerm`.
- Delete some **currently open sessions** in `Session Pane`.
- Make it crash or kill it with task manager.
- Restart `WindTerm`.

Then you can see the strange strings in the screenshot. The reason for this is that `WindTerm` tries to load the history of all last open sessions at startup after a crash. But these sessions have been deleted, so there is no way to restore their names, only their internal uuids. If it is a normal exit, `WindTerm` will do special processing in the history record for the deleted sessions that are still open when it exits. But the crash prevents this processing.

Overall it's not a bug, you just need to close these tabs and you will never see them again.

**Comment by chen1195585098** [comment]
Thanks, it is indeed helpful.
