### ISSUE TITLE
How to expand the main menu?

### ISSUE THREAD

**Issue by wsl-github** [kingToolbox/WindTerm#647]
2.4版本当中的菜单栏把所有的工具都隐藏了,这个怎么展开

**Comment by vc5** [comment]
快捷键`ALT+W,ALT+M`恢复
https://github.com/kingToolbox/WindTerm/issues/386

**Comment by kingToolbox** [comment]
@wsl-github 
Do you mean the menu items have been combined into one item? This is a test feature of version `WindTerm_2.4.0_Prerelease`, and I will restore the previous configuration in the official version. In addition, you can also refer to [this comment](https://github.com/kingToolbox/WindTerm/issues/614#issuecomment-1075932216) to modify it yourself.

**Comment by kingToolbox** [comment]
Hello, the menu bar has been restored in the new [WindTerm_2.4.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.4.0), welcome to download and use it. Thank you.
