### ISSUE TITLE
Suggestion: Mention 'How to install' above in the readme.

### ISSUE THREAD

**Issue by gerardog** [kingToolbox/WindTerm#653]
Hi,
The readme doesn't mention that WindTerm is available in Scoop/Extras.
```
scoop bucket add extras
scoop install windterm
```
Or Chocolatey. 

Users are more likely to try an app if they find it easy to install, or in my case if I know that it is Portable.

**Comment by kingToolbox** [comment]
Thanks for the great suggestion, I will add `Scoop` and `Chocolatey` in the next version release notes. it should help some users to install `WindTerm` easier. 

It's just that the current version in the `Scoop`, `Chocolatery` is generally behind the released version and the latest version cannot be installed.

**Comment by gerardog** [comment]
In my experience scoop is only 8 hours behind approximately, when the manifest includes auto update.
For Chocolatey, maybe you can ask in their chat how to get promoted to a trusted package. That really accelerates the moderation process.

**Comment by kingToolbox** [comment]
Thank you for the explanation, I am also grateful that @Verbalinsurection has made `WindTerm` validated in `Chocolatey` and uploaded the latest `2.3.1` version. I think there should be more installation methods from the next version. :smile:

**Comment by gerardog** [comment]
Glad my voice was heard. 😉

**Comment by kingToolbox** [comment]
You are welcome.
