### ISSUE TITLE
Serious error, WindTerm_2.4.0_Prerelease_2 can't use rz, sz anymore

### ISSUE THREAD

**Issue by xzhuiz** [kingToolbox/WindTerm#656]
Serious error, WindTerm_2.4.0_Prerelease_2 can't use rz, sz anymore

**Comment by kingToolbox** [comment]
My mistake. This bug has been confirmed and fixed in the `WindTerm_2.4.0_Prerelease_3` version. And you can temporarily fix this bug by following the steps below.

- Find the corresponding configuration file according to your session's Term, for example, if Term is xterm-256color, then the file is WindTerm_installed_path/terminal/terms/xterm-256color.term.

Change the lines:
> 		| (?<IgnoreControlCharacter>                                                 [\\x01-\\x04\\x06\\x10-\\x1a\\x1c-\\x1f]) # SOH, STX, ETX, EOT, ACK, DLE, DC1, DC2, DC3, DC4, NAK, SYN, ETB, CAN, EM, SUB, FS, GS, RS, US
> 		| (?<CheckControlCharacter>                      \\e  [\\x20-\\xff]{0,9}+                    [\\x00-\\x1a\\x1c-\\x1f]) # Control Characters Inside ESC Sequences
> 		| (?&CAN) (
> 			  (?<ZmodemSend>                       B010{6}.{6})
> 			| (?<ZmodemReceive>                    B000{6}0{6})
> 			)                    ((\\r\\x00?)?(\\n|\\x8a)\\x11)
> 		| (?<ModemClose>                    \\x18{10}\\x08{10})

to:
> 		| (?&CAN) (
> 		  	(?<ZmodemSend>                       B010{6}.{6})
> 			| (?<ZmodemReceive>                    B000{6}0{6})
> 			)                    ((\\r\\x00?)?(\\n|\\x8a)\\x11)
> 		| (?<ModemClose>                    \\x18{10}\\x08{10})
> 		| (?<CheckControlCharacter>                       \\e [\\x20-\\xff]{0,9}+                    [\\x00-\\x1a\\x1c-\\x1f]) # Control Characters Inside ESC Sequences
> 		| (?<IgnoreControlCharacter>                                                 [\\x01-\\x04\\x06\\x10-\\x1a\\x1c-\\x1f]) # SOH, STX, ETX, EOT, ACK, DLE, DC1, DC2, DC3, DC4, NAK, SYN, ETB, CAN, EM, SUB, FS, GS, RS, US

If you have any question, please tell me, thank you.

**Comment by kingToolbox** [comment]
I am happy to inform you that [WindTerm_2.4.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.4.0) has been released and this bug has been fixed. Please download and check it, thank you.

**Comment by xzhuiz** [comment]
Yes, it's all ok
Thanks for this awesome tool

**Comment by kingToolbox** [comment]
Thank you for your feedback. This issue has been solved and will be closed. Welcome to continue submitting new feature requests and bugs. :smile:
