### ISSUE TITLE
How to copy the IP of the current session?

### ISSUE THREAD

**Issue by xiamy-SumMer** [kingToolbox/WindTerm#658]
能快捷的复制当前IP吗？找了半天都没找到，只能复制当前的URL。如果能复制当前服务器IP还是一个很便捷的操作的

**Comment by kingToolbox** [comment]
If the `Host` of your session is a `IP`, then you can directly copy it by the `Right-click menu - Copy Session Name` of the session tab.

**Comment by xiamy-SumMer** [comment]
My session host is not IP

**Comment by kingToolbox** [comment]
I am happy to inform you that [WindTerm_2.4.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.4.0) has been released and this feature has been implemented. Please click the `Info` button in front of the address bar to view and copy the session's IP in the pop-up panel. thank you.

**Comment by xiamy-SumMer** [comment]
thanks
