### ISSUE TITLE
Cannot run on the Windows Server 2016

### ISSUE THREAD

**Issue by pam955** [kingToolbox/WindTerm#661]
Hi 
     I cannot run the windTerm on my Windows Server 2016 PC, is there any work around for the Windows Server OS?

![image](https://user-images.githubusercontent.com/55932732/163660288-9a884f73-b03b-4edc-a929-135562923fd5.png)

![image](https://user-images.githubusercontent.com/55932732/163660275-3586ecca-33bf-4bb0-a44a-ed8e49affd32.png)

**Comment by zhongzhichun** [comment]
应该是缺少一些库导致的，装这个修复一下http://blog.csdn.net/vbcom/article/details/6962388，我在win server 2012用这个修复后就能运行了

**Comment by pam955** [comment]
> 

Thanks very much, it works! 
非常感谢！
