### ISSUE TITLE
Homebrew support

### ISSUE THREAD

**Issue by chaos-cn** [kingToolbox/WindTerm#662]
MacOS
Publishing via homebrew might be a good idea

**Comment by kingToolbox** [comment]
Thanks for your suggestion. I know this would be a good way to install `WindTerm`. But I really don't have time to maintain such a source, so I'll just have to see if there are contributors willing to do it.

**Comment by chaos-cn** [comment]
> Thanks for your suggestion. I know this would be a good way to install `WindTerm`. But I really don't have time to maintain such a source, so I'll just have to see if there are contributors willing to do it.

Done!
https://github.com/Homebrew/homebrew-cask/pull/122439
