### ISSUE TITLE
The cursor will not blink.

### ISSUE THREAD

**Issue by ssmmtt** [kingToolbox/WindTerm#668]
![image](https://user-images.githubusercontent.com/16244320/163796762-f43f627e-1342-4b17-9199-3a446a62eed7.png)
![image](https://user-images.githubusercontent.com/16244320/163796815-f04e0570-82de-4de0-854a-69571d554f55.png)
Set the cursor to blink, but it doesn't actually take effect.

**Comment by kingToolbox** [comment]
The global `Settings` dialog just provides settings for the cursor property. Each session has its own cursor, so you need to set the cursor in the `Session Settings` dialog:

![image](https://user-images.githubusercontent.com/51009775/163801902-e6a1fae5-9614-4d8d-9dc9-97d895039ead.png)

**Comment by ssmmtt** [comment]
Oh, it worked. It would be nice to have a default session setting.

**Comment by kingToolbox** [comment]
There is already a default session configuration `WindTerm_Profiles_Path/terminal/configs/session.config`, but there is no time to develop the settings interface, you can modify it manually.

Too many features have been completed, but there is no settings interface, such as shortcut key customization. I will implement them in subsequent releases. Please stay tuned, thank you.
