### ISSUE TITLE
Can't type upper case characters in Windows -> WSL -> vim

### ISSUE THREAD

**Issue by tex** [kingToolbox/WindTerm#675]
$SUBJ$

Run on Windows 10, open WSL terminal, run vim inside it. I can type lower-case characters, but upper-case characters typed with SHIFT key are ignored. CAPS switches successfully and upper-case characters are typed and showed.

**Comment by tex** [comment]
Duplicate of https://github.com/kingToolbox/WindTerm/issues/485.

**Comment by kingToolbox** [comment]
Thank you, are you using `WSL 1` or `WSL 2`? I can't reproduce this problem in `WSL 1`.

**Comment by ihersom** [comment]
I have this issue in WSL 2
