### ISSUE TITLE
X11 windows open only for first host

### ISSUE THREAD

**Issue by eugenov** [kingToolbox/WindTerm#678]
Hello!
I have just found out that when you want to open 2 gui apps on 2 different hosts, you open all these apps on the first host (despite of server where you launch them). You can see it at vxsrv window name.

**Comment by eugenov** [comment]
Hmmm, this is right for firefox only. Investigating

**Comment by eugenov** [comment]
With another terminal+x11 server situation is the same. I think something is wrong with names resolving. Closing

**Comment by kingToolbox** [comment]
Hello. It should be possible to start two independent `X Servers`, but it should be noted that each `X Server` should have its own `Display Number`, and now `WindTerm` is limited to starting only one `X Server`. So you need to start two `WindTerm`, or start a separate `vcxsrv`.

**Comment by eugenov** [comment]
At first i thought it was because of ControlMaster implementation, but tests proved i was wrong. OR every ControlMaster implementation has such bug :)
