### ISSUE TITLE
E437: terminal capability "cm" required by VIM

### ISSUE THREAD

**Issue by zzugyl** [kingToolbox/WindTerm#685]
windter version 2.4，Linux platform，connect to centos7 ，edit file whth vim,get error message `终端需要能力 "cm"`
press ENTER，still can not edit file.

![2022-04-21_21-14](https://user-images.githubusercontent.com/27466768/164466496-3f0b0ff8-70e6-4983-b8ca-4f0c88768488.png)

echo TERM get
```
# echo $TERM  
  vt520
```

when set `export TERM=xterm`  and edit the file
![luan](https://user-images.githubusercontent.com/27466768/164467570-fd1fd779-7040-4756-af72-cfa8b89c222a.png)

**Comment by kingToolbox** [comment]
May I ask what is the `Term` (Session Settings Dialog - SSH - Term) of your session? If it is not `xterm` or `xterm-256color`, can setting it to `xterm-256color` solve the problem?

These extra characters look like mouse info, but I'm not quite sure yet, maybe I need to read the source code of `vi`.

**Comment by zzugyl** [comment]
Session Settings Dialog - SSH - Term，vt520. 
Term change to xterm-256color , problem solved. thanks.
I have 2 session in a group，only this term set to vt520，but I have no idea when it was changed.

**Comment by kingToolbox** [comment]
It's okay, maybe it's an accident, maybe it's a bug. If it is a bug, it will always recur. :smile: This issue will be closed. If there are new problems, please file new issues. Thank you.
