### ISSUE TITLE
Cannot use sz/rz in 2.4.0. But it works in 2.2.2

### ISSUE THREAD

**Issue by x10000year** [kingToolbox/WindTerm#689]
I used to use sz/rz in 2.2.2. But after upgrade to 2.4.0, sz/rz just hangs.

I use windterm in windows, and connect to linux server

**Comment by x10000year** [comment]
just notice that this bug has been fixed

**Comment by kingToolbox** [comment]
Welcome to continue submitting new feature requests and bugs, thank you.
