### ISSUE TITLE
zsh stdout with ']133;C;' 

### ISSUE THREAD

**Issue by shellsuperhu** [kingToolbox/WindTerm#693]
zsh stdout with ']133;C;' 
what's mean? 
how to cut it?

![image](https://user-images.githubusercontent.com/2357410/164964866-ce63a815-45fc-4919-a63d-f326e50bc353.png)

**Comment by kingToolbox** [comment]
I am happy to inform you that [WindTerm_2.4.1](https://github.com/kingToolbox/WindTerm/releases/tag/2.4.0) has been released and this bug has been fixed. Please download and check it, thank you.

**Comment by shellsuperhu** [comment]
thanks, you fixed soon. it seems working correct now.

![image](https://user-images.githubusercontent.com/2357410/165203765-36df8594-1699-4a6a-b841-818168367c46.png)

**Comment by kingToolbox** [comment]
Good news. You are welcome to file new issues. Thank you.
