### ISSUE TITLE
关于日志的打印与缓存

### ISSUE THREAD

**Issue by lain-github** [kingToolbox/WindTerm#7]
请问当前的日志打印缓存是怎么处理的, 为什么滚动翻看之后, 新的打印信息只能保留一部分.
另外如果想将打印信息保存起来应该怎么操作呢.

**Comment by kingToolbox** [comment]
All output will be kept in scrollback if "Lines of scrollback (Session Dialog / Window)" set to 0. If you can not find all the output, you may,
- Check if "Lines of scrollback" is set to a non-zero number.
- Check if the scrollback has been erased as server's request.
```
CSI Ps J  Erase in Display (ED), VT100.
            Ps = 0  ⇒  Erase Below (default).
            Ps = 1  ⇒  Erase Above.
            Ps = 2  ⇒  Erase All.
            Ps = 3  ⇒  Erase Saved Lines, xterm.
```
Press alt+s (Menu: Session / Save), all content will be prompted to be saved as a text file.

**Comment by lain-github** [comment]
Sorry, i do not know how to set "Lines of scrollback" to 0.

**Comment by lain-github** [comment]
Lines of scrollback is setted to 0, it is ok when i using serial, but if i use telnet, it is abnormal after i scrolling througn the log.

**Comment by lain-github** [comment]
打印是不是区分cmd和telnet, 我看使用telnet时, telnet的打印是独立的, 还可以折叠, 但是为什么不能查看它之前的日志呢, 只能显示一屏的日志.

**Comment by lain-github** [comment]
第一次telnet时输入命令正常, 如果exit退出telnet, 再重新telnet, 此时输入的命令不可见, 除非按enter键才能看到输入的命令.  @ kingToolbox

**Comment by kingToolbox** [comment]
There is no difference for scrollback among cmd, serial and telnet. It's better to show the screenshot to analyse.

**Comment by kingToolbox** [comment]
Every session has its own setting. If only 40 lines display, please check `Lines of scrollback` of the session.

**Comment by lain-github** [comment]
It is easy to reproduce.
1. In cmd session use telnet, when i login, the fold flag appears on the left, and subsequent logs will be in this fold flag, only 40 lines can be displayed. (Lines of scrollback is setted to 0)
![图片](https://user-images.githubusercontent.com/33279034/77711149-1c4d4a80-700b-11ea-98bd-79ed78cb3724.png)

2. Then exit to telnet, and type some cmds, such as telnet, the cmd is invisible.

**Comment by lain-github** [comment]
Why! my picture can not display.

**Comment by kingToolbox** [comment]
When using telnet in cmd, the window's telnet.exe is actually used. It limits the output to only 40 lines, and `lines of scrollback` has nothing to do with it.
If you need scrollback, you can use WindTerm's telnet session instead.
