### ISSUE TITLE
Serial session set to binary, not logging to files

### ISSUE THREAD

**Issue by yuwen123441** [kingToolbox/WindTerm#71]
1. create a serial session, set Data : binary, and set logging enabled
2. session connect succeed, 
![image](https://user-images.githubusercontent.com/54434146/113371333-a5bef780-9398-11eb-96e0-0b3210c263b5.png)
3.  Set: Mode -> Hex Edit, disabled, the log is easy to read
![image](https://user-images.githubusercontent.com/54434146/113371416-dbfc7700-9398-11eb-9ac1-348945069c88.png)
4. but the log is not logging to files

**Comment by kingToolbox** [comment]
Thank you, I checked the code, and it is true that the data is displayed directly in binary mode, and it is not written into the log like text mode. 

I will fix this in the next version. And I want to consult you. Do you think it is better to store the raw binary directly without timestamp in the log file, or to store it in hex text with timestamp, as shown in the view? Which mode is more convenient in daily use? Thank you again.

**Comment by yuwen123441** [comment]
For binary mode, i think should record without timestamp, because user other script read the binary file or do some other things，if add timestamp, it may destroy the original data.
Binary mode also need to save a text log, it should add the timestamp, if  use set: Mode -> Hex Edit, disabled.

**Comment by kingToolbox** [comment]
Thank you for your great advice. I am happy to tell you that this feature has almost been completed, and I also think that the original data should be retained. Therefore, when serial session is configured in binary mode, the original data will be recorded. Otherwise, it is recorded as text with timestamp. 

BTW, since the option `Mode - Hex Edit` can be modified at any time during operation, and the log format cannot be modified accordingly, I think it is not suitable as a criterion for the log format. What do you think?

**Comment by yuwen123441** [comment]
I agree with you.

**Comment by kingToolbox** [comment]
Hi, I am glad to tell you that this feature has been completed in v2.1.0 prerelease 3, but now you can download [WindTerm_2.1.0_Prerelease_4](https://github.com/kingToolbox/WindTerm/releases/tag/2.1-prerelease) and check it.

BTW, I redesigned the record format. I later felt that the log was still for people to read, so the original raw data was not recorded as binary, but it is recorded like the example below:

> [2021-06-15 00:11:22] Received 21 bytes.
> 0000: 53 53 48 2d 32 2e 30 2d 4f 70 65 6e 53 53 48 5f  SSH-2.0-OpenSSH_
> 0010: 38 2e 30 0d 0a                                                       8.0..

If necessary, I think the original data can be obtained by parsing the log. If you have any ideas, please let me know. Thank you.

**Comment by kingToolbox** [comment]
Hello, [WindTerm_2.1.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.1) has been released and this issue has been fixed too, please download and check it, thank you.

**Comment by kingToolbox** [comment]
The issue should have been fixed in the new [WindTerm_2.1.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.1) and self-test passed. Please reopen this issue if it is still valid. Thank you.
