### ISSUE TITLE
Text gets quite crowded on high DPI screen

### ISSUE THREAD

**Issue by mbrownnycnyc** [kingToolbox/WindTerm#72]
Hello,

Any `/` character appears quite crowded the high DPI screen of my surface book gen 1.

![image](https://user-images.githubusercontent.com/991809/113465026-0bde6580-93ff-11eb-8eaa-364ccf983e2d.png)

Any ideas on how I can remediate this possibly with a config change?

Thanks!

**Comment by kingToolbox** [comment]
You can try [changing the font](https://github.com/kingToolbox/WindTerm/issues/59#issuecomment-797263696) first to see if it solves the problem? In addition, I will add character spacing options in the next release, which should also solve this problem.

**Comment by kingToolbox** [comment]
Sorry to keep you waiting. [WindTerm_2.1.0_Prerelease_3](https://github.com/kingToolbox/WindTerm/releases/tag/2.1) has just been released and this issue has been fixed. You can download and check it now.

This new prerelease version supports specifying character spacing through `text.charSpaceFactor` in the configuration file `WindTerm-install-path/global/wind.config`, which range is 0.8 to 2.0, the default is 1.0. You can adjust this parameter until you are satisfied, usually 1.1 or 1.2 is wide enough.

If there is any need, please let me know, thank you.

**Comment by mbrownnycnyc** [comment]
i just saw this response.  I'll test in a few hours and let you know.  Thank you!

**Comment by kingToolbox** [comment]
Hello, is this issue fixed? You can download [WindTerm_2.1.0_Prerelease_4](https://github.com/kingToolbox/WindTerm/releases/tag/2.1-prerelease) and check now, thank you.

**Comment by kingToolbox** [comment]
Hello, [WindTerm_2.1.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.1) has just been released and the text display has been improved, please download and check it, thank you.

**Comment by kingToolbox** [comment]
The issue should have been fixed in the new [WindTerm_2.1.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.1) and self-test passed. Please reopen this issue if it is still valid. Thank you.
