### ISSUE TITLE
Better support for two-factor authentication

### ISSUE THREAD

**Issue by chaos-cn** [kingToolbox/WindTerm#722]
Winterm 2.4.1
MacOS M1 12.3..1

I connect to the server through a [bastion machine](https://www.dbappsecurity.com.cn/product/cloud1706.html). It turned on the Two-factor authentication. I need to enter username,password and a dynamic SMS verification code to login. The  first time I conncet to the bastion machine var WindTerm is ok like this:

1. step 1 input username and password

<img width="513" alt="image" src="https://user-images.githubusercontent.com/71205599/166628891-4992be13-626c-4fae-9e95-8d502997d422.png">

<img width="515" alt="image" src="https://user-images.githubusercontent.com/71205599/166628920-4c70dfb7-b6d1-4aef-86ea-531cb9d3de5b.png">

2. step2 input a dynamic SMS verification code

<img width="514" alt="image" src="https://user-images.githubusercontent.com/71205599/166629006-5bbd6549-a66b-4efa-9336-87367c4719f7.png">

3. step3 It's OK

**But when I save correct username and password, double clike the linkname in session to connect it  , the dialog like this :** 

<img width="514" alt="image" src="https://user-images.githubusercontent.com/71205599/166629887-fae00474-bd00-4f84-99e4-4df6702c2cd3.png">

However, I have received a SMS verification code for this matter. But I can not use this code , I shoud input password again , and receive a SMS verification code again!

**I hope this time show step2 dialog and i just need to input SMS verification code.**

**Comment by ghostgeek** [comment]
I have a similar problem！ @kingToolbox

**Comment by chaos-cn** [comment]
2.5.0 fixed
