### ISSUE TITLE
Warning at startup because of path with spaces

### ISSUE THREAD

**Issue by makexiao113** [kingToolbox/WindTerm#736]
![image](https://user-images.githubusercontent.com/63517007/167326415-1d24ee7b-d238-4ce3-adb4-2926cb0196e9.png)

**Comment by kingToolbox** [comment]
Sorry for the late reply, because I have some personal matters to take care of recently.

I am happy to inform you that [WindTerm_2.5.0_Prerelease_1](https://github.com/kingToolbox/WindTerm/releases/tag/2.5-prerelease) has been released and this bug has been fixed. Please download and check it, thank you.

**Comment by makexiao113** [comment]
> Sorry for the late reply, because I have some personal matters to take care of recently.
> 
> I am happy to inform you that [WindTerm_2.5.0_Prerelease_1](https://github.com/kingToolbox/WindTerm/releases/tag/2.5-prerelease) has been released and this bug has been fixed. Please download and check it, thank you.

Thank you very much. By the way, I found that the upload speed was a little slow when I uploaded the file. Do you have any optimization plan for this aspect in the future?

**Comment by makexiao113** [comment]
> Sorry for the late reply, because I have some personal matters to take care of recently.
> 
> I am happy to inform you that [WindTerm_2.5.0_Prerelease_1](https://github.com/kingToolbox/WindTerm/releases/tag/2.5-prerelease) has been released and this bug has been fixed. Please download and check it, thank you.

this bug has bean fixed, thank you

**Comment by kingToolbox** [comment]
Yes, there is already issues #437 and #687 about this. However, since my development environment is a local area network, the speed is very fast at almost any time, so I cannot further compare the expected speed with the actual speed.

This problem will definitely be fixed, I am just waiting for the right time. After all, there are too many factors that affect the speed. In addition to the code, the network environment, the system, etc. may be the cause of the slow speed.

BTW:
If it's not very troublesome, can you help me test your upload speed, using the current `WindTerm`, [WindTerm_2.2.2](https://github.com/kingToolbox/WindTerm/releases/tag/2.2) and a third-party tool with fast upload speed.

**Comment by makexiao113** [comment]
my pleasure,sir



---Original---
From: ***@***.***&gt;
Date: Fri, May 20, 2022 19:28 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [kingToolbox/WindTerm] Warning at startup because of path with spaces (Issue #736)




 
Yes, there is already issues #437 and #687 about this. However, since my development environment is a local area network, the speed is very fast at almost any time, so I cannot further compare the expected speed with the actual speed.
 
This problem will definitely be fixed, I am just waiting for the right time. After all, there are too many factors that affect the speed. In addition to the code, the network environment, the system, etc. may be the cause of the slow speed.
 
BTW:
 If it's not very troublesome, can you help me test your upload speed, using the current WindTerm, WindTerm_2.2.2 and a third-party tool with fast upload speed.

**Comment by makexiao113** [comment]
> Yes, there is already issues #437 and #687 about this. However, since my development environment is a local area network, the speed is very fast at almost any time, so I cannot further compare the expected speed with the actual speed.
> 
> This problem will definitely be fixed, I am just waiting for the right time. After all, there are too many factors that affect the speed. In addition to the code, the network environment, the system, etc. may be the cause of the slow speed.
> 
> BTW: If it's not very troublesome, can you help me test your upload speed, using the current `WindTerm`, [WindTerm_2.2.2](https://github.com/kingToolbox/WindTerm/releases/tag/2.2) and a third-party tool with fast upload speed.

![image](https://user-images.githubusercontent.com/63517007/169629579-6f66d1ad-7574-4ad4-bb6e-6603b6244aca.png)
version 2.2.0

![image](https://user-images.githubusercontent.com/63517007/169629590-b165f5af-574f-4536-a9de-ec77f953ed50.png)
version 2.5.5

The speed difference is not big. When I used MobaXterm, the speed was about 2m/s

**Comment by kingToolbox** [comment]
I never thought that the upload speed is less than half that of `MobaXterm`, which is **really slow**. I will try to see if I can improve the speed. I will update here if there is any progress, thank you very much.

By the way, is the download speed also much slower than `MobaXterm`?

**Comment by makexiao113** [comment]
> I never thought that the upload speed is less than half that of `MobaXterm`, which is **really slow**. I will try to see if I can improve the speed. I will update here if there is any progress, thank you very much.
> 
> By the way, is the download speed also much slower than `MobaXterm`?

After testing, there should be a bug in the calculation of the speed of mobaXterm. The speed displayed by mobaXterm is 5 to 10 times higher than the actual speed 
![微信图片_20220523135325](https://user-images.githubusercontent.com/63517007/169752473-1d520033-987d-4bf3-bc9f-66bb4171136d.jpg)

**Comment by kingToolbox** [comment]
I see, `MobaXterm` uses `kb/s` and `WindTerm` uses `KB/s`, usually `1KB/s = 8kb/s`. 

I think the real speed still depends on the actual test. Can you measure the time it takes for `MobaXterm` and `WindTerm` to upload the same large file separately? Thank you very much.

**Comment by makexiao113** [comment]
> I see, `MobaXterm` uses `kb/s` and `WindTerm` uses `KB/s`, usually `1KB/s = 8kb/s`.
> 
> I think the real speed still depends on the actual test. Can you measure the time it takes for `MobaXterm` and `WindTerm` to upload the same large file separately? Thank you very much.

i am sure I use one file
