### ISSUE TITLE
不小心把菜单栏给关掉了，怎么重新打开菜单栏

### ISSUE THREAD

**Issue by sugs86** [kingToolbox/WindTerm#745]
不小心把菜单栏给关掉了，怎么重新打开菜单栏

![image](https://user-images.githubusercontent.com/62504651/167753270-53253555-fff0-446c-9872-f215075cd6b0.png)

**Comment by sugs86** [comment]
I accidentally turned off the menu bar. How can I reopen the menu bar。

**Comment by beetsuan** [comment]
> I accidentally turned off the menu bar. How can I reopen the menu bar。
你在界面上，先按Alt+W，再按Alt+M，菜单栏就出来了。
我也是刚刚搞了一会儿，使用Ctrl+Alt进入专注模式才发现的

**Comment by beetsuan** [comment]
> 不小心把菜单栏给关掉了，怎么重新打开菜单栏
> 
> ![image](https://user-images.githubusercontent.com/62504651/167753270-53253555-fff0-446c-9872-f215075cd6b0.png)

你在界面上，先按Alt+W，再按Alt+M，菜单栏就出来了。
我也是刚刚搞了一会儿，使用Ctrl+Alt进入专注模式才发现的

**Comment by sugs86** [comment]
谢谢您提供的帮助

**Comment by RealForce1024** [comment]
其实最简单的方式，对于mac和windows以及linux都适用的方式是修改配置文件，.wind/profiles/default.v10/user.config文件中注释或删除掉`"Terminal.MenuBar"` 就能看到菜单栏了
<img width="693" alt="image" src="https://github.com/kingToolbox/WindTerm/assets/5277544/cee99db0-3dba-495b-bd5f-1ea706ff8387">

**Comment by yurenchen000** [comment]
#309
#810
#1815 
#2019

You're not the only one
你不是一个人

-----

OR use the **Command Pallete** :  
或者 使用 **命令面板**

  press <kbd> Alt + ; </kbd>   
  input  `Toggle Menu Bar`

-----

There are indeed blind spots in the interaction design.  
Perhaps the option to restore the menu bar shouldn't disappear when the menu bar is hidden.

peopes thoughs:
#1002 some gtk app did that thing, such as nautilus..
#2990  gnome also have some thing like that global menu
