### ISSUE TITLE
After opening bash, log in as the current user, not bash-3.2$（打开bash怎么默认以当前登录用户的身份登录）

### ISSUE THREAD

**Issue by GanHuaLin** [kingToolbox/WindTerm#753]
On a terminal like a MAC, the default to open is the current user identity
就像MAC的终端那样，默认打开的是当前用户的身份
<img width="405" alt="iShot_2022-05-12_15 51 32" src="https://user-images.githubusercontent.com/8326761/168020357-d1cf7459-25f7-4e9c-94ff-4c83178f9e8d.png">
<img width="351" alt="iShot_2022-05-12_23 25 54" src="https://user-images.githubusercontent.com/8326761/168111527-1c300d49-10a6-4ae5-be93-11a6457b0ad7.png">

**Comment by kingToolbox** [comment]
Sorry for the late reply.

I tried to open `/bin/bash` directly, it shows exactly the same as `WindTerm`. And if you open the `zsh` session in `WindTerm` you can get what you want.

BTW:
In `WindTerm`, any `MacOS` shell session is logged in as the current user, including `bash`.

**Comment by GanHuaLin** [comment]
> Sorry for the late reply.
> 
> I tried to open `/bin/bash` directly, it shows exactly the same as `WindTerm`. And if you open the `zsh` session in `WindTerm` you can get what you want.
> 
> BTW: In `WindTerm`, any `MacOS` shell session is logged in as the current user, including `bash`.

<img width="976" alt="iShot_2022-05-20_13 51 41" src="https://user-images.githubusercontent.com/8326761/169459784-9bf1786c-6c1a-4f28-ac0e-05bd1aec3610.png">
I hope that after OPENING shell ZSH, I can enter docker command or other commands without entering other commands, just like the terminal of MAC, so how should I configure?

（我希望我打开shell的zsh后，不用输入其他命令就可以像MAC自带的终端那样，可以输入docker命令或者其他命令，这样我该怎么配置？）

**Comment by GanHuaLin** [comment]
参考了一下其他终端应用，添加参数：-l
<img width="531" alt="iShot_2022-05-24_10 46 32" src="https://user-images.githubusercontent.com/8326761/169939223-f11ac4f9-e235-44be-9148-77519be2c17f.png">
