### ISSUE TITLE
[bug] when I'm in vim normal mode, the key is doesn't showed correctly.

### ISSUE THREAD

**Issue by yisuixinq** [kingToolbox/WindTerm#76]
when I press d-d to delete whole line,the key is showed like the picture below:

![image](https://user-images.githubusercontent.com/40953718/113744109-fb97f480-9736-11eb-9dab-02976bd11c99.png)

**Comment by hongnod** [comment]
possibly U checked an improper vt

**Comment by kingToolbox** [comment]
Thank you hongnod for the great advice. As suggested, this is a problem with TERM. I don’t know if it has been resolved after the suggested modification. If not, would you like to provide a little more information? If you want, please follow the steps below:

- Make sure that there is several text on a line.
- Before pressing "dd", click the menu item "Mode(7) - Debug Mode" to enter the debug mode.
- Press "dd" and make sure the illegal characters appear.
- Click the menu item "Mode(7) - Debug Mode" again to leave the debug mode.
- Browse $(WindTermInstalledDir)/profiles/default.v10/Terminal/logs/debug, zip and upload the newly generated log file as an attachment when you comment this.
- Done.

**Please don't worry about the content of the log file, it will only record the current command input and output, and will not record any sensitive information, including passwords, ip, computer information, etc.**

The log file is in plain text format. You can use a text editor to open and review the content. If there is any information you don't want to disclose, you can delete it manually.

Thank you!

**Comment by yisuixinq** [comment]
> possibly U checked an improper vt , try another vt such as to watch it works or not.
what is it meaning "vt"?

**Comment by kingToolbox** [comment]
"vt" is the `Term` configuration in your session dialog.
![image](https://user-images.githubusercontent.com/51009775/114060725-4006ca00-98c8-11eb-8787-62b7d2610d04.png)

**Comment by yisuixinq** [comment]
when I tried vt220, the key is showed correctly in vim, but when I type ":wq" to save&exit, there is some mistake characters in the left of corner.

![alignment](https://user-images.githubusercontent.com/40953718/114204792-2fb82300-998c-11eb-9da4-ee816b9d35f6.gif)

**Comment by kingToolbox** [comment]
According to the [Term documentation](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html), ESC[23;0;0t, which is `CSI Ps ; Ps ; Ps t`, means window manipulation(xterm) or DECSLPP(Resize to Ps lines, VT340 and VT420). VT220 does not support this control sequence. I think this can be solved by setting the shell term to VT220(`export TERM=VT220`) before executing the vim.

In addition, you can also set the session TERM to `xterm-256color`. Then before executing VI, use `echo $TERM` to view the value of the shell TERM. If it is not `xterm` or `xterm-256color`, then use `export TERM=xterm` or `export TERM=xterm-256color` to set the shell TERM to `xterm` or `xterm-256color`, and then execute VI to see if the delete function is normal. Logically speaking, whether it is VT220 or xterm, there should be no difference in deletion.

**Comment by kingToolbox** [comment]
Hi, has this problem been resolved? If there is any need, please let me know, thank you.

**Comment by kingToolbox** [comment]
As analyzed before, this may be caused by `Term` mismatch and choosing the correct `Term` should avoid this problem.

This issue will also be closed because no further activity occurs during the last month. Please reopen this issue if it is still valid. Thank you.
