### ISSUE TITLE
如何在会话管理器里建立文件夹？

### ISSUE THREAD

**Issue by tycjlee** [kingToolbox/WindTerm#763]
会话管理器里会话过多的时候，能否可以建立不同的文件夹收纳分类会话，目前暂时没找到方法。

**Comment by zhucp18** [comment]
@tycjlee 印象里可以在每个会话上打标签，能实现归类

**Comment by tycjlee** [comment]
@zhucp18 确实在每个会话的属性里使用“分组”可以进行归类，不过这个操作稍稍有点反人类 :) ,希望作者能改进成可以右键创建会话文件夹，可以拖拽会话进文件夹进行归类。

**Comment by HollrayChan** [comment]
可以在 WindTerm_2.5.0\.wind\profiles\default.v10\terminal\user.sessions 里去直接改group名字，就不同在界面里操作了
