### ISSUE TITLE
Automatically saves log files to a directory

### ISSUE THREAD

**Issue by GustabMG** [kingToolbox/WindTerm#775]
I want to automatically save the log file to a directory every time I start a session, rather than having to manually set the save log file after starting a session. How do I set up to do this?

**Comment by kingToolbox** [comment]
Please open the `Session Settings` dialog and configure the relevant options. You can watch the intro video [Logging / Automated Logging](https://kingtoolbox.github.io/2020/10/16/automated_logging/) to learn more.

**Comment by jan-bar** [comment]
You can edit `terminal\configs\session.config`，Restart the program so that all sessions will take effect

```text
"session.logType": 2,
"session.logOption": 1,
```

**Comment by kingToolbox** [comment]
@jan-bar 
Wow, you found it. This is the default configuration file for all sessions, and no related interface settings are provided for the time being. :smile:

**Comment by GustabMG** [comment]
> 

Oh, than's just what i wanted ,thank you!

**Comment by kingToolbox** [comment]
Thank you for your feedback. This issue has been solved and will be closed. Welcome to continue submitting new feature requests and bugs.
