### ISSUE TITLE
No input for some cyrillic characters 

### ISSUE THREAD

**Issue by eugenov** [kingToolbox/WindTerm#783]
Hello!
I've noticed strange bug - I can't type cyrillic  letter "р"  inside terminal at last few builds. "Space" is inserting in place of "р". UTF-8 encoding, other terminals deal with it without problem.

**Comment by kingToolbox** [comment]
Hi, eugenov. I tried it and did not encounter such a problem. Could it be a font problem? You can try changing a font to see if it works. In addition, after entering the character, copy it from `WindTerm` to `notepad` to see if it is ok.

BTW:
Is there any old `WindTerm` version that can handle this character correctly?

**Comment by kingToolbox** [comment]
Good news, I have reproduced the bug, and I found that the old `0.9` version is ok. I will try to fix it and let you know if there is any progress. :smile:

**Comment by eugenov** [comment]
> Is there any old `WindTerm` version that can handle this character correctly?

I fear i don't remember the version the problem appeared. I've just noticed a bug and I think one of previous versions was ok. :)

**Comment by eugenov** [comment]
Tried 2.4.1 and latest 2.5.0 preview 2 still has this bug.

**Comment by eugenov** [comment]
> So I plan to stop the development of new features in the next `2.6.0` version, and try to fix all the bugs before continuing to develop new features.

It's not just good decision, it's great decision, I must say.

**Comment by kingToolbox** [comment]
I am happy to inform you that [WindTerm_2.5.0_Prerelease_3](https://github.com/kingToolbox/WindTerm/releases/tag/2.5-prerelease) has been released and this bug has been finally fixed. Please download and check it, thank you. :smile:

**Comment by eugenov** [comment]
Thank you! Closing.
