### ISSUE TITLE
[request] Need an option for disabling auto completion

### ISSUE THREAD

**Issue by ImMartinYoung** [kingToolbox/WindTerm#784]
[2.5.0 Prerelease 1]

Cannot disable auto completion. It's useless for a somewhat sophisticated user, and bothersome, e.g. when I input the most commonly used "ll" and press ENTER(in CentOS), WindTerm gives "kill" on the command line.

I have to change back into Version 2.4.1.

Thanks.

**Comment by eugenov** [comment]
dupe https://github.com/kingToolbox/WindTerm/issues/773

**Comment by kingToolbox** [comment]
@ImMartinYoung 
Sorry for the late reply. In the [WindTerm_2.5.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.5.0) version, you can easily disable `auto completion` by setting `Menu - Session - Preferences - Terminal - Auto Completion - Enable auto completion`.
![image](https://user-images.githubusercontent.com/51009775/186059401-5bd122ba-1d1b-439b-b6f8-854fe3d75866.png)
