### ISSUE TITLE
ssh中自动补全的如何去掉

### ISSUE THREAD

**Issue by leeliangstudy** [kingToolbox/WindTerm#785]
![image](https://user-images.githubusercontent.com/89442766/170403728-3ff0b8f4-38f8-4475-ad93-67847b3386d7.png)
这个自动加载命令的如何去掉

**Comment by leeliangstudy** [comment]
How to cancel this function of matching search load command, because I often use ```ll query directory, search to ```kill, very upset

**Comment by Negative04** [comment]
change the session "system" to other mode except cmd.

![image](https://user-images.githubusercontent.com/108313362/176074448-0b9eb1a6-be3a-4ae9-85b8-8a923109c053.png)

**Comment by kingToolbox** [comment]
Sorry for the late reply. In the [WindTerm_2.5.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.5.0) version, you can easily disable `auto completion` by setting `Menu - Session - Preferences - Terminal - Auto Completion - Enable auto completion`.
![image](https://user-images.githubusercontent.com/51009775/186059401-5bd122ba-1d1b-439b-b6f8-854fe3d75866.png)
