### ISSUE TITLE
连接dropbear，没有sftp-server时，打开文件传输会卡死

### ISSUE THREAD

**Issue by jiangjianghu** [kingToolbox/WindTerm#791]
2.4.1版本
连接dropbear，没有sftp-server时，打开文件传输会卡死，而且一个标签页卡死后整个软件就卡死了，不能单独结束一个标签页，不知道这算不算一个bug

**Comment by waveacme** [comment]
session property -> ssh -> authentication -> enable sftp , uncheck it to avoid this issue.
