### ISSUE TITLE
when using serial, it will tip session error first

### ISSUE THREAD

**Issue by lain-github** [kingToolbox/WindTerm#8]
when using serial, it will tip [session error] first and the tip will always be there.  Is this normal?

**Comment by kingToolbox** [comment]
Thanks, this issue will be fixed in the feature.

**Comment by kingToolbox** [comment]
Sorry for the late reply, This issue has been fixed now, please download the new version [2.0.0 Prerelease 2](https://github.com/kingToolbox/WindTerm/releases/tag/2.0.0) and check, thank you.

**Comment by kingToolbox** [comment]
Self-test passed in [v2.0.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.0), and this issue will be closed because no further activity occurs during the last month. Please reopen this issue if it is still valid. Thank you.

**Comment by kingToolbox** [comment]
Self-test passed in [v2.0.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.0), and this issue will be closed because no further activity occurs during the last month. Please reopen this issue if it is still valid. Thank you.
