### ISSUE TITLE
[问题]Alpine Linux 基于 ash 的shell 环境无法认证

### ISSUE THREAD

**Issue by lckei** [kingToolbox/WindTerm#801]
环境：PVE + LXC容器 openssh-server-8.6_p1-r3

```
 cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.14.0
PRETTY_NAME="Alpine Linux v3.14"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```
windterm 通过配置ssh 连接Alpine Linux 失败，提示 身份验证失败，请重试,  希望能够支持。

**Comment by kcmxuan** [comment]
在系统日志中的报错：
![图片](https://user-images.githubusercontent.com/11486274/172087436-a25632a0-8390-4740-ac57-60b313db4f84.png)
取消 “会话管理 -> SSH -> 验证 -> 尝试键盘交互认证” 可已正常连接

**Comment by lvygit** [comment]
> 在系统日志中的报错： ![图片](https://user-images.githubusercontent.com/11486274/172087436-a25632a0-8390-4740-ac57-60b313db4f84.png) 取消 “会话设置 -> SSH -> 验证 -> 尝试键盘交互认证” 可已正常连接

成功解决了，3q
