### ISSUE TITLE
How to modify scroll bar color

### ISSUE THREAD

**Issue by gooker** [kingToolbox/WindTerm#81]
can't see clearly.

The best SSH client in my heart!!

**Comment by kingToolbox** [comment]
Thank you. Which theme are you using,`dige-white`? I think the `dige-black` theme should be fine. If you want to modify the scrollbar color, take the `dige-black` theme as an example, open `windterm-install-path/global/themes/dige-black/gui.theme` and find the following to modify: 
``` python
QAbstractItemView QScrollBar {
  background-color: #191919;  // The background color of the scroll bar in the QAbstractItemView, like list or tree widget
}
QScrollBar {
  border: none;
  // The default background color of the scroll bar
  background-color: transparent;  
  margin: 0px 0px 0px 0px;
}
QScrollBar::handle {
  // The default background color of the handle in the scrollbar, which might be what you need.
  // When modifying, please keep the alpha channel to ensure that the color of the mark below is visible 
  background-color: #40c0c0c0;
}
QScrollBar::handle:hover {
  // The default background color of the handle in the scrollbar when the mouse is hovering
  background-color: #40a6a6a6;
}
TextView > QAbstractScrollArea QScrollBar {
  // The background color of the scrollbar in the textview, which might be what you need.
  background-color: #1c1c1c;
  border: none;
  margin: 0px;
}
```

**Comment by kingToolbox** [comment]
By the way, after the `gui.theme` is modified, whether you restart `WindTerm` or switch to another theme and then switch back through the menu `View - Color Themes`, you can see the effect of the modification, and I would recommend switching themes. :smile:

**Comment by gooker** [comment]
:)
I like dige-black-and-white ,it's ok.

```
QScrollBar::handle {
  // The default background color of the handle in the scrollbar, which might be what you need.
  // When modifying, please keep the alpha channel to ensure that the color of the mark below is visible 
  background-color: #900fffff;
}
QScrollBar::handle:hover {
  // The default background color of the handle in the scrollbar when the mouse is hovering
  background-color: #900fffff;
}
TextView > QAbstractScrollArea QScrollBar {
  // The background color of the scrollbar in the textview, which might be what you need.
  background-color: #000000;
  border: none;
  margin: 0px;
}
```

> Thank you. Which theme are you using,`dige-white`? I think the `dige-black` theme should be fine. If you want to modify the scrollbar color, take the `dige-black` theme as an example, open `windterm-install-path/global/themes/dige-black/gui.theme` and find the following to modify:
> 
> ```python
> QAbstractItemView QScrollBar {
>   // The background color of the scroll bar in the QAbstractItemView, like list or tree widget
>   background-color: #191919; 
> }
> QScrollBar {
>   border: none;
>   // The default background color of the scroll bar
>   background-color: transparent;  
>   margin: 0px 0px 0px 0px;
> }
> QScrollBar::handle {
>   // The default background color of the handle in the scrollbar, which might be what you need.
>   // When modifying, please keep the alpha channel to ensure that the color of the mark below is visible 
>   background-color: #40c0c0c0;
> }
> QScrollBar::handle:hover {
>   // The default background color of the handle in the scrollbar when the mouse is hovering
>   background-color: #40a6a6a6;
> }
> TextView > QAbstractScrollArea QScrollBar {
>   // The background color of the scrollbar in the textview, which might be what you need.
>   background-color: #1c1c1c;
>   border: none;
>   margin: 0px;
> }
> ```

**Comment by kingToolbox** [comment]
I'm glad you resolved the problem so quickly. I will also deepen the color of the scroll bar in the next version to make it more conspicuous. The next version will add X/Y/Z modem function and the prerelease will be released in these two days, if you like, please download and use, thank you. :smiley:

**Comment by gooker** [comment]
> I'm glad you resolved the problem so quickly. I will also deepen the color of the scroll bar in the next version to make it more conspicuous. The next version will add X/Y/Z modem function and the prerelease will be released in these two days, if you like, please download and use, thank you. 😃

That’s awesome, I always use rz & sz;

**Comment by kingToolbox** [comment]
The new version [2.1.0_prerelease_2](https://github.com/kingToolbox/WindTerm/releases/tag/2.1) has been released, which not only deepens the color of the scroll bar slider, but also supports [ZModem](https://kingtoolbox.github.io/2021/04/23/modem-zmodem/), please download and use, thank you.
