### ISSUE TITLE
How to set default syntax schemes to none

### ISSUE THREAD

**Issue by TheBobbyliu** [kingToolbox/WindTerm#822]
Hello,
  I'm using WindTerm 2.5.0, and I find the "syntax schemes" automatically set for linux quite annoying because my computer does not have high computing capabilities.
  So I am wondering if there's a way to set the default syntax scheme to "none" instead of "linux" when I open a remote ssh.
Thanks

**Comment by kingToolbox** [comment]
Sorry for replying so late, I just got back from a business trip.

You can open the `WindTerm_install_path/terminal/configs/session.config` and modify `"session.system": "linux"` to `"session.system": "none"`, then restart `WindTerm` and it should work.
