### ISSUE TITLE
建议：终端路径跳转时，文件管理器能否同步跳转呢

### ISSUE THREAD

**Issue by chen1195585098** [kingToolbox/WindTerm#823]
终端路径跳转时，终端路径仍保持初始状态，在根目录。能否让其保持同步
![image](https://user-images.githubusercontent.com/25813537/174202451-271ac0ca-bdc7-45cc-94e2-1442d37da0c0.png)

**Comment by l-we** [comment]
当cd到有几万个文件的文件夹时会直接卡死的

**Comment by freekkk** [comment]
不需要。你这有点开玩笑了。

**Comment by redseabay** [comment]
应该有个按钮, 可以选择跟随走, 或者不跟随走. 有时候想固定一个目录传文件, 有时候想传到当前目录

**Comment by Kendarou** [comment]
> 当cd到有几万个文件的文件夹时会直接卡死的

mobaxterm, xshell也都是默认跟随当前目录的，也没见谁整天反馈切到几万个文件的目录下卡死的。两种需求确实都有，但我觉得是1%对99%的关系。

**Comment by redseabay** [comment]
> 



> > 当cd到有几万个文件的文件夹时会直接卡死的
> 
> mobaxterm, xshell也都是默认跟随当前目录的，也没见谁整天反馈切到几万个文件的目录下卡死的。两种需求确实都有，但我觉得是1%对99%的关系。

弄这种目录本来就是不妥当. 终端软件也可以进入某个目录, 只加载前面200个文件名好了, 那个窗口这么小, 加载多了, 翻页也烦死了

**Comment by moli765** [comment]
想有这样的功能

**Comment by redseabay** [comment]
> 想有这样的功能

其实不同步跳转, 增加一个按钮, 手工同步也可以, 不然每次都要手工复制黏贴, 挺烦的.

**Comment by kingToolbox** [comment]
Duplicate of #450 

Sorry for the late reply. I've started development on this feature, which is expected to be released in the `2.6.0` or `2.7.0` version. Please stay tuned, thank you.

**Comment by peafowl-wang** [comment]
有这个功能的在下面有一个图标有这个功能，也可以按F8来设置

**Comment by peafowl-wang** [comment]
sync Terminal Folder F8

**Comment by Straw2333** [comment]
> 不需要。你这有点开玩笑了。

你认真的？

**Comment by TerminaCoder** [comment]
有可以设置登录主机的默认路径的功能吗
