### ISSUE TITLE
How do I reset the password for opening windtrem in the configuration?

### ISSUE THREAD

**Issue by iiiusky** [kingToolbox/WindTerm#835]
I didn't set a password for windtrem when I first started using it, and after using it for a while to set a password for windtrem to start. But I can't find any place in the interface to configure it.
Currently my password is empty, is there any support for resetting the password in the interface if my password is not empty?

**Comment by Negative04** [comment]
CTRL+ALT+L or click the "Lock Screen" in right bottom (default GUI )

**Comment by iiiusky** [comment]
ok
