### ISSUE TITLE
增加鼠标选中后复制到剪切板

### ISSUE THREAD

**Issue by bilbilmyc** [kingToolbox/WindTerm#837]
可以增加一个鼠标选中终端后，自动粘贴到剪切板的功能吗

**Comment by liujunhui1** [comment]
https://zhuanlan.zhihu.com/p/468501270

**Comment by mzky** [comment]
@Ma-Yunchao 

![image](https://user-images.githubusercontent.com/13345233/177742214-a25ee912-e93f-4591-9582-f890ced9d1d3.png)

![image](https://user-images.githubusercontent.com/13345233/177741808-e3e2e8fe-74bd-4cc0-81bc-0b790ac16907.png)

**Comment by chymy** [comment]
“自动选中复制选定内容” 其实只能配置 “右键单击”粘贴文本使用，而且不能粘贴到外部剪切板
