### ISSUE TITLE
Quick Commands could support ctrl_c?

### ISSUE THREAD

**Issue by gooker** [kingToolbox/WindTerm#84]
I test Quick Commands  support \n \t
how to send ctrl_c?

**Comment by kingToolbox** [comment]
The current version does not yet support it. But I have completed the development of this feature for you in the past two days. The new version supports sending ctrl+c (same as ASCII code `EXT/03`) in the following ways:  

| format | code |
| -- | -- |
| hexadecimal char | \x03 |
| octal char | \003 |
| wide hexadecimal char | \u0003 |
| control char | \cc |
|control char | \c-c |

Later versions will support running custom scripts, and you can send any text to the server more easily at that time.

**Comment by kingToolbox** [comment]
The new version [2.1.0_prerelease_2](https://github.com/kingToolbox/WindTerm/releases/tag/2.1) has been released and supports [sending escaped characters](https://kingtoolbox.github.io/2020/08/22/quickbar/) like `Ctrl+C` now, please download and check, thank you!

**Comment by gooker** [comment]
control char | \c-c
-- | --

P2 test ok

**Comment by kingToolbox** [comment]
Thank you for verifying so quickly. This issue will be closed and welcome to continue submitting new issues and feature requests, thank you. :smile:
