### ISSUE TITLE
When logging into the network switch, you cannot use backspce to delete characters

### ISSUE THREAD

**Issue by wilia** [kingToolbox/WindTerm#846]
When logging into the network switch, you cannot use backspce to delete characters, you can only use ctrl+H, even if you set it according to [Backspcae And Delete Key](https://kingtoolbox.github.io/2020/08/22/keyboard-backspace-delete/)，

 protocol ：ssh
 term ：vt100 or xterm-256color
 system：cisco switch and H3C switch

![WindTerm1](https://user-images.githubusercontent.com/3975384/175859940-27de6665-d5e3-436d-b6be-7ab977a1430e.png)
![WindTerm2](https://user-images.githubusercontent.com/3975384/175859960-cab9fa96-dc20-41ef-987a-65803df0d9cf.png)
![WindTerm3](https://user-images.githubusercontent.com/3975384/175859967-04c1e21d-143a-4243-af78-9786becd706d.png)

**Comment by kingToolbox** [comment]
If you can use `Ctrl+H` to delete characters, then it should be possible to use `Backspace` too. Please set `Session Settings - Terminal - Keyboard - Backspace sends` to `Backspace (&B)`, then **reconnect or create a new session** and see if it works.

If there is still a problem and the system supports the `stty` command, then please execute the `stty -a` command and paste the output here. I will analyze it further. Thank you.

**Comment by wilia** [comment]
> If you can use `Ctrl+H` to delete characters, then it should be possible to use `Backspace` too. Please set `Session Settings - Terminal - Keyboard - Backspace sends` to `Backspace (&B)`, then **reconnect or create a new session** and see if it works.
> 
> If there is still a problem and the system supports the `stty` command, then please execute the `stty -a` command and paste the output here. I will analyze it further. Thank you.

Set Session Settings - Terminal - Keyboard - Backspace sends to Backspace (&B)successful, it can be used normally, thank you for your help
