### ISSUE TITLE
Any password is suitable as a master password

### ISSUE THREAD

**Issue by karagi4** [kingToolbox/WindTerm#85]
When I set a new master password and then restart WindTerm, when I am prompted for the master password, I can enter any wrong password to get into WindTerm!
![2021-04-21 10-54-30 WindTerm](https://user-images.githubusercontent.com/41114204/115520076-73ffc900-a292-11eb-9ca6-276b4bc5da42.jpg)

**Comment by kingToolbox** [comment]
Don't worry, this has no negative impact on security. 

For security, WindTerm does not record the master password, so the master password cannot be verified when entering it. However, the wrong password will fail in subsequent decryption of sensitive content such as automatic login information. 

Although there is no safety issue, but in the new version 2.1.0_prerelease_2, this has been improved. WindTerm will use the existing encrypted information to verify the master password. If the verification fails, the master password will be rejected. However, users can still use features that do not involve encrypted information normally, but the use of automatic login information to log in to the host is still prohibited. 

By this design, I believe that encrypted data is safe at all times.

**Comment by kingToolbox** [comment]
The new version [2.1.0_prerelease_2](https://github.com/kingToolbox/WindTerm/releases/tag/2.1) has been released and a "Wrong password" message box will pop up when the wrong master password is detected. I hope this will meet your needs well.

**Comment by karagi4** [comment]
Thank

**Comment by kingToolbox** [comment]
My pleasure. Welcome to continue submitting new issues and feature requests. Thank you!
