### ISSUE TITLE
Would you make file explorer window sync with terminal path

### ISSUE THREAD

**Issue by steinvenic** [kingToolbox/WindTerm#856]
![image](https://user-images.githubusercontent.com/18524326/176342243-359274cd-2ff8-4213-83d2-e09dc566f5c2.png)

**Comment by kingToolbox** [comment]
Duplicate of #823 

Yes, I've started development on this feature, which is expected to be released in the `2.6.0` or `2.7.0` version. Please stay tuned, thank you.

**Comment by steinvenic** [comment]
thank for your deveoping
