### ISSUE TITLE
Sort sessions in the session pane

### ISSUE THREAD

**Issue by laoola** [kingToolbox/WindTerm#867]
会话加一个自动排序
![image](https://user-images.githubusercontent.com/42239744/177897175-aabbd7b7-f769-4d5b-8e1d-8c651dad96b8.png)

**Comment by kingToolbox** [comment]
This is very strange, the `folders` and `sessions` are sorted on my machine. And no one has ever reported such a problem before. Does it work after restarting `WindTerm`?

**Comment by laoola** [comment]
Have you made the corresponding settings when it takes effect? It can be used WindTerm normally after I restart it here

**Comment by laoola** [comment]
![image](https://user-images.githubusercontent.com/42239744/178398265-e60b3733-236d-46db-8294-cfc994763de4.png)
Folders and sessions are not sorted

**Comment by kingToolbox** [comment]
Ok, i see, actually the session names are already sorted **alphabetically**, but you think they should be sorted **numerically**. e.g. it should be `11, 15, 118, 119, 121 `, not `11, 118, 119, 121, 15`, am i right?

**Comment by laoola** [comment]
Yes, that means, but the order of the session is the sequence of creating the session

**Comment by laoola** [comment]
Sorry, I didn't pay attention to the sorting rules,
