### ISSUE TITLE
Why don't I have a master password set

### ISSUE THREAD

**Issue by HalfSea** [kingToolbox/WindTerm#877]
When creating a new session, I logged in directly without prompting me to set the master password, and the screen locked. I did not know the master password.

**Comment by HalfSea** [comment]
Version is against 2.4.1

**Comment by kingToolbox** [comment]
Hello, the default master password is an empty string. And you will only be prompted to set a master password when you start `WindTerm` for the first time or after you have checked `Auto login next time` when logging in.

**Comment by HalfSea** [comment]
thanks
