### ISSUE TITLE
Can not open ssh session to CoreELEC

### ISSUE THREAD

**Issue by RuralHunter** [kingToolbox/WindTerm#879]
I login with root/password. After I input the 'root' in username dialog and then click next, WindTerm just tells me "identity verification failed”, even before I input the password. I then input the password and click "next", nothing happens.
![Clipboard01](https://user-images.githubusercontent.com/723880/178417453-e39e3770-6438-4bdc-8d54-ab5571cd8f12.jpg)

There is no problem to login to my CoreELEC with other ssh tools though.

**Comment by kingToolbox** [comment]
Your problem looks similar to #802. You can try the fix steps in it first, and please let me know if the issue is resolved or not. Thank you.

**Comment by RuralHunter** [comment]
yes, the workaround works, Thanks for the quick response.
