### ISSUE TITLE
File manager favorite path

### ISSUE THREAD

**Issue by laoola** [kingToolbox/WindTerm#888]
![image](https://user-images.githubusercontent.com/42239744/178676407-b66f4f46-64d5-4611-b860-9015ff09f50a.png)
There is a recently used path record now. Is there a plan to add a favorite path？

**Comment by kingToolbox** [comment]
Yes, `Favorites Button` has been planned for a long time, but have not had time to complete this. I will enhance the `Filer` in `2.6.0` or `2.7.0` version. including but not limited to:
- Favorites Button
- Dual Pane File Manager
- Display transfer details and error messages
- Transfer files between two `SSH` sessions #845 
- Fix the bug that upload speed is very slow #437 #687
- When editing a file, even if the server is disconnected, it can be saved and uploaded correctly after reconnecting to the server.

**Comment by laoola** [comment]
nice, I like this tool very much
