### ISSUE TITLE
old master password is empty

### ISSUE THREAD

**Issue by beyound87** [kingToolbox/WindTerm#90]
i used old version and master password is empty, but new version required master password[lock screen]
i need help,tks!

**Comment by kingToolbox** [comment]
If you haven't set a master password, just press `Enter`. I have tested this, but if it doesn't work, that is a bug, I will fix it.

**Comment by beyound87** [comment]
tks

**Comment by kingToolbox** [comment]
My pleasure. This issue will be closed and welcome to continue submitting new issues and feature requests, thank you. :smile:
