### ISSUE TITLE
关闭声音

### ISSUE THREAD

**Issue by Ma-Yunchao** [kingToolbox/WindTerm#903]
tab补全的时候，电脑开着声音会一直响。可否增加一个关闭声音的按钮呢？

**Comment by wang33winner** [comment]
在会话设置 -> 终端 -> Bell中可以选择 Mute 关闭响铃声音

In Session Settings -> Terminal -> Bell, you can select Mute to disable the ringtone

**Comment by Ma-Yunchao** [comment]
thanks，it's ok.
