### ISSUE TITLE
新建链接窗口屏蔽windows快捷键,无法切换窗口.

### ISSUE THREAD

**Issue by ser163** [kingToolbox/WindTerm#908]
新建链接窗口会屏蔽掉windows的window快捷键,无法切换窗口,这样就无法粘贴复制.

**Comment by 107295472** [comment]
为什么不打英文，他们能看懂吗?

**Comment by phx95** [comment]
> 为什么不打英文，他们能看懂吗?

帮友人们学汉语了，哈哈

**Comment by ser163** [comment]
作者不是中国人.我看那么多人用汉语在提,就直接写了一个.哈哈.
