### ISSUE TITLE
Nesting of session folders

### ISSUE THREAD

**Issue by karagi4** [kingToolbox/WindTerm#91]
Nesting of session folders, similar to that in SuperPutty. 
Is it possible to implement such a thing, would it be very convenient?
Thanks!
![image](https://user-images.githubusercontent.com/41114204/116231604-c2fda080-a761-11eb-8cbe-256e06706837.png)

**Comment by kingToolbox** [comment]
Currently, the design is very flat and simple. Each session has two attributes, one is `label` and the other is `group`, and when sessions are displayed, `group` will be displayed as a folder, and `label` will be displayed as a node, just as you can see in the  `Session` pane.

If sessions need to be displayed as a nested structure, a third attribute must be introduced, and it will be more complicated whether a session is created or managed. For example, to change a session from the folder `groupA` to another folder `groupB`, now only need to modify its group from `groupA` to `groupB`. If it is nested, you probably need to drag and drop or cut and paste the session on the session tree. 

The flat design is also more simple for a third-party to operate. Whether a plug-in needs to read and write sessions, or other clients/terminals need to import and export sessions, it will be very convenient. 

In addition, there are many new features to be completed based on the current `lable` and `group` design. For example, in the design of future command bar and chat mode, You can send the command to the specified sessions as convenient as the `@` function of twitter. Suppose you have three sessions:
| Lable | Group |
| --- | ---- |
| Mickey | |
| Tom | TomAndJerry |
| Jerry | TomAndJerry |

Then the following command in command bar or chat mode will complete the following operations: 
| Command | Description |
| --- | ---- |
| `@Mickey hello` | Send "hello" to the session Mickey |
| `@TomAndJerry hello` | Send "hello" to the session Tom and Jerry |
| `@Mickey,TomAndJerry hello` | Send "hello" to the session Mickey and Tom and Jerry |

If it is a nested structure, it is difficult to easily implement such a feature. Moreover, sessions in the same group may belong to different tree branches, which brings inconvenience to management. 

If a nested structure is necessary, I recommend naming the group name as a compound name, for example:

> - Folder1
>   server1 
> - Folder1 / Folder2 // Combine names using backslashs
>    10.0.0.1
>    10.0.0.2
> - Folder1, Folder3, Folder4 // Combine names using commas
>    127.0.0.1
>    127.0.0.2

**Comment by karagi4** [comment]
OK, this fits)) Can I do auto-opening and auto-opening of the session panel?

**Comment by kingToolbox** [comment]
Sorry, I am afraid auto-show/hide is not yet supported, but it may be possible after the docking framework is replaced by [Qt-Advanced-Docking-System](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System).

Many session opening methods have been provided so that the session pane is not necessary. You can completely close it and open sessions by typing the session name in the address bar(`Alt+D`) or command palette(`Alt+O`) to open it. If you need visualization, you can also open it through the tabbar menu below. The session pane only needs to be opened when you managing sessions. 

![image](https://user-images.githubusercontent.com/51009775/116270358-95d8de80-a7b1-11eb-89f9-cec31066ac11.png)

**Comment by kingToolbox** [comment]
BTW, when you move the mouse to the edge of the left/right/bottom pane and the cursor is displayed as the picture ![image](https://user-images.githubusercontent.com/51009775/116275247-0550cd00-a7b6-11eb-8b10-b6dd7c3bc8ca.png), you can open or hide the pane by double-clicking the edge. Although it is not auto-show/hide, it is still a litte convenient. Later, buttons will be provided on the status bar to more easily show or hide the panes.

**Comment by karagi4** [comment]
Thx!

**Comment by kingToolbox** [comment]
Anytime.

I checked the auto-hide development of Qt-Advanced-Docking-System and found [Can you add Auto Hide functionality?](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/issues/147), it looks like the feature is still under development. However, there are still a lot of new features of WindTerm to be completed. So it doesn't matter. I believe that the feature should already be available when the new docking framework is used. :laughing:

**Comment by karagi4** [comment]
Thx. It work now! 10.10.2021, 14:34, "kingToolbox" ***@***.***>: Hello, the feature nesting session groups you wanted has been provided in the new prerelease WindTerm_2.2.0_Prerelease_2. You only need to separate the group names with dots to get nested groups. E.g. a.b.c.d.Please download and check it, if you have any questions, please let me know, thank you.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.   --- ---С уважением,KA.
