### ISSUE TITLE
WindTerm does not restart when exited from fullscreen

### ISSUE THREAD

**Issue by Shellfishgene** [kingToolbox/WindTerm#93]
When I set WindTerm to full screen mode and the exit I can't restart it. If I start it nothing happens. I have to delete the `profile` folder, then it starts again.

**Comment by kingToolbox** [comment]
Thank you, I have confirmed that this is a bug. And I will fix it in the next prerelease version.

**Comment by gooker** [comment]
I cant start too,this is win10 Report.wer,remove profile is ok

C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_WindTerm_Win10

[Report.zip](https://github.com/kingToolbox/WindTerm/files/6490889/Report.zip)

**Comment by kingToolbox** [comment]
@gooker Thank you for your report. This is a bug and has been fixed, I am preparing to release a new prerelease version today or tomorrow. Currently deleting the file `profiles\default.v10\global\reopen.history` can circumvent this problem.

**Comment by kingToolbox** [comment]
Hi, [WindTerm_2.1.0_Prerelease_3](https://github.com/kingToolbox/WindTerm/releases/tag/2.1) has just been released and this issue has been fixed. You can download and check it now. Thank you.

**Comment by kingToolbox** [comment]
@Shellfishgene, @gooker If you often need to use the full screen mode, I recommend you to use the brand new `Focus Mode` in [WindTerm_2.1.0_prerelase_5](https://github.com/kingToolbox/WindTerm/releases/tag/2.1-prerelease), I believe it is better than the full screen mode. Welcome to download and use, thank you.

**Comment by gooker** [comment]
> @Shellfishgene, @gooker If you often need to use the full screen mode, I recommend you to use the brand new `Focus Mode` in [WindTerm_2.1.0_Prerelase_5](https://github.com/kingToolbox/WindTerm/releases/tag/2.1-prerelease), you can read [Focus Mode](https://kingtoolbox.github.io/2021/06/28/ui_focus_mode/) to learn more, I believe it is better than the full screen mode. Welcome to download and use, thank you.

focus_mode is great.

**Comment by kingToolbox** [comment]
This issue has been fixed and will be closed. Welcome to continue submitting new issues and feature requests, thank you.

**Comment by kingToolbox** [comment]
@gooker, I am glad you like this feature. :smile:
