### ISSUE TITLE
[HELP] How to restore default sender panel

### ISSUE THREAD

**Issue by pengtianabc** [kingToolbox/WindTerm#95]
I close default sender panel at bottom, and i don't know how to reopen it, i tried to drag the right panel to bottom, but it doesn't work.

**Comment by kingToolbox** [comment]
You can restore the sender pane by using either of the following methods:

- Click the menu `View - Panes - Sender`.
- Use the shortcut key `<Alt+W><Alt+X>`.
- Open the `Command Palette` by `<Alt+;>` then input `show pane sender` and press `enter`.
- Move the mouse to the bottom boundary and drag the sender pane up when the mouse becomes splitter shape.

**Comment by pengtianabc** [comment]
I 

> You can restore the sender pane by using either of the following methods:
> 
> * Click the menu `View - Panes - Sender`.
> * Use the shortcut key `<Alt+W><Alt+X>`.
> * Open the `Command Palette` by `<Alt+;>` then input `show pane sender` and press `enter`.
> * Move the mouse to the bottom boundary and drag the sender pane up when the mouse becomes splitter shape.
> 
> Future versions will support drag-and-drop panes.

I use the last method to solve it, thank you!

**Comment by kingToolbox** [comment]
My pleasure. This issue will be closed and welcome to continue submitting new issues and feature requests, thank you. 😄
