### ISSUE TITLE
有没有鼠标选中复制文本，右键点击粘贴文本的功能

### ISSUE THREAD

**Issue by zqxsober** [kingToolbox/WindTerm#957]
有没有鼠标选中复制文本，右键点击粘贴的功能？感觉这样会方便很多，希望后续版本可以支持

**Comment by myliwenbo** [comment]
![image](https://user-images.githubusercontent.com/29202248/182074535-657a747b-889f-4503-9b12-c86240e8f5f4.png)
本身是支持的

**Comment by myliwenbo** [comment]
![image](https://user-images.githubusercontent.com/29202248/182074646-f02b5df9-3706-4c75-aad4-d5b20b4f2405.png)
![image](https://user-images.githubusercontent.com/29202248/182074713-a3474bef-9fc3-47f2-bc40-dff003ceaca6.png)

是支持的
