### ISSUE TITLE
WindTerm Ask some questions?

### ISSUE THREAD

**Issue by 2416210017** [kingToolbox/WindTerm#965]
1、Can I cancel the text carriage return? As shown below
![image](https://user-images.githubusercontent.com/52597892/182281374-cfce0cab-ff34-4a7f-b252-6ff9ebb61d24.png)

2、Is there any setting that supports the paste of selected text with the middle button of the mouse? Thank you!
![B8304D1C-6EC9-4844-A6DD-5AA7A9F990F3](https://user-images.githubusercontent.com/52597892/182281423-0a56ec7b-1379-4e7d-8a1c-e6a0fbcd4932.png)

**Comment by 2416210017** [comment]
Question 1, I found the way to set it, thank you
But question 2 hasn't been found yet. I hope someone can help me look at it. Thank you

**Comment by laoola** [comment]
![image](https://user-images.githubusercontent.com/42239744/182302596-f4c74ed7-7a12-4065-8594-d95a80ffd073.png)
勾选这个就能中间复制粘贴了
