### ISSUE TITLE
希望增加端口转发功能

### ISSUE THREAD

**Issue by ranbest** [kingToolbox/WindTerm#97]
希望增加端口转发功能，这个功能还是比较有用的。希望作者考虑下（可以参考xshell）。

**Comment by kingToolbox** [comment]
Thank you. Do you mean SSH port forwarding? WindTerm already supports direct/local port forwarding, reverse/remote port forwarding and dynamic port forwarding, please read [Port Forwarding](https://kingtoolbox.github.io/2020/07/21/port_forwarding/) to learn how to use it.

**Comment by ranbest** [comment]
Thank you. That's what I need。
