### ISSUE TITLE
Screen clear problem.

### ISSUE THREAD

**Issue by gooker** [kingToolbox/WindTerm#98]
1. shell cmd "clear" / shortcut "ctrl+l" ,
    can't :"clear screen and move cursor to top-left corner control"

   (in top,send"enter"/q refresh or quit also have some problem)
![GIF](https://user-images.githubusercontent.com/5688076/119262633-76956b80-bc0e-11eb-83f4-cdbbdd901e6d.gif)

2. c language : printf("\033[2J"); 
    can't clear screen;

**Comment by kingToolbox** [comment]
This `clear` issue is a bit similar to #61 , and I failed to reproduce again. Can you tell me your server system name and version number printed by the command `lsb_release -a`? Thank you.

In your screen recording, I noticed that you did not turn on the `Mode - Word Wrap`, which caused only part of the text to be displayed on the screen when the cursor was asked to move to the end of the long line. This only needs to turn on `Word Wrap` to avoid this problem. 

In shell, please use `echo -e "\033[2J"` to clear the screen, `prinft` of c language does not work for shell.

**Comment by gooker** [comment]
> This `clear` issue is a bit similar to #61 , and I failed to reproduce again. Can you tell me your server system name and version number printed by the command `lsb_release -a`? Thank you.
> 
> In your screen recording, I noticed that you did not turn on the `Mode - Word Wrap`, which caused only part of the text to be displayed on the screen when the cursor was asked to move to the end of the long line. This only needs to turn on `Word Wrap` to avoid this problem.
> 
> In shell, please use `echo -e "\033[2J"` to clear the screen, `prinft` of c language does not work for shell.

my pc is win10, linux server is centos7.3 64bit (kernel 3.10.0),vmware 16.1.2.

echo -e "\033[2J" 
<img width="418" alt="20210524201432" src="https://user-images.githubusercontent.com/5688076/119346335-aacf6180-bccc-11eb-9cf1-1469b43ad2a5.png">
"

**Comment by gooker** [comment]
> This `clear` issue is a bit similar to #61 , and I failed to reproduce again. Can you tell me your server system name and version number printed by the command `lsb_release -a`? Thank you.
> 
> In your screen recording, I noticed that you did not turn on the `Mode - Word Wrap`, which caused only part of the text to be displayed on the screen when the cursor was asked to move to the end of the long line. This only needs to turn on `Word Wrap` to avoid this problem.
> 
> In shell, please use `echo -e "\033[2J"` to clear the screen, `prinft` of c language does not work for shell.

my pc is win10, linux server is centos7.3 64bit (kernel 3.10.0),vmware 16.1.2.

echo -e "\033[2J" 
<img width="418" alt="20210524201432" src="https://user-images.githubusercontent.com/5688076/119346335-aacf6180-bccc-11eb-9cf1-1469b43ad2a5.png">
"

**Comment by gooker** [comment]
turn on the Mode - Word Wrap,  everything is ok.

**Comment by kingToolbox** [comment]
Thank you, I will try to reproduce `clear screen` bug in the centos7.3 64bit. If there is a problem, I will fix it, but this work will be done after the version 2.2.0 is released. It is expected to be in August and September.
